(()=>{
 const list=document.getElementById('alertList'),summary=document.getElementById('summary'),refresh=document.getElementById('refreshAlerts');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={score_change:'Scoreendring',trend_activity:'Trend / aktivitet',early_opportunity:'Opportunity'};
 function time(value){if(!value)return 'Tidspunkt ukjent';const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString('nb-NO',{timeZone:'Europe/Oslo'}):'Tidspunkt ukjent'}
 function render(items){if(!items.length){list.innerHTML='<div class="notice">Ingen signalhendelser i tilgjengelig historikk.</div>';return}list.innerHTML=items.map(x=>{const ticker=String(x.ticker||x.symbol||'').toUpperCase().replace(/\.OL$/,'');const content='<span class="time">'+esc(names[x.event_type]||'Signalhendelse')+' · '+esc(time(x.updated_at))+' (Oslo)</span><h2>'+esc(x.name||ticker||'Marked')+'</h2><p>'+esc(x.event||'Registrert hendelse')+'</p>'+(x.detail?'<p class="muted">'+esc(x.detail)+'</p>':'');return /^[A-Z0-9.-]{1,16}$/.test(ticker)?'<a class="alertCard" href="/stock?ticker='+encodeURIComponent(ticker)+'">'+content+'<span>'+esc(ticker)+' →</span></a>':'<article class="alertCard">'+content+'</article>'}).join('')}
 async function load(){if(refresh.disabled)return;refresh.disabled=true;summary.textContent='Laster…';try{const r=await fetch('/api/signal-events?asset_class=Aksjer&limit=30',{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!Array.isArray(d.items))throw Error('Uventet dataformat');render(d.items);summary.textContent=d.items.length+' hendelser · maks 30 vist'}catch{list.innerHTML='<div class="notice">UTILGJENGELIG · kunne ikke hente signalhendelser. Prøv Oppdater igjen.</div>';summary.textContent='Kunne ikke laste'}finally{refresh.disabled=false}}
 refresh.onclick=load;load();
})();
