(function(){
  let state={days:30,data:null,query:'',filter:'all',busy:false};
  const E=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const N=v=>v==null?'—':Number(v).toLocaleString('no-NO',{maximumFractionDigits:0});
  const D=v=>v?String(v).slice(0,10):'—';
  function M(v,c='NOK'){
    if(v==null)return '—';const x=Math.abs(Number(v));let s;
    if(x>=1e9)s=(x/1e9).toLocaleString('no-NO',{maximumFractionDigits:2})+' mrd.';
    else if(x>=1e6)s=(x/1e6).toLocaleString('no-NO',{maximumFractionDigits:2})+' mill.';
    else if(x>=1e3)s=(x/1e3).toLocaleString('no-NO',{maximumFractionDigits:1})+'k';
    else s=x.toLocaleString('no-NO',{maximumFractionDigits:0});
    return s+' '+(c||'');
  }
  function qnorm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9æøå]+/g,' ').trim()}
  function actor(x){return x?.person||x?.entity||x?.insider||(x?.details_pending?'Detaljer venter':'Ikke oppgitt')}
  function pulseValue(p){return (p?.values||[]).map(x=>M((x.buy||0)+(x.sell||0),x.currency)).filter(Boolean).join(' · ')||'—'}
  function tone(p){return p?.tone==='positive'?'positive':p?.tone==='negative'?'negative':'neutral'}
  function typeOf(x){if(x?.details_pending)return 'pending';if(x?.signal_eligible&&x?.direction==='buy')return 'buy';if(x?.signal_eligible&&x?.direction==='sell')return 'sell';return 'other'}
  function labelOf(x){const t=typeOf(x);return t==='buy'?'KJØP':t==='sell'?'SALG':t==='pending'?'DETALJER VENTER':'ANNEN MELDING'}
  function searchTextPulse(p){return qnorm([p?.company,p?.ticker,...(p?.actors||[])].join(' '))}
  function searchTextItem(x){return qnorm([x?.company,x?.ticker,actor(x),x?.role,x?.title,x?.summary].join(' '))}
  function matchesFilterItem(x){const t=typeOf(x);return state.filter==='all'||state.filter===t}
  function matchesFilterPulse(p){if(state.filter==='buy')return Number(p?.buy_count||0)>0;if(state.filter==='sell')return Number(p?.sell_count||0)>0;if(state.filter==='pending')return !p?.buy_count&&!p?.sell_count;return true}
  function stockLink(ticker,company){const t=String(ticker||'').trim();return t?`<button class="nsInsCompany" data-ticker="${E(t)}">${E(company||t)}</button>`:`<span class="nsInsCompanyText">${E(company||'Ukjent selskap')}</span>`}
  function ensureStyle(){if(document.getElementById('nsInsiderCleanStyle'))return;const s=document.createElement('style');s.id='nsInsiderCleanStyle';s.textContent=`
    .nsInsiderTools{display:flex;gap:10px;justify-content:space-between;align-items:center;flex-wrap:wrap;margin:18px 0 14px}.nsInsiderSearch{min-width:280px;flex:1;max-width:520px;background:#0a1727;border:1px solid var(--line);color:var(--t);border-radius:10px;padding:11px 13px;outline:0}.nsInsiderSearch:focus{border-color:#53779a}.nsInsiderFilters{display:flex;gap:7px;flex-wrap:wrap}.nsInsiderFilters button{border:1px solid var(--line);background:#0a1727;color:var(--m);border-radius:999px;padding:8px 11px;cursor:pointer;font-weight:750}.nsInsiderFilters button.active{background:#eef5ff;color:#07111f;border-color:#eef5ff}.nsInsiderCount{font-size:11px;color:var(--m);margin:6px 0 12px}.nsPulseGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.nsPulseCard{background:#0a1727;border:1px solid var(--line);border-radius:12px;padding:14px;min-width:0}.nsPulseTop{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.nsInsCompany,.nsInsCompanyText{font:inherit;font-weight:850;color:var(--t);background:none;border:0;padding:0;text-align:left;cursor:pointer}.nsInsCompany:hover{color:var(--g)}.nsTicker{font-size:10px;color:var(--m);margin-top:2px}.nsSignalPill{white-space:nowrap;border-radius:999px;padding:5px 8px;font-size:9px;font-weight:900;border:1px solid #34495d}.nsSignalPill.positive{color:var(--g);background:#0c2a22;border-color:#245c49}.nsSignalPill.negative{color:var(--r);background:#2c1219;border-color:#6a2c39}.nsSignalPill.neutral{color:var(--y);background:#2c250f;border-color:#665523}.nsPulseMetrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.nsPulseMetric{border-top:1px solid var(--line);padding-top:8px;min-width:0}.nsPulseMetric span{display:block;font-size:9px;color:var(--m);text-transform:uppercase;letter-spacing:.04em}.nsPulseMetric b{display:block;margin-top:3px;font-size:12px;overflow-wrap:anywhere}.nsActors{display:flex;gap:5px;flex-wrap:wrap;margin-top:10px}.nsActorChip{font-size:9px;border:1px solid var(--line);border-radius:999px;padding:4px 6px;color:#c8d6e6}.nsActivityList{display:grid;gap:8px}.nsTradeRow{display:grid;grid-template-columns:95px minmax(180px,1.1fr) minmax(180px,1fr) 105px 105px 105px 80px;gap:10px;align-items:center;padding:11px 12px;background:#0a1727;border:1px solid var(--line);border-radius:10px}.nsTradeDate,.nsTradeMeta{color:var(--m);font-size:10px}.nsTradeActor{font-weight:800;overflow-wrap:anywhere}.nsTradeBadge{display:inline-flex;width:max-content;border-radius:999px;padding:5px 7px;font-size:9px;font-weight:900}.nsTradeBadge.buy{color:var(--g);background:#0c2a22}.nsTradeBadge.sell{color:var(--r);background:#2c1219}.nsTradeBadge.pending,.nsTradeBadge.other{color:var(--y);background:#2c250f}.nsSourceLink{color:var(--m);font-size:10px}.nsInsEmpty{padding:24px;text-align:center;border:1px dashed var(--line);border-radius:10px;color:var(--m)}
    @media(max-width:1050px){.nsTradeRow{grid-template-columns:85px 1fr 1fr 90px}.nsTradeRow>:nth-child(5),.nsTradeRow>:nth-child(6),.nsTradeRow>:nth-child(7){display:none}}
    @media(max-width:700px){.nsPulseGrid{grid-template-columns:1fr}.nsPulseMetrics{grid-template-columns:repeat(2,1fr)}.nsInsiderSearch{min-width:100%;max-width:none}.nsTradeRow{grid-template-columns:1fr auto;gap:6px}.nsTradeRow>:nth-child(1){grid-column:1}.nsTradeRow>:nth-child(2){grid-column:1}.nsTradeRow>:nth-child(3){grid-column:1}.nsTradeRow>:nth-child(4){grid-column:2;grid-row:1 / span 2}.nsTradeRow>:nth-child(n+5){display:none}.nsInsiderTools{align-items:stretch}}
  `;document.head.appendChild(s)}
  async function getData(force=false){const r=await fetch(`/api/insider-market?limit=100&days=${state.days}${force?'&refresh=true':''}`,{cache:'no-store'});if(!r.ok)throw Error('Insider feed '+r.status);return r.json()}
  function renderStats(d){const pulses=d?.pulses||[],items=d?.items||[];const clusters=pulses.filter(p=>p.flags?.includes('cluster_buying')).length,sells=items.filter(x=>x.signal_eligible&&x.direction==='sell').length;return `<section class="cards"><div class="card"><div class="label">Verifiserte handler</div><div class="value">${N(d?.eligible_trade_count||0)}</div><div class="sub">ordinære kjøp og salg</div></div><div class="card"><div class="label">Klyngekjøp</div><div class="value g">${N(clusters)}</div><div class="sub">flere kjøpere i samme selskap</div></div><div class="card"><div class="label">Innsidersalg</div><div class="value r">${N(sells)}</div><div class="sub">ordinære salg</div></div><div class="card"><div class="label">Offisielle meldinger</div><div class="value y">${N(d?.disclosure_count||items.length)}</div><div class="sub">${N(d?.pending_detail_count||0)} venter på detaljer</div></div></section>`}
  function renderPulse(p){const actors=(p.actors||[]).slice(0,4),pending=!p.buy_count&&!p.sell_count;return `<article class="nsPulseCard"><div class="nsPulseTop"><div>${stockLink(p.ticker,p.company)}<div class="nsTicker">${E(p.ticker||'Ticker ikke identifisert')}</div></div><span class="nsSignalPill ${tone(p)}">${E(pending?'OFFISIELL MELDING':p.signal_label||'AKTIVITET')}</span></div><div class="nsPulseMetrics"><div class="nsPulseMetric"><span>Kjøp</span><b class="g">${N(p.buy_count||0)}</b></div><div class="nsPulseMetric"><span>Salg</span><b class="r">${N(p.sell_count||0)}</b></div><div class="nsPulseMetric"><span>Rapportert verdi</span><b>${E(pulseValue(p))}</b></div><div class="nsPulseMetric"><span>Siste</span><b>${E(D(p.latest_date))}</b></div></div><div class="nsActors">${actors.length?actors.map(a=>`<span class="nsActorChip">${E(a)}</span>`).join(''):`<span class="nsActorChip">${pending?'Detaljer kan vente':'Aktør ikke oppgitt'}</span>`}${(p.actors||[]).length>4?`<span class="nsActorChip">+${p.actors.length-4}</span>`:''}</div></article>`}
  function renderTrade(x){const t=typeOf(x),price=x.price==null?'—':Number(x.price).toLocaleString('no-NO',{maximumFractionDigits:4})+' '+(x.currency||'');return `<article class="nsTradeRow"><div class="nsTradeDate">${E(D(x.trade_date||x.date||x.published_at))}</div><div>${stockLink(x.ticker,x.company)}<div class="nsTicker">${E(x.ticker||'')}</div></div><div><div class="nsTradeActor">${E(actor(x))}</div><div class="nsTradeMeta">${E(x.role||'')}</div></div><span class="nsTradeBadge ${t}">${E(labelOf(x))}</span><div><b>${E(N(x.shares))}</b><div class="nsTradeMeta">aksjer</div></div><div><b>${E(price)}</b>${x.display_value!=null?`<div class="nsTradeMeta">${E(M(x.display_value,x.currency))}</div>`:''}</div><div>${x.url?`<a class="nsSourceLink" href="${E(x.url)}" target="_blank" rel="noopener">Original</a>`:'—'}</div></article>`}
  function filtered(){const d=state.data||{},q=qnorm(state.query);let pulses=(d.pulses||[]).filter(matchesFilterPulse),items=(d.items||[]).filter(matchesFilterItem);if(q){pulses=pulses.filter(p=>searchTextPulse(p).includes(q));items=items.filter(x=>searchTextItem(x).includes(q))}else{pulses=pulses.filter(p=>p.buy_count||p.sell_count)}return {pulses,items}}
  function paintLists(){const f=filtered(),ph=document.getElementById('nsPulseCards'),ih=document.getElementById('nsTradeList'),count=document.getElementById('nsInsiderCount');if(!ph||!ih||!count)return;const pulseShow=state.query?f.pulses:f.pulses.slice(0,20),itemShow=state.query?f.items:f.items.slice(0,30);count.textContent=state.query?`Søk «${state.query}» · ${f.pulses.length} selskapsfunn · ${f.items.length} hendelser`:`Viser ${pulseShow.length} prioriterte selskaper og ${itemShow.length} siste hendelser`;ph.innerHTML=pulseShow.length?pulseShow.map(renderPulse).join(''):`<div class="nsInsEmpty" style="grid-column:1/-1">Ingen selskaper matcher søket/filteret. Prøv ticker, for eksempel XPLRA.</div>`;ih.innerHTML=itemShow.length?itemShow.map(renderTrade).join(''):`<div class="nsInsEmpty">Ingen konkrete hendelser matcher. Hvis selskapet bare har en offisiell melding som fortsatt venter på detaljdata, kan det fortsatt vises i selskapsoversikten over.</div>`;document.querySelectorAll('.nsInsCompany[data-ticker]').forEach(b=>b.onclick=()=>showStock(b.dataset.ticker))}
  function bind(){const q=document.getElementById('nsInsiderSearch');if(q)q.oninput=()=>{state.query=q.value.trim();paintLists()};document.querySelectorAll('[data-ins-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.insFilter;document.querySelectorAll('[data-ins-filter]').forEach(x=>x.classList.toggle('active',x===b));paintLists()});document.querySelectorAll('[data-ins-days]').forEach(b=>b.onclick=()=>{state.days=Number(b.dataset.insDays)||30;document.querySelectorAll('[data-ins-days]').forEach(x=>x.classList.toggle('active',x===b));load(false)});const r=document.getElementById('nsInsiderRefresh');if(r)r.onclick=()=>load(true)}
  function shell(){return `<div id="nsInsiderStatsHost"></div><section class="section"><div class="toolbar"><div><h2 style="margin:0">Insider Pulse</h2><div class="sub">Ryddig markedsoversikt · Euronext Oslo Børs · søk på selskap, ticker eller aktør</div></div><div class="controls"><button class="btn ${state.days===7?'active':''}" data-ins-days="7">7d</button><button class="btn ${state.days===14?'active':''}" data-ins-days="14">14d</button><button class="btn ${state.days===30?'active':''}" data-ins-days="30">30d</button><button class="btn" id="nsInsiderRefresh">Oppdater</button></div></div><div class="nsInsiderTools"><input id="nsInsiderSearch" class="nsInsiderSearch" placeholder="Søk selskap, ticker eller insider — f.eks. XPLRA"><div class="nsInsiderFilters"><button class="active" data-ins-filter="all">Alle</button><button data-ins-filter="buy">Kjøp</button><button data-ins-filter="sell">Salg</button><button data-ins-filter="pending">Venter</button></div></div><div id="nsInsiderCount" class="nsInsiderCount"></div><div id="nsPulseCards" class="nsPulseGrid"><div class="notice" style="grid-column:1/-1">Laster Insider Pulse…</div></div></section><section class="section"><div class="toolbar"><div><h2 style="margin:0">Siste handler og meldinger</h2><div class="sub">Konkrete verifiserte transaksjoner. Offisielle Euronext-meldinger beholdes synlige når detaljene venter.</div></div></div><div id="nsTradeList" class="nsActivityList"><div class="notice">Laster…</div></div></section>`}
  async function load(force){if(state.busy)return;state.busy=true;try{state.data=await getData(force);const stats=document.getElementById('nsInsiderStatsHost');if(stats)stats.innerHTML=renderStats(state.data);paintLists()}catch(e){const ph=document.getElementById('nsPulseCards'),ih=document.getElementById('nsTradeList');if(ph)ph.innerHTML='<div class="notice" style="grid-column:1/-1">Insider Pulse er midlertidig utilgjengelig.</div>';if(ih)ih.innerHTML='<div class="notice">Kunne ikke hente insidermeldinger akkurat nå.</div>';console.warn(e)}finally{state.busy=false}}
  window.renderInsider=async function(){ensureStyle();state.query='';state.filter='all';setTitle('Insider Pulse','Market-wide primærinsideraktivitet fra Euronext Oslo Børs');appview.innerHTML=`<div id="nsInsiderRoot">${shell()}</div>`;bind();await load(false)};
})();
