(function(){
  const esc=v=>String(v==null?'':v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const nok=v=>v==null?'—':Number(v).toLocaleString('no-NO',{maximumFractionDigits:0})+' kr';
  const pct=v=>v==null?'—':(Number(v)>=0?'+':'')+Number(v).toLocaleString('no-NO',{maximumFractionDigits:2})+'%';
  let compareBenchmark='OSEBX',comparePeriod='1y',compareSeq=0,pulseMode='news',pulseTimer=null,pulseSeq=0,homeSeq=0;
  let currentEvents=[],currentCalendar=[];

  function styles(){
    if(document.getElementById('nsPortfolioHomeStyles'))return;
    const s=document.createElement('style');s.id='nsPortfolioHomeStyles';s.textContent=`
      .nsHomeWrap{margin-top:22px}.nsHomeCards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}
      .nsHomeCard,.nsHomePanel{background:#101010;border:1px solid #282828;border-radius:12px}.nsHomeCard{padding:17px 18px}.nsHomeCard .k{color:#8d8d8d;font-size:11px}.nsHomeCard .v{font-size:24px;font-weight:850;margin-top:5px;letter-spacing:-.02em}.nsHomeCard .m{color:#777;font-size:10px;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
      .nsHomeGrid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(330px,.75fr);gap:16px}.nsHomePanel{padding:18px}.nsHomeHead{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:12px}.nsHomeHead h2{margin:0;font-size:17px}.nsHomeHead p{margin:4px 0 0;color:#858585;font-size:11px}.nsHomeLink{color:#d8d8d8;font-size:11px;text-decoration:none;border:1px solid #303030;border-radius:8px;padding:7px 9px;white-space:nowrap}.nsHomeLink:hover{border-color:#555;color:#fff}
      .nsHoldingRow{display:grid;grid-template-columns:minmax(160px,1.4fr) .85fr .7fr .55fr;gap:12px;align-items:center;padding:13px 2px;border-top:1px solid #242424;cursor:pointer}.nsHoldingRow:first-of-type{border-top:0}.nsHoldingRow:hover .nsHoldingName{color:#35d49a}.nsHoldingName{font-weight:800}.nsTicker{display:block;color:#747474;font-size:10px;margin-top:3px}.nsRight{text-align:right}.nsPos{color:#35d49a}.nsNeg{color:#fb7185}.nsWeight{height:4px;background:#242424;border-radius:99px;margin-top:6px;overflow:hidden}.nsWeight i{display:block;height:100%;background:#717171;border-radius:99px}
      .nsBriefLead{border:1px solid #292929;background:#0c0c0c;border-radius:9px;padding:11px 12px;margin-bottom:4px}.nsBriefLead b{font-size:11px}.nsBriefLead span{display:block;color:#858585;font-size:10px;line-height:1.45;margin-top:4px}.nsBriefMark{display:inline-flex;align-items:center;border:1px solid #3a3a3a;border-radius:999px;padding:4px 7px;color:#c9c9c9;font-size:9px;font-weight:850;letter-spacing:.04em}
      .nsPulseTabs{display:flex;gap:4px;padding:3px;background:#0b0b0b;border:1px solid #292929;border-radius:9px;margin:0 0 8px}.nsPulseTab{flex:1;border:0;background:transparent;color:#888;border-radius:6px;padding:7px 8px;font:750 10px system-ui;cursor:pointer}.nsPulseTab.active{background:#ededed;color:#090909}.nsPulseFoot{display:flex;justify-content:space-between;gap:10px;align-items:center;color:#666;font-size:9px;border-top:1px solid #222;padding-top:10px;margin-top:4px}.nsPulseFoot a{color:#aaa;text-decoration:none}.nsPulseFoot a:hover{color:#fff}
      .nsEvent{display:block;padding:13px 0;border-top:1px solid #242424;text-decoration:none;color:#eee}.nsEvent:first-of-type{border-top:0}.nsEventTop{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.nsEventTicker{font-size:10px;font-weight:850;color:#bdbdbd}.nsEventBadge{font-size:9px;font-weight:900;letter-spacing:.03em;padding:3px 6px;border-radius:999px;border:1px solid #393939;color:#aaa}.nsEventBadge.report{color:#e7c16b;border-color:#554923;background:#17150c}.nsEventBadge.buy{color:#35d49a;border-color:#24503f;background:#0d1814}.nsEventBadge.sell{color:#fb7185;border-color:#5b2b34;background:#1b0f12}.nsEventBadge.important{color:#ffcb73;border-color:#624824;background:#1c160d}.nsEventTitle{font-weight:750;font-size:12px;margin-top:7px;line-height:1.35}.nsEventBrief{color:#a2a2a2;font-size:10px;line-height:1.5;margin-top:5px}.nsEventMeta{color:#6f6f6f;font-size:9px;margin-top:5px}
      .nsCalendarRow{display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:11px;align-items:center;padding:12px 0;border-top:1px solid #242424;text-decoration:none;color:#eee}.nsCalendarRow:first-of-type{border-top:0}.nsCalendarDate{width:42px;text-align:center;border:1px solid #303030;border-radius:8px;background:#0b0b0b;padding:5px 2px}.nsCalendarDate b{display:block;font-size:15px}.nsCalendarDate span{display:block;color:#777;font-size:8px;text-transform:uppercase;margin-top:1px}.nsCalendarMain b{font-size:11px}.nsCalendarMain span{display:block;color:#797979;font-size:9px;margin-top:3px}.nsCalendarDays{font-size:9px;color:#929292;white-space:nowrap}
      .nsCompare{margin-top:16px}.nsCompareHead{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;flex-wrap:wrap}.nsCompareControls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.nsCompareSelect{appearance:auto;background:#0b0b0b;color:#eee;border:1px solid #303030;border-radius:8px;padding:8px 28px 8px 9px;font:650 11px system-ui;outline:none}.nsPeriods{display:flex;gap:4px;padding:3px;border:1px solid #292929;border-radius:9px;background:#0b0b0b}.nsPeriod{border:0;background:transparent;color:#858585;border-radius:6px;padding:6px 8px;font:750 10px system-ui;cursor:pointer}.nsPeriod.active{background:#ededed;color:#090909}.nsCompareStats{display:flex;gap:28px;flex-wrap:wrap;margin:18px 0 8px}.nsCompareStat span{display:block;color:#777;font-size:10px}.nsCompareStat b{display:block;font-size:17px;margin-top:4px}.nsChartWrap{position:relative;height:285px;margin-top:6px}.nsChartWrap svg{width:100%;height:100%;display:block;overflow:visible}.nsChartGrid{stroke:#242424;stroke-width:1}.nsChartZero{stroke:#3a3a3a;stroke-width:1}.nsPortfolioLine{fill:none;stroke:#35d49a;stroke-width:2.5;stroke-linejoin:round;stroke-linecap:round}.nsBenchmarkLine{fill:none;stroke:#d7d7d7;stroke-width:1.8;stroke-linejoin:round;stroke-linecap:round;opacity:.78}.nsChartLabel{fill:#727272;font-size:9px}.nsCompareLegend{display:flex;gap:18px;align-items:center;flex-wrap:wrap;color:#8b8b8b;font-size:10px;margin-top:8px}.nsLegendDot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px}.nsLegendDot.portfolio{background:#35d49a}.nsLegendDot.benchmark{background:#d7d7d7}.nsCompareNote{color:#666;font-size:9px;line-height:1.45;margin-top:10px}.nsCompareLoading{height:250px;display:flex;align-items:center;justify-content:center;color:#777}.nsEmptyHome{padding:28px 18px;text-align:center;color:#888}.nsEmptyHome b{display:block;color:#eee;font-size:16px;margin-bottom:7px}.nsHomeSkeleton{padding:24px;color:#888;background:#101010;border:1px solid #282828;border-radius:12px}.nsFastHint{font-size:9px;color:#626262;margin-top:8px}
      @media(max-width:1050px){.nsHomeCards{grid-template-columns:repeat(2,1fr)}.nsHomeGrid{grid-template-columns:1fr}}
      @media(max-width:650px){.nsHomeCards{grid-template-columns:repeat(2,1fr)}.nsHomeCard{padding:14px}.nsHomeCard .v{font-size:20px}.nsHoldingRow{grid-template-columns:1fr .8fr .65fr}.nsHoldingRow>:nth-child(4){display:none}.nsHomePanel{padding:15px}.nsCompareControls{width:100%}.nsCompareSelect{width:100%}.nsChartWrap{height:230px}.nsCompareStats{gap:16px}}
    `;document.head.appendChild(s);
  }

  async function dashboardPhase(phase){const r=await fetch('/api/dashboard-home?mode=desktop&phase='+encodeURIComponent(phase),{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||('HTTP '+r.status));return d}
  function eventLabel(x){if(x.kind==='report')return ['RAPPORT','report'];if(x.kind==='insider'&&x.direction==='buy')return ['INSIDER KJØP','buy'];if(x.kind==='insider'&&x.direction==='sell')return ['INSIDER SALG','sell'];if(x.kind==='insider')return ['INSIDER',''];if(x.kind==='dividend')return ['UTBYTTE',''];return [String(x.category||'HENDELSE').toUpperCase(),'']}
  function eventHref(x){const tab=x.kind==='report'?'reports':x.kind==='insider'?'insider':x.kind==='dividend'?'dividend':'news';return '/stock?ticker='+encodeURIComponent(String(x.ticker||'').replace(/\.OL$/,''))+'&tab='+tab}
  function dateLabel(x){if(!x.occurred_at)return 'Dato ikke oppgitt';try{return new Date(x.occurred_at).toLocaleDateString('no-NO',{day:'2-digit',month:'short',year:'numeric'})}catch{return x.occurred_at}}
  function holdingRows(items){const sorted=[...(items||[])].sort((a,b)=>Number(b.market_value||0)-Number(a.market_value||0)).slice(0,8);if(!sorted.length)return '<div class="nsEmptyHome"><b>Ingen aksjer i beholdningen ennå</b>Legg inn aksjene dine, så blir forsiden automatisk tilpasset dem.</div>';return sorted.map(x=>{const pnl=x.unrealized_pnl,cls=pnl==null?'':Number(pnl)>=0?'nsPos':'nsNeg',weight=Math.max(0,Math.min(100,Number(x.portfolio_weight_pct||0)));return `<div class="nsHoldingRow" data-ns-holding="${esc(x.ticker)}"><div><span class="nsHoldingName">${esc(x.company_name||x.instrument_name||x.ticker)}</span><span class="nsTicker">${esc(x.ticker)} · ${esc(x.account_type||'')}</span></div><div class="nsRight"><b>${nok(x.market_value)}</b><div class="nsWeight"><i style="width:${weight}%"></i></div></div><div class="nsRight ${cls}"><b>${nok(pnl)}</b><span class="nsTicker">${pct(x.unrealized_pnl_pct)}</span></div><div class="nsRight"><b>${Number(x.portfolio_weight_pct||0).toLocaleString('no-NO',{maximumFractionDigits:1})}%</b><span class="nsTicker">vekt</span></div></div>`}).join('')}
  function eventRows(items){const list=(items||[]).slice(0,6);if(!list.length)return '<div class="nsEmptyHome"><b>Ingen viktige hendelser akkurat nå</b>Når en aksje i beholdningen får rapport, insiderhandel eller viktig børsmelding, vises den her.</div>';const high=list.filter(x=>x.importance==='high').length;const lead=`<div class="nsBriefLead"><b>Kort fortalt</b><span>${high?high+' viktige hendelse'+(high===1?'':'r')+' ligger øverst. ':''}NordicSignal kobler offisielle hendelser med markedsreaksjon og viser bare det som gjelder aksjene du eier.</span></div>`;return lead+list.map(x=>{const [label,cls]=eventLabel(x),important=x.importance==='high'?'<span class="nsEventBadge important">VIKTIG</span>':'';return `<a class="nsEvent" href="${eventHref(x)}"><div class="nsEventTop"><span class="nsEventTicker">${esc(String(x.ticker||'').replace(/\.OL$/,''))}</span><span class="nsEventBadge ${cls}">${esc(label)}</span>${important}</div><div class="nsEventTitle">${esc(x.title)}</div>${x.brief?`<div class="nsEventBrief">${esc(x.brief)}</div>`:''}<div class="nsEventMeta">${esc(x.company||x.ticker)} · ${esc(dateLabel(x))}</div></a>`}).join('')}
  function calendarHref(x){if(x.ticker){const tab=x.event_type==='report'?'reports':'overview';return '/stock?ticker='+encodeURIComponent(x.ticker)+'&tab='+tab}return x.url||'/calendar'}
  function calendarRows(items){const list=(items||[]).slice(0,7);if(!list.length)return '<div class="nsEmptyHome"><b>Ingen planlagte hendelser funnet</b>Kalenderen oppdateres fra den offisielle Oslo Børs-finanskalenderen.</div>';return list.map(x=>{let d;try{d=new Date(String(x.date)+'T12:00:00')}catch{}const day=d&&!Number.isNaN(d.getTime())?String(d.getDate()).padStart(2,'0'):'—',month=d&&!Number.isNaN(d.getTime())?d.toLocaleDateString('no-NO',{month:'short'}):'',when=Number(x.days_until)===0?'I dag':Number(x.days_until)===1?'I morgen':Number(x.days_until)>1?'om '+x.days_until+' dager':'';return `<a class="nsCalendarRow" href="${esc(calendarHref(x))}"${!x.ticker&&x.url?' target="_blank" rel="noopener"':''}><span class="nsCalendarDate"><b>${esc(day)}</b><span>${esc(month)}</span></span><span class="nsCalendarMain"><b>${esc(x.ticker?x.ticker+' · '+x.event_label:x.company+' · '+x.event_label)}</b><span>${esc(x.company||'Oslo Børs')} · ${esc(x.event_raw||x.event_label||'Hendelse')}</span></span><span class="nsCalendarDays">${esc(when)}</span></a>`}).join('')}
  function renderPulse(){const body=document.getElementById('nsPulseBody');if(!body)return;document.querySelectorAll('.nsPulseTab').forEach(b=>b.classList.toggle('active',b.dataset.mode===pulseMode));body.innerHTML=pulseMode==='upcoming'?calendarRows(currentCalendar):eventRows(currentEvents)}
  function comparePanel(){return `<section class="nsHomePanel nsCompare"><div class="nsCompareHead"><div><h2>Utvikling mot markedet</h2><p>Din beholdningsmiks mot valgt indeks · start = 0 %</p></div><div class="nsCompareControls"><select id="nsCompareSelect" class="nsCompareSelect"><option value="OSEBX">OSEBX</option><option value="OSEAX">OSEAX</option><option value="SP500">S&P 500</option><option value="NASDAQ100">Nasdaq 100</option><option value="OMXS30">OMX Stockholm 30</option><option value="DAX">DAX</option></select><div class="nsPeriods">${[['1m','1M'],['3m','3M'],['1y','1Å'],['3y','3Å'],['5y','5Å']].map(([id,label])=>`<button class="nsPeriod${id===comparePeriod?' active':''}" data-period="${id}">${label}</button>`).join('')}</div></div></div><div id="nsCompareBody"><div class="nsCompareLoading">Laster sammenligning etter hovedinnholdet…</div></div></section>`}
  function pathFor(rows,key,min,max,w=900,h=260,p=28){const span=Math.max(.0001,max-min),count=Math.max(1,rows.length-1),pts=[];rows.forEach((r,i)=>{const v=Number(r[key]);if(!Number.isFinite(v))return;const x=p+(w-p*2)*(i/count),y=p+(h-p*2)*(1-(v-min)/span);pts.push((pts.length?'L':'M')+x.toFixed(1)+' '+y.toFixed(1))});return pts.join(' ')}
  function chartMarkup(d){const rows=(d.series||[]).filter(x=>Number.isFinite(Number(x.portfolio_pct))&&Number.isFinite(Number(x.benchmark_pct)));if(rows.length<2)return '<div class="nsEmptyHome"><b>Ikke nok historikk til sammenligning</b>Prøv en kortere periode eller en annen indeks.</div>';const values=[];rows.forEach(x=>values.push(Number(x.portfolio_pct),Number(x.benchmark_pct)));values.push(0);let min=Math.min(...values),max=Math.max(...values);const pad=Math.max(1,(max-min)*.12);min-=pad;max+=pad;const w=900,h=260,p=28,span=Math.max(.0001,max-min),zeroY=p+(h-p*2)*(1-(0-min)/span),portfolioPath=pathFor(rows,'portfolio_pct',min,max,w,h,p),benchmarkPath=pathFor(rows,'benchmark_pct',min,max,w,h,p),pCls=Number(d.portfolio_return_pct)>=0?'nsPos':'nsNeg',bCls=Number(d.benchmark_return_pct)>=0?'nsPos':'nsNeg',diffCls=Number(d.difference_pp)>=0?'nsPos':'nsNeg';const labels=[max,(max+min)/2,min].map(v=>{const y=p+(h-p*2)*(1-(v-min)/span);return `<text x="${p}" y="${Math.max(10,y-4)}" class="nsChartLabel">${Number(v).toLocaleString('no-NO',{maximumFractionDigits:1})}%</text>`}).join('');return `<div class="nsCompareStats"><div class="nsCompareStat"><span>Min beholdning · ${esc(d.period_label)}</span><b class="${pCls}">${pct(d.portfolio_return_pct)}</b></div><div class="nsCompareStat"><span>${esc(d.benchmark_label)}</span><b class="${bCls}">${pct(d.benchmark_return_pct)}</b></div><div class="nsCompareStat"><span>Forskjell</span><b class="${diffCls}">${d.difference_pp==null?'—':pct(d.difference_pp).replace('%',' pp')}</b></div></div><div class="nsChartWrap"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line x1="${p}" x2="${w-p}" y1="${zeroY}" y2="${zeroY}" class="nsChartZero"></line><line x1="${p}" x2="${w-p}" y1="${p}" y2="${p}" class="nsChartGrid"></line><line x1="${p}" x2="${w-p}" y1="${h-p}" y2="${h-p}" class="nsChartGrid"></line>${labels}<path d="${portfolioPath}" class="nsPortfolioLine"></path><path d="${benchmarkPath}" class="nsBenchmarkLine"></path></svg></div><div class="nsCompareLegend"><span><i class="nsLegendDot portfolio"></i>Min beholdning</span><span><i class="nsLegendDot benchmark"></i>${esc(d.benchmark_label)}</span></div><div class="nsCompareNote">${esc(d.note||'')}</div>`}
  async function loadComparison(){const body=document.getElementById('nsCompareBody'),select=document.getElementById('nsCompareSelect');if(!body)return;if(select)select.value=compareBenchmark;document.querySelectorAll('.nsPeriod').forEach(b=>b.classList.toggle('active',b.dataset.period===comparePeriod));body.innerHTML='<div class="nsCompareLoading">Laster sammenligning…</div>';const mine=++compareSeq;try{const r=await fetch('/api/holdings/compare?benchmark='+encodeURIComponent(compareBenchmark)+'&period='+encodeURIComponent(comparePeriod),{cache:'no-store'}),d=await r.json().catch(()=>({}));if(mine!==compareSeq)return;if(!r.ok)throw Error(d.detail||('HTTP '+r.status));body.innerHTML=chartMarkup(d)}catch(e){if(mine!==compareSeq)return;body.innerHTML='<div class="nsEmptyHome"><b>Sammenligningen er midlertidig utilgjengelig</b>Resten av forsiden fungerer fortsatt.</div>'}}
  function updatePulseCards(events,calendar){const important=document.getElementById('nsImportantValue'),nextValue=document.getElementById('nsNextEventValue'),nextMeta=document.getElementById('nsNextEventMeta');if(important)important.textContent=String(events?.high_priority_count||0);const next=(calendar?.items||[])[0];if(nextValue)nextValue.textContent=!next?'—':Number(next.days_until)===0?'I dag':Number(next.days_until)===1?'I morgen':next.days_until+' d';if(nextMeta)nextMeta.textContent=next?(String(next.ticker||next.company)+' · '+String(next.event_label||next.event_raw||'Hendelse')):'Ingen planlagt hendelse funnet'}
  function bindHome(){document.querySelectorAll('[data-ns-holding]').forEach(el=>el.onclick=()=>{const t=String(el.dataset.nsHolding||'').replace(/\.OL$/,'');if(typeof showStock==='function')showStock(t);else location.href='/stock?ticker='+encodeURIComponent(t)});document.querySelectorAll('.nsPulseTab').forEach(b=>b.onclick=()=>{pulseMode=b.dataset.mode||'news';renderPulse()});const select=document.getElementById('nsCompareSelect');if(select)select.onchange=()=>{compareBenchmark=select.value;loadComparison()};document.querySelectorAll('.nsPeriod').forEach(b=>b.onclick=()=>{comparePeriod=b.dataset.period||'1y';loadComparison()})}
  async function refreshPulse(){const mine=++pulseSeq;try{const d=await dashboardPhase('deferred');if(mine!==pulseSeq)return;const e=d.sections?.events||{},c=d.sections?.calendar||{};currentEvents=e.items||currentEvents;currentCalendar=c.items||currentCalendar;renderPulse();updatePulseCards(e,c);const stamp=document.getElementById('nsPulseUpdated');if(stamp)stamp.textContent='Oppdatert '+new Date().toLocaleTimeString('no-NO',{hour:'2-digit',minute:'2-digit'})}catch(e){console.warn('portfolio pulse refresh failed',e)}}
  function startPulseTimer(){if(pulseTimer)clearInterval(pulseTimer);pulseTimer=setInterval(()=>{const active=document.querySelector('#nav a.active');if(!document.hidden&&(!active||active.dataset.page==='Dashboard'))refreshPulse()},120000)}
  async function loadDeferred(mine){try{const d=await dashboardPhase('deferred');if(mine!==homeSeq)return;const events=d.sections?.events||{},calendar=d.sections?.calendar||{};currentEvents=events.items||[];currentCalendar=calendar.items||[];renderPulse();updatePulseCards(events,calendar);const stamp=document.getElementById('nsPulseUpdated');if(stamp)stamp.textContent='Oppdatert '+new Date().toLocaleTimeString('no-NO',{hour:'2-digit',minute:'2-digit'});startPulseTimer()}catch(e){const body=document.getElementById('nsPulseBody');if(body)body.innerHTML='<div class="nsEmptyHome"><b>Hendelser lastes ikke akkurat nå</b>Beholdningen og resten av forsiden er fortsatt tilgjengelig.</div>'}}
  async function renderPortfolioHome(){styles();if(typeof setTitle==='function')setTitle('Min oversikt','Beholdning først · marked og hendelser etterlastes');const view=document.getElementById('appview');if(!view)return;const mine=++homeSeq;view.innerHTML='<div class="nsHomeWrap"><div class="nsHomeSkeleton">Laster beholdningen først…</div></div>';try{const d=await dashboardPhase('core');if(mine!==homeSeq)return;const holdings=d.sections?.holdings||{},summary=holdings.summary||{},items=holdings.items||[],pnl=summary.unrealized_pnl,pnlCls=pnl==null?'':Number(pnl)>=0?'nsPos':'nsNeg';view.innerHTML=`<div class="nsHomeWrap"><section class="nsHomeCards"><div class="nsHomeCard"><div class="k">Porteføljeverdi</div><div class="v">${nok(summary.market_value)}</div><div class="m">${esc(summary.position_count||0)} posisjoner</div></div><div class="nsHomeCard"><div class="k">Urealisert resultat</div><div class="v ${pnlCls}">${nok(pnl)}</div><div class="m ${pnlCls}">${pct(summary.unrealized_pnl_pct)}</div></div><div class="nsHomeCard"><div class="k">Viktig nå</div><div id="nsImportantValue" class="v">…</div><div class="m">etterlastes uten å blokkere</div></div><div class="nsHomeCard"><div class="k">Neste hendelse</div><div id="nsNextEventValue" class="v">…</div><div id="nsNextEventMeta" class="m">kalender lastes</div></div></section><div class="nsHomeGrid"><section class="nsHomePanel"><div class="nsHomeHead"><div><h2>Min beholdning</h2><p>Største posisjoner først</p></div><a class="nsHomeLink" href="/holdings">Administrer beholdning</a></div>${holdingRows(items)}</section><section class="nsHomePanel"><div class="nsHomeHead"><div><h2>For min beholdning</h2><p>Nyheter og kommende hendelser</p></div><span class="nsBriefMark">NORDICSIGNAL BRIEF</span></div><div class="nsPulseTabs"><button class="nsPulseTab active" data-mode="news">Siste nytt</button><button class="nsPulseTab" data-mode="upcoming">Kommende</button></div><div id="nsPulseBody"><div class="nsEmptyHome">Henter viktige hendelser i bakgrunnen…</div></div><div class="nsPulseFoot"><span id="nsPulseUpdated">Laster…</span><a href="/calendar">Åpne kalender →</a></div></section></div>${comparePanel()}<div class="nsFastHint">Forsiden bruker progressiv lasting: beholdning først, deretter hendelser og marked.</div></div>`;bindHome();setTimeout(()=>loadDeferred(mine),0);if('requestIdleCallback'in window)requestIdleCallback(()=>loadComparison(),{timeout:900});else setTimeout(()=>loadComparison(),120)}catch(e){console.error(e);view.innerHTML='<div class="nsHomeWrap"><div class="nsHomeSkeleton">Min oversikt kunne ikke lastes akkurat nå. De andre NordicSignal-sidene fungerer fortsatt.</div></div>'}}
  function install(){styles();const dashboardLink=document.querySelector('#nav a[data-page="Dashboard"]');if(dashboardLink)dashboardLink.textContent='Min oversikt';window.renderDashboard=renderPortfolioHome;const active=document.querySelector('#nav a.active');if(!active||active.dataset.page==='Dashboard')renderPortfolioHome()}
  install();
})();
