(function(){
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  let timer=null,seq=0,last=[];
  function symbolOf(x){return String(x?.symbol||x?.market_symbol||x?.ticker||'').trim()}
  function assetOf(x){return String(x?.asset_class||x?.type||x?.quote_type||'').toLowerCase()}
  function isOsloEquity(x){const s=symbolOf(x).toUpperCase(),a=assetOf(x),ex=String(x?.exchange||'').toUpperCase();if(a.includes('fond')||a.includes('fund')||a.includes('etf'))return false;return s.endsWith('.OL')||ex.includes('OSLO')||ex==='OSL'||ex==='XOSL'}
  function openInstrument(x){const s=symbolOf(x);if(!s)return;if(isOsloEquity(x)){location.href='/stock?ticker='+encodeURIComponent(s.toUpperCase().replace(/\.OL$/,''));return}const p=new URLSearchParams({symbol:s});if(x.name||x.longname)p.set('name',x.name||x.longname);if(x.asset_class)p.set('type',x.asset_class);if(x.exchange)p.set('exchange',x.exchange);if(x.currency)p.set('currency',x.currency);location.href='/instrument?'+p.toString()}
  function styles(){if(document.getElementById('nsStockSelectorStyles'))return;const s=document.createElement('style');s.id='nsStockSelectorStyles';s.textContent=`.nsIntelSwitch{margin:10px 0 18px;display:flex;justify-content:flex-end}.nsIntelSearch{position:relative;width:min(420px,100%)}.nsIntelSearch input{width:100%;background:#090909;border:1px solid #303030;color:#fff;border-radius:9px;padding:10px 12px;font:650 12px system-ui;outline:none}.nsIntelSearch input:focus{border-color:#555}.nsIntelResults{display:none;position:absolute;z-index:80;left:0;right:0;top:100%;margin-top:5px;background:#0a0a0a;border:1px solid #343434;border-radius:10px;max-height:330px;overflow:auto;box-shadow:0 18px 45px #000c}.nsIntelResults.open{display:block}.nsIntelResult{display:block;width:100%;border:0;border-bottom:1px solid #222;background:transparent;color:#eee;text-align:left;padding:10px 11px;cursor:pointer}.nsIntelResult:hover{background:#151515}.nsIntelResult b{display:block}.nsIntelResult span{display:block;color:#777;font-size:9px;margin-top:3px}`;document.head.appendChild(s)}
  async function search(text){const q=text.trim(),mine=++seq,box=document.getElementById('nsIntelResults');if(!box)return;if(q.length<2){last=[];box.className='nsIntelResults';return}box.className='nsIntelResults open';box.innerHTML='<div class="nsIntelResult"><span>Søker…</span></div>';try{const r=await fetch('/api/search?q='+encodeURIComponent(q)+'&limit=10',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(mine!==seq)return;last=(d.items||[]).slice(0,8);box.innerHTML=last.length?last.map((x,i)=>`<button class="nsIntelResult" data-i="${i}"><b>${esc(x.name||x.longname||symbolOf(x))}</b><span>${esc(symbolOf(x))}${x.asset_class?' · '+esc(x.asset_class):''}${x.exchange?' · '+esc(x.exchange):''}</span></button>`).join(''):'<div class="nsIntelResult"><span>Ingen treff.</span></div>';box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>openInstrument(last[Number(b.dataset.i)]))}catch(e){box.innerHTML='<div class="nsIntelResult"><span>Søk midlertidig utilgjengelig.</span></div>'}}
  function install(){styles();const main=document.querySelector('main.wrap');if(!main||document.getElementById('nsIntelSwitch'))return;const host=document.createElement('div');host.id='nsIntelSwitch';host.className='nsIntelSwitch';host.innerHTML='<div class="nsIntelSearch"><input id="nsIntelInput" autocomplete="off" placeholder="Bytt aksje, fond eller ETF…"><div id="nsIntelResults" class="nsIntelResults"></div></div>';const top=main.querySelector('.top');if(top)top.insertAdjacentElement('beforebegin',host);else main.prepend(host);const input=document.getElementById('nsIntelInput');input.addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>search(e.target.value),200)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&last[0]){e.preventDefault();openInstrument(last[0])}});document.addEventListener('click',e=>{if(!e.target.closest('.nsIntelSearch'))document.getElementById('nsIntelResults').className='nsIntelResults'})}
  install();
})();