(function(){
  const ticker=(new URLSearchParams(location.search).get('ticker')||'').toUpperCase().replace(/\.OL$/,'');
  if(!ticker)return;
  const esc=v=>String(v==null?'—':v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  let payload=null,loading=false;

  function styles(){if(document.getElementById('nsReadinessTabStyles'))return;const s=document.createElement('style');s.id='nsReadinessTabStyles';s.textContent=`
    .nsReadyHero{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;flex-wrap:wrap}.nsReadyScore{font-size:34px;font-weight:850}.nsReadyStatus{font-weight:800;margin-top:3px}.nsReadyStatus.positive,.nsReadyScore.positive{color:#35d49a}.nsReadyStatus.risk,.nsReadyScore.risk{color:#fb7185}.nsReadyStatus.watch,.nsReadyScore.watch{color:#e7c16b}.nsReadyGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.nsReadyFactor{padding:9px 0;border-top:1px solid var(--line)}.nsReadyFactor:first-child{border-top:0}.nsReadyBrief{line-height:1.55;color:#c7c7c7}.nsReadySources{color:var(--m);font-size:10px;line-height:1.5;margin-top:12px}@media(max-width:760px){.nsReadyGrid{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}
  function tone(d){return d.tone==='positive'?'positive':d.tone==='risk'?'risk':'watch'}
  function factors(items,kind){return (items||[]).length?(items||[]).slice(0,5).map(x=>`<div class="nsReadyFactor ${kind==='positive'?'positive':'negative'}">${kind==='positive'?'＋':'−'} ${esc(x)}</div>`).join(''):'<div class="muted">Ingen tydelige faktorer registrert.</div>'}
  function markup(d){return `<section class="card"><div class="nsReadyHero"><div><h2>Investment Readiness · ${esc(ticker)}</h2><div class="nsReadyBrief">${esc(d.brief)}</div></div><div><div class="nsReadyScore ${tone(d)}">${esc(d.readiness_score)}/100</div><div class="nsReadyStatus ${tone(d)}">${esc(d.readiness_label)}</div><div class="muted">Datadekning ${esc(d.coverage_pct)}%</div></div></div><div class="notice" style="margin-top:14px">Analyse-statusen kombinerer uavhengige datapunkter og er ikke en personlig kjøps-, salgs- eller holdeanbefaling.</div><div class="nsReadyGrid"><div><h3>Det som trekker opp</h3>${factors(d.positive_factors,'positive')}</div><div><h3>Risiko / det som trekker ned</h3>${factors(d.risk_factors,'risk')}</div></div><div class="nsReadySources">Kilder: ${(d.sources||[]).map(esc).join(' · ')||'—'} · <a href="/legal">Vilkår og risiko</a> · <a href="/readiness?symbol=${encodeURIComponent(ticker)}">Åpne full Investment Check</a></div></section>`}
  async function fetchReadiness(){if(payload||loading)return;loading=true;try{const r=await fetch('/api/readiness/'+encodeURIComponent(ticker),{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||('HTTP '+r.status));payload=d}catch(e){payload={error:String(e.message||e)}}finally{loading=false}}
  async function renderReadiness(){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab==='readiness'));const c=document.getElementById('content');if(!c)return;c.innerHTML='<section class="card"><div class="notice">Analyserer risiko, trend og siste nytt…</div></section>';await fetchReadiness();c.innerHTML=payload&&!payload.error?markup(payload):`<section class="card"><div class="notice">Investment Readiness er midlertidig utilgjengelig${payload?.error?' · '+esc(payload.error):''}.</div></section>`}
  function install(){styles();const tabs=document.querySelector('.tabs');if(!tabs)return;if(!tabs.querySelector('[data-tab="readiness"]')){const b=document.createElement('button');b.className='tab';b.dataset.tab='readiness';b.textContent='Investment Check';b.onclick=renderReadiness;tabs.appendChild(b)}if((new URLSearchParams(location.search).get('tab')||'').toLowerCase()==='readiness'){let tries=0;const t=setInterval(()=>{tries++;const b=tabs.querySelector('[data-tab="readiness"]'),c=document.getElementById('content');if(b&&c){b.click();clearInterval(t)}else if(tries>60)clearInterval(t)},120)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
