/* Presentation only. All production model decisions come from their existing API. */
function compactAmount(value){if(value==null||value===''||!Number.isFinite(Number(value)))return '—';const n=Number(value),a=Math.abs(n);for(const [size,label] of [[1e12,'bill.'],[1e9,'mrd.'],[1e6,'mill.']])if(a>=size)return (n/size).toLocaleString('nb-NO',{maximumFractionDigits:2})+' '+label;return num(n)}
function trendLabel(value){return ({CONFIRMED_UPTREND:'Bekreftet opptrend',EARLY_REVERSAL:'Tidlig trendvending',REVERSAL_CANDIDATE:'Mulig trendvending',BOTTOMING:'Mulig bunndannelse',FALLING_OR_WEAK:'Fallende eller svak',INSUFFICIENT_DATA:'For lite data'})[value]||'Ukjent'}
function renderTechnical(d){const r=d.reversal||{},m=r.metrics||{};document.getElementById('technicalSection').innerHTML='<h2>Momentum · volum · relativ styrke</h2><div class="metrics">'+[['Trend',trendLabel(r.regime)],['RSI 14',num(m.rsi14)],['Volum / normal',num(m.raw_volume_ratio)],['Bullish volum',num(m.volume_ratio)],['Relativ styrke','Mangler data']].map(([k,v])=>'<div class="metric"><span class="muted">'+esc(k)+'</span><b>'+esc(v)+'</b></div>').join('')+'</div><p class="muted">Observasjon '+esc(m.close_date||'ukjent')+'. Relativ styrke krever sammenlignbare benchmark-data; vanlig aksjeavkastning vises ikke som excess. Kursendringer er ikke bekreftet totalavkastning. Utbytte, splitt og andre selskapshendelser kan påvirke kurs og trend.</p>'}
async function loadAnalysis(){
 window.AksjerCompany.mount($('companyContextSection'),ticker,{financialRoot:$('fundamentalSection'),summaryRoot:$('companySummary'),reportsRoot:$('reviewedReports')});
 const chart=async()=>{const d=await get('/api/history/'+encodeURIComponent(ticker)+'?period=1y'),rows=(d.items||[]).filter(x=>x.close!=null&&Number.isFinite(Number(x.close)));if(!rows.length)throw Error('history unavailable');const values=rows.map(x=>Number(x.close)),min=Math.min(...values),span=Math.max(...values)-min||1,points=values.map((v,i)=>(20+i*960/Math.max(1,values.length-1))+','+(230-(v-min)*210/span)).join(' ');$('chartSection').innerHTML='<h2>Kurs og trend · 1 år</h2><svg role="img" aria-label="Historisk sluttkurs for '+esc(ticker)+'" viewBox="0 0 1000 250" style="width:100%;max-height:280px"><polyline points="'+points+'" fill="none" stroke="var(--b)" stroke-width="3"/></svg><p class="muted">'+esc(String(rows[0].date||'').slice(0,10))+' – '+esc(String(rows.at(-1).date||'').slice(0,10))+' · historiske sluttkurser · Yahoo Finance</p>'};
 const capital=async()=>{const d=await get('/api/capital-flow?ticker='+encodeURIComponent(ticker)+'&limit=10');const rows=(d.items||[]).filter(x=>String(x.ticker||'').toUpperCase()===ticker);$('capitalSection').innerHTML='<h2>Capital Flow · forskning</h2><p class="muted">Offentlige hendelser med tickerkobling. Ingen score-effekt.</p>'+news(rows)};
 const ipo=async()=>window.AksjerIPO.mount($('ipoSection'),ticker);
 const calendar=async()=>{const d=await get('/api/calendar?days=90&limit=120');data.nextCatalyst=(d.items||[]).filter(x=>x.ticker===ticker&&x.official&&x.url&&x.date>=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Oslo'})).sort((a,b)=>a.date.localeCompare(b.date))[0]||null;renderDecisionPanels(data.opportunity)};calendar().catch(()=>{data.nextCatalyst=null;renderDecisionPanels(data.opportunity)});
 for(const [run,id,label] of [[chart,'chartSection','Kurshistorikk'],[capital,'capitalSection','Capital Flow'],[ipo,'ipoSection','IPO / New']])run().catch(()=>{$(id).innerHTML='<h2>'+label+'</h2><div class="notice">UTILGJENGELIG · prøv igjen senere.</div>'});
}
