/* Presentation only. All production model decisions come from their existing API. */
function compactAmount(value){if(value==null||value===''||!Number.isFinite(Number(value)))return '—';const n=Number(value),a=Math.abs(n);for(const [size,label] of [[1e12,'bill.'],[1e9,'mrd.'],[1e6,'mill.']])if(a>=size)return (n/size).toLocaleString('nb-NO',{maximumFractionDigits:2})+' '+label;return num(n)}
function renderTechnical(d){const r=d.reversal||{},m=r.metrics||{};document.getElementById('technicalSection').innerHTML='<h2>Momentum · volum · relativ styrke</h2><div class="metrics">'+[['Trend',r.regime||'Ukjent'],['RSI 14',num(m.rsi14)],['Volum / normal',num(m.raw_volume_ratio)],['Bullish volum',num(m.volume_ratio)],['Relativ styrke','UTILGJENGELIG']].map(([k,v])=>'<div class="metric"><span class="muted">'+esc(k)+'</span><b>'+esc(v)+'</b></div>').join('')+'</div><p class="muted">Observasjon '+esc(m.close_date||'ukjent')+'. Relativ styrke krever sammenlignbare benchmark-data; vanlig aksjeavkastning vises ikke som excess.</p>'}
async function loadAnalysis(){
 const chart=async()=>{const d=await get('/api/history/'+encodeURIComponent(ticker)+'?period=1y'),rows=(d.items||[]).filter(x=>x.close!=null&&Number.isFinite(Number(x.close)));if(!rows.length)throw Error('history unavailable');const values=rows.map(x=>Number(x.close)),min=Math.min(...values),span=Math.max(...values)-min||1,points=values.map((v,i)=>(20+i*960/Math.max(1,values.length-1))+','+(230-(v-min)*210/span)).join(' ');$('chartSection').innerHTML='<h2>Kurs og trend · 1 år</h2><svg role="img" aria-label="Historisk sluttkurs for '+esc(ticker)+'" viewBox="0 0 1000 250" style="width:100%;max-height:280px"><polyline points="'+points+'" fill="none" stroke="var(--b)" stroke-width="3"/></svg><p class="muted">'+esc(String(rows[0].date||'').slice(0,10))+' – '+esc(String(rows.at(-1).date||'').slice(0,10))+' · historiske sluttkurser · Yahoo Finance</p>'};
 const fundamentals=async()=>{const d=await get('/api/research/'+encodeURIComponent(ticker)),r=d.data||{},f=r.fundamentals||{},sd=r.summaryDetail||{},ks=r.defaultKeyStatistics||{},raw=v=>r.valuation_currency_verified===true?(v&&typeof v==='object'?v.raw:v):null;const vals=[['Omsetning',f.revenue],['EBITDA',f.ebitda],['Nettoresultat',f.net_income],['Fri kontantstrøm',f.free_cashflow],['Gjeld',f.debt],['Egenkapital',f.equity],['P/E',raw(sd.trailingPE??ks.trailingPE)],['P/B',raw(ks.priceToBook)],['EV/EBITDA',raw(ks.enterpriseToEbitda)]];$('fundamentalSection').innerHTML='<h2>Fundamentals og verdsettelse</h2><div class="metrics">'+vals.map(([label,v],i)=>'<div class="metric"><span class="muted">'+label+'</span><b title="'+esc(num(v))+'">'+esc(i<6?compactAmount(v):num(v))+'</b></div>').join('')+'</div><p class="muted">Kilde: '+esc(d.source||'ukjent')+' · rapporteringsperiode '+esc(r.period||r.as_of||'ikke oppgitt i feed')+'. Absolutte tall i rapporteringsvaluta, ikke nødvendigvis NOK. P/E, P/B og EV/EBITDA vises bare når samsvar mellom kurs- og regnskapsvaluta er verifisert.</p>'};
 const capital=async()=>{const d=await get('/api/capital-flow?ticker='+encodeURIComponent(ticker)+'&limit=10');const rows=(d.items||[]).filter(x=>String(x.ticker||'').toUpperCase()===ticker);$('capitalSection').innerHTML='<h2>Capital Flow · forskning</h2><p class="muted">Offentlige hendelser med tickerkobling. Ingen score-effekt.</p>'+news(rows)};
 const ipo=async()=>window.AksjerIPO.mount($('ipoSection'),ticker);
 const calendar=async()=>{const d=await get('/api/calendar?days=90&limit=120');data.nextCatalyst=(d.items||[]).filter(x=>x.ticker===ticker&&x.official&&x.url&&x.date>=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Oslo'})).sort((a,b)=>a.date.localeCompare(b.date))[0]||null;renderDecisionPanels(data.opportunity)};calendar().catch(()=>{data.nextCatalyst=null;renderDecisionPanels(data.opportunity)});
 for(const [run,id,label] of [[chart,'chartSection','Kurshistorikk'],[fundamentals,'fundamentalSection','Fundamentals og verdsettelse'],[capital,'capitalSection','Capital Flow'],[ipo,'ipoSection','IPO / New']])run().catch(()=>{$(id).innerHTML='<h2>'+label+'</h2><div class="notice">UTILGJENGELIG · prøv igjen senere.</div>'});
}
