(function(){
  const path=location.pathname;
  const MORE_ROUTES=['/capital-flow','/alerts','/ipo-radar','/learning','/calendar','/readiness','/legal'];
  function addStyles(){if(document.getElementById('nsUiShellStyles'))return;const s=document.createElement('style');s.id='nsUiShellStyles';s.textContent=`:root{--ns-blue:#19a7ff;--ns-cyan:#20e6ff;--ns-violet:#9b45ff;--ns-green:#2de6a7;--ns-amber:#ffb84a;--ns-red:#ff4e64}.nsOpportunityMetric,.nsOpportunityReason,.nsEvidenceMetric{background:var(--surface-2,#151515)!important;border-color:var(--line,#292929)!important}.nsReadyBrief{color:var(--t,#f5f5f5)!important}.nsOppWatch,.nsEvidenceWarn{color:var(--y,#e6b94b)!important}.side .logo{font-size:0!important;display:flex!important;align-items:center!important}.side .logo:before{content:"";width:34px;height:34px;margin-right:10px;background:linear-gradient(135deg,#29c8ff,#1679ff);clip-path:polygon(0 100%,28% 0,48% 0,62% 38%,78% 0,100% 100%,76% 100%,61% 55%,47% 100%,27% 100%,38% 62%,28% 34%,20% 100%);filter:drop-shadow(0 0 10px #168fff66)}.side .logo:after{content:"NORDICSIGNAL";font-size:16px;letter-spacing:.08em;color:#eef7ff}.nsMoreToggle.active,.nsMoreMenu a.active{color:var(--t,#f5f5f5)!important;border-color:color-mix(in srgb,var(--a,#19a7ff) 48%,transparent)!important;background:color-mix(in srgb,var(--a,#19a7ff) 10%,var(--surface-2,#151515))!important}html[data-theme="light"] .card,html[data-theme="light"] .section,html[data-theme="light"] .metric,html[data-theme="light"] .notice,html[data-theme="light"] .pressureAlert{background:linear-gradient(180deg,rgba(255,255,255,.82),rgba(247,250,255,.94))!important}html[data-theme="light"] .side{background:linear-gradient(180deg,rgba(255,255,255,.96),rgba(241,246,255,.96))!important}html[data-theme="light"] .search,html[data-theme="light"] .input,html[data-theme="light"] .wideinput,html[data-theme="light"] .form input,html[data-theme="light"] .form select{background:rgba(255,255,255,.9)!important}html[data-theme="light"] .btn,html[data-theme="light"] .tab,html[data-theme="light"] .nsThemeToggle,html[data-theme="light"] .nsMoreToggle{background:linear-gradient(180deg,#fff,#edf3ff)!important;color:var(--t)!important}html[data-theme="light"] .btn.active,html[data-theme="light"] .tab.active,html[data-theme="light"] .btn.primary{background:linear-gradient(110deg,#176dcc,#6745d8)!important;color:#fff!important}html[data-theme="light"] .top h1,html[data-theme="light"] .top h2{background:none!important;color:var(--t)!important;-webkit-text-fill-color:var(--t)!important}html[data-theme="light"] .side .logo:after{color:#10213c}@media(max-width:900px){.nsAlertShortcut{bottom:96px!important}.top{align-items:center!important}.top>.nsThemeToggle{display:inline-grid!important;place-items:center!important}}`;document.head.appendChild(s)}
  function themeButton(slot){return `<button class="nsThemeToggle" data-ns-theme-toggle data-slot="${slot}" type="button" aria-label="Bytt tema">☀︎</button>`}
  function installGlobalNav(){const side=document.querySelector('.side');const nav=side&&side.querySelector('nav');if(!side||!nav||nav.dataset.nsSimplified==='1')return;nav.dataset.nsSimplified='1';nav.innerHTML=`<a href="/app" data-ns-nav="home">Hjem</a><a href="/morning" data-ns-nav="morning">Før børs</a><a href="/app?view=signals" data-ns-nav="signals">Signaler</a><a href="/holdings" data-ns-nav="portfolio">Portefølje</a><a href="/stock" data-ns-nav="search">Søk</a><button class="nsMoreToggle" type="button" aria-expanded="false">Mer</button><div class="nsMoreMenu" hidden><a href="/capital-flow">Kapitalflyt</a><a href="/alerts">Varsler</a><a href="/ipo-radar">IPO Radar</a><a href="/learning">Historikk</a><a href="/calendar">Kalender</a><a href="/readiness">Sjekkliste</a><a href="/legal">Vilkår & risiko</a></div>`;if(!side.querySelector('.nsSideFooter'))side.insertAdjacentHTML('beforeend',`<div class="nsSideFooter"><span>NordicSignal</span>${themeButton('side')}</div>`);const more=nav.querySelector('.nsMoreToggle'),menu=nav.querySelector('.nsMoreMenu');more&&more.addEventListener('click',()=>{const open=more.getAttribute('aria-expanded')==='true';more.setAttribute('aria-expanded',String(!open));menu.hidden=open});const moreRoute=MORE_ROUTES.find(route=>path.startsWith(route))||'';if(moreRoute){more?.classList.add('active');const secondary=menu?.querySelector(`a[href="${moreRoute}"]`);if(secondary){secondary.classList.add('active');secondary.setAttribute('aria-current','page')}}const active=moreRoute?'':path.startsWith('/morning')?'morning':path.startsWith('/holdings')?'portfolio':path.startsWith('/stock')||path.startsWith('/intelligence')||path.startsWith('/instrument')?'search':location.search.includes('view=signals')?'signals':'home';if(active)nav.querySelector(`[data-ns-nav="${active}"]`)?.classList.add('active')}
  function installTopTheme(){if(document.querySelector('[data-slot="top"]'))return;const top=document.querySelector('.top');if(top)top.insertAdjacentHTML('beforeend',themeButton('top'));else document.body.insertAdjacentHTML('afterbegin',`<div class="nsFloatingTheme">${themeButton('top')}</div>`)}
  function activateSignalsView(){if(path!=='/app'&&path!=='/'&&path!=='/dashboard')return;if(new URLSearchParams(location.search).get('view')!=='signals')return;let tries=0;const run=()=>{if(typeof window.renderRadar==='function'){window.renderRadar();return true}if(tries++<20)setTimeout(run,100);return false};run();setTimeout(()=>{if(typeof window.renderRadar==='function')window.renderRadar()},900)}
  const REMOVED_STOCK_TOOLS=new Set(['backtest','paper']);
  const TOOL_ORDER=['overview','opportunity','readiness','events','pressure','insider','news','reports','dividend','short','evidence'];
  const TOOL_LABELS={overview:'Oversikt',opportunity:'Signal',readiness:'Analyse',events:'Hendelser',pressure:'Marked',insider:'Insider',news:'Nyheter',reports:'Rapporter',dividend:'Utbytte',short:'Short',evidence:'Historikk'};
  function organizeStockTools(){if(!path.startsWith('/stock'))return;const tabs=document.querySelector('.tabs');if(!tabs)return;tabs.querySelectorAll('[data-tab]').forEach(btn=>{if(REMOVED_STOCK_TOOLS.has(btn.dataset.tab))btn.remove()});tabs.classList.add('nsToolRail');if(!document.querySelector('.nsToolHeader'))tabs.insertAdjacentHTML('beforebegin','<div class="nsToolHeader"><div><span class="muted">VERKTØY</span><h2>Analyser valgt aksje</h2></div><span class="muted">Velg verktøy uten å forlate aksjen</span></div>');const current=[...tabs.querySelectorAll('[data-tab]')];current.forEach(btn=>{const key=btn.dataset.tab;if(TOOL_LABELS[key]&&btn.textContent!==TOOL_LABELS[key])btn.textContent=TOOL_LABELS[key]});const rank=btn=>{const i=TOOL_ORDER.indexOf(btn.dataset.tab);return i===-1?TOOL_ORDER.length:i};const desired=[...current].sort((a,b)=>rank(a)-rank(b));const needsReorder=desired.some((btn,index)=>btn!==current[index]);if(needsReorder){const fragment=document.createDocumentFragment();desired.forEach(btn=>fragment.appendChild(btn));tabs.appendChild(fragment)}const title=document.querySelector('.top .muted');if(title)title.textContent='NORDICSIGNAL · AKSJE';const name=document.getElementById('name')?.textContent;if(name&&name!=='Loading…')document.title=name+' · NordicSignal'}
  function stockObserver(){if(!path.startsWith('/stock'))return;organizeStockTools();const tabs=document.querySelector('.tabs');if(!tabs)return;new MutationObserver(()=>organizeStockTools()).observe(tabs,{childList:true,subtree:false})}
  function renamePlainLanguage(){const map={'Market Dashboard':'Oversikt','Live signal-driven stock intelligence':'Det viktigste først. Åpne en aksje for alle verktøy.','Stock Radar':'Signaler','Watchlist':'Følger','Insider Activity':'Insider','Short Radar':'Short','Stock Intelligence':'Aksjeanalyse','Signal Performance':'Historikk','Investment Check':'Sjekkliste'};document.querySelectorAll('h1,h2,.sub,.label').forEach(el=>{const text=el.textContent.trim();if(map[text])el.textContent=map[text]})}
  function install(){addStyles();installGlobalNav();installTopTheme();activateSignalsView();stockObserver();renamePlainLanguage()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(organizeStockTools,250);setTimeout(organizeStockTools,900);setTimeout(renamePlainLanguage,350)
})();