"""Persistent history for successfully delivered NordicSignal Web Push alerts.

The history hooks the central push sender, so one canonical record is created only
after at least one Web Push delivery succeeds. Multiple subscribed devices increment
delivery_count without duplicating the alert. History is presentation-only and has
no effect on scoring, signals, Opportunity thresholds, or push eligibility.
"""
from __future__ import annotations

from datetime import datetime, timezone, timedelta
import json
import re
from urllib.parse import urlparse, parse_qs

import extra_api
from database import connect, USING_POSTGRES
import push_runtime as push

RETENTION_DAYS = 90
MAX_LIST_LIMIT = 250


def _now():
    return datetime.now(timezone.utc).isoformat()


def _ensure_schema():
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn = connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS alert_history (
          id {identity},
          event_key TEXT NOT NULL UNIQUE,
          alert_type TEXT NOT NULL,
          ticker TEXT,
          company_name TEXT,
          title TEXT NOT NULL,
          body TEXT NOT NULL,
          url TEXT,
          source_created_at TEXT NOT NULL,
          first_sent_at TEXT NOT NULL,
          last_sent_at TEXT NOT NULL,
          delivery_count INTEGER NOT NULL DEFAULT 1,
          read_at TEXT,
          payload_json TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_alert_history_created ON alert_history(source_created_at);
        CREATE INDEX IF NOT EXISTS idx_alert_history_type ON alert_history(alert_type);
        """)
        conn.commit()
    finally:
        conn.close()


def _safe_url(value):
    text = str(value or "").strip()
    if not text.startswith("/") or text.startswith("//"):
        return "/alerts"
    return text[:1000]


def _ticker_from_payload(payload):
    direct = str((payload or {}).get("ticker") or "").strip().upper().replace(".OL", "")
    if direct:
        return direct[:20]
    try:
        parsed = urlparse(str((payload or {}).get("url") or ""))
        query = parse_qs(parsed.query)
        ticker = str((query.get("ticker") or query.get("symbol") or [""])[0]).strip().upper().replace(".OL", "")
        if ticker:
            return ticker[:20]
    except Exception:
        pass
    title = str((payload or {}).get("title") or "").strip()
    first = re.split(r"\s*[·|–—:-]\s*", title, maxsplit=1)[0].strip().upper()
    if re.fullmatch(r"[A-ZÆØÅ0-9.-]{2,12}", first or ""):
        return first.replace(".OL", "")
    return None


def _classify(payload):
    tag = str((payload or {}).get("tag") or "").lower()
    text = " ".join(str((payload or {}).get(k) or "") for k in ("title", "body")).lower()
    if tag.startswith("opportunity:") or "early opportunity" in text or "opportunity watch" in text:
        return "OPPORTUNITY"
    insider_terms = (
        "primary insider", "primærinsider", "primaerinsider", "insiderkjøp", "innsidersalg",
        "insider transaction", "managers' transaction", "manager's transaction", "meldepliktig handel",
        " kjøp ·", " salg ·",
    )
    if tag.startswith("insider:") or any(term in text for term in insider_terms):
        return "INSIDER"
    if tag.startswith("trend:"):
        if "høy aktivitet" in text or "volum" in text or "handelsaktivitet" in text:
            return "ACTIVITY"
        return "TREND"
    if tag.startswith("score:") or "signalendring" in text:
        return "SIGNAL"
    if tag.startswith("short:") or "short" in text:
        return "SHORT"
    return "OTHER"


def _event_key(payload):
    tag = str((payload or {}).get("tag") or "").strip()
    if tag:
        return tag[:300]
    canonical = json.dumps({
        "title": str((payload or {}).get("title") or ""),
        "body": str((payload or {}).get("body") or ""),
        "url": str((payload or {}).get("url") or ""),
        "timestamp": str((payload or {}).get("timestamp") or ""),
    }, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    import hashlib
    return "payload:" + hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:32]


def _is_test_payload(payload):
    tag = str((payload or {}).get("tag") or "").lower()
    title = str((payload or {}).get("title") or "").lower()
    return tag.startswith("test") or tag.startswith("push-test") or "push-varsler fungerer" in str((payload or {}).get("body") or "").lower() or title == "nordicsignal test"


def _record_successful_payload(payload):
    if not isinstance(payload, dict) or _is_test_payload(payload):
        return False
    title = str(payload.get("title") or "").strip()
    body = str(payload.get("body") or "").strip()
    if not title and not body:
        return False
    event_key = _event_key(payload)
    now = _now()
    source_created = str(payload.get("timestamp") or payload.get("created_at") or now)
    ticker = _ticker_from_payload(payload)
    company = str(payload.get("company_name") or payload.get("company") or "").strip() or None
    alert_type = _classify(payload)
    url = _safe_url(payload.get("url"))
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"), default=str)
    cutoff = (datetime.now(timezone.utc) - timedelta(days=RETENTION_DAYS)).isoformat()

    conn = connect()
    try:
        # A single UPSERT keeps one canonical row per event while making the
        # delivery counter safe across concurrent workers/processes. The prior
        # SELECT-then-INSERT sequence could lose a device increment if two
        # successful deliveries for the same event raced on the unique key.
        conn.execute(
            "INSERT INTO alert_history(event_key,alert_type,ticker,company_name,title,body,url,source_created_at,first_sent_at,last_sent_at,delivery_count,read_at,payload_json) "
            "VALUES(?,?,?,?,?,?,?,?,?,?,1,NULL,?) "
            "ON CONFLICT(event_key) DO UPDATE SET "
            "last_sent_at=excluded.last_sent_at,delivery_count=alert_history.delivery_count+1",
            (event_key, alert_type, ticker, company, title or "NordicSignal", body, url, source_created, now, now, encoded),
        )
        conn.execute("DELETE FROM alert_history WHERE source_created_at<?", (cutoff,))
        conn.commit()
        return True
    finally:
        conn.close()


def list_alerts(limit=100, alert_type=None, unread_only=False):
    limit = max(1, min(int(limit or 100), MAX_LIST_LIMIT))
    kind = str(alert_type or "").strip().upper()
    clauses = []
    params = []
    if kind and kind not in {"ALL", "ALLE"}:
        clauses.append("alert_type=?")
        params.append(kind)
    if unread_only:
        clauses.append("read_at IS NULL")
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    conn = connect()
    try:
        rows = conn.execute(
            "SELECT id,event_key,alert_type,ticker,company_name,title,body,url,source_created_at,first_sent_at,last_sent_at,delivery_count,read_at "
            f"FROM alert_history{where} ORDER BY source_created_at DESC,id DESC LIMIT ?",
            tuple(params + [limit]),
        ).fetchall()
        unread_row = conn.execute("SELECT COUNT(*) AS n FROM alert_history WHERE read_at IS NULL").fetchone()
        total_row = conn.execute("SELECT COUNT(*) AS n FROM alert_history").fetchone()
        return {
            "status": "ok",
            "items": [dict(row) for row in rows],
            "unread": int(unread_row["n"] if unread_row else 0),
            "total": int(total_row["n"] if total_row else 0),
            "retention_days": RETENTION_DAYS,
            "generated_at": _now(),
        }
    finally:
        conn.close()


def mark_read(alert_id):
    now = _now()
    conn = connect()
    try:
        conn.execute("UPDATE alert_history SET read_at=COALESCE(read_at,?) WHERE id=?", (now, int(alert_id)))
        conn.commit()
        row = conn.execute("SELECT id,read_at FROM alert_history WHERE id=?", (int(alert_id),)).fetchone()
        return {"status": "ok", "id": int(alert_id), "read_at": row["read_at"] if row else None}
    finally:
        conn.close()


def mark_all_read():
    now = _now()
    conn = connect()
    try:
        cur = conn.execute("UPDATE alert_history SET read_at=? WHERE read_at IS NULL", (now,))
        conn.commit()
        return {"status": "ok", "marked": max(0, int(getattr(cur, "rowcount", 0) or 0)), "read_at": now}
    finally:
        conn.close()


def install():
    if getattr(extra_api, "_alert_history_runtime", False):
        return

    _ensure_schema()
    original_send = push._send

    def send_with_history(subscription, payload):
        ok, status = original_send(subscription, payload)
        if ok:
            try:
                _record_successful_payload(payload)
            except Exception:
                # History must never break actual push delivery.
                pass
        return ok, status

    push._send = send_with_history

    original_install = extra_api.install
    def patched_install(app):
        original_install(app)

        @app.get("/api/alerts")
        def alerts_list(limit: int = 100, type: str | None = None, unread_only: bool = False):
            return list_alerts(limit=limit, alert_type=type, unread_only=unread_only)

        @app.post("/api/alerts/read-all")
        def alerts_read_all():
            return mark_all_read()

        @app.post("/api/alerts/{alert_id}/read")
        def alerts_mark_read(alert_id: int):
            return mark_read(alert_id)

    extra_api.install = patched_install
    extra_api._alert_history_runtime = True


install()
