from datetime import datetime, timezone

from fastapi import HTTPException

from dividend_runtime import fetch_dividend_events


def _xirr(cashflows):
    if len(cashflows) < 2:
        return None
    first = cashflows[0][0]
    flows = [((dt - first).total_seconds() / 31557600.0, float(amount)) for dt, amount in cashflows]
    if not any(amount < 0 for _, amount in flows) or not any(amount > 0 for _, amount in flows):
        return None

    def npv(rate):
        base = 1.0 + rate
        if base <= 0:
            return float("inf")
        return sum(amount / (base ** years) for years, amount in flows)

    lo, hi = -0.9999, 10.0
    nlo, nhi = npv(lo), npv(hi)
    for _ in range(40):
        if nlo * nhi <= 0:
            break
        hi = hi * 2 + 1
        nhi = npv(hi)
    if nlo * nhi > 0:
        return None
    for _ in range(100):
        mid = (lo + hi) / 2
        nm = npv(mid)
        if abs(nm) < 1e-7:
            return mid
        if nlo * nm <= 0:
            hi, nhi = mid, nm
        else:
            lo, nlo = mid, nm
    return (lo + hi) / 2


def _corrected_backtest(provider, ticker, start, end, initial_cash, monthly_investment, reinvest_dividends):
    history = provider.historical(ticker, "max")
    start_ts = (
        int(datetime.fromisoformat(start).replace(tzinfo=timezone.utc).timestamp())
        if "T" not in start
        else int(datetime.fromisoformat(start.replace("Z", "+00:00")).timestamp())
    )
    end_ts = (
        int(datetime.fromisoformat(end).replace(tzinfo=timezone.utc).timestamp()) + 86399
        if "T" not in end
        else int(datetime.fromisoformat(end.replace("Z", "+00:00")).timestamp())
    )
    rows = [x for x in history if start_ts <= int(x["timestamp"]) <= end_ts]
    if not rows:
        raise HTTPException(404, detail="No historical data for selected period")

    # Dividend events are cash flows generated by the portfolio. They must not
    # silently disappear, and reinvested dividends must not be counted as new
    # external investment. The runtime helper also handles Yahoo's timestamp-
    # keyed event format and host/parameter fallbacks.
    divs = fetch_dividend_events(provider, ticker, start_ts, end_ts)
    div_by_day = {}
    for item in divs:
        day = item["date"]
        div_by_day[day] = div_by_day.get(day, 0.0) + float(item["amount"])

    cash = 0.0
    shares = 0.0
    invested = 0.0
    dividend_total = 0.0
    last_month = None
    points = []
    tx = []
    cashflows = []

    for row in rows:
        d = datetime.fromtimestamp(int(row["timestamp"]), timezone.utc).date()
        price = float(row["close"])

        if last_month != (d.year, d.month):
            if last_month is None:
                contribution = float(initial_cash)
            else:
                contribution = float(monthly_investment)

            if contribution > 0:
                cash += contribution
                bought = contribution / price if price > 0 else 0.0
                shares += bought
                cash -= bought * price
                invested += contribution
                tx.append({
                    "date": d.isoformat(),
                    "side": "buy",
                    "shares": bought,
                    "price": price,
                    "amount": contribution,
                })
                cashflows.append((datetime(d.year, d.month, d.day, tzinfo=timezone.utc), -contribution))
            last_month = (d.year, d.month)

        dividend_per_share = div_by_day.get(d.isoformat(), 0.0)
        if dividend_per_share > 0 and shares > 0:
            dividend = shares * dividend_per_share
            dividend_total += dividend
            if reinvest_dividends and price > 0:
                added = dividend / price
                shares += added
                tx.append({
                    "date": d.isoformat(),
                    "side": "dividend_reinvest",
                    "shares": added,
                    "price": price,
                    "amount": dividend,
                })
            else:
                cash += dividend
                tx.append({
                    "date": d.isoformat(),
                    "side": "dividend_cash",
                    "shares": shares,
                    "price": price,
                    "amount": dividend,
                })

        value = shares * price
        equity = cash + value
        points.append({
            "date": d.isoformat(),
            "price": price,
            "shares": shares,
            "cash": cash,
            "value": value,
            "equity": equity,
            "invested": invested,
        })

    end_equity = points[-1]["equity"]
    end_date = datetime.fromtimestamp(int(rows[-1]["timestamp"]), timezone.utc)
    cashflows.append((end_date, end_equity))
    total_return = end_equity - invested

    return {
        "ticker": ticker,
        "start": rows[0]["date"],
        "end": rows[-1]["date"],
        "initial_cash": initial_cash,
        "monthly_investment": monthly_investment,
        "reinvest_dividends": reinvest_dividends,
        "invested": invested,
        "final_equity": end_equity,
        "return": total_return,
        "return_pct": total_return / invested * 100 if invested else 0,
        "xirr": _xirr(cashflows),
        "shares": shares,
        "cash": cash,
        "dividends": dividend_total,
        "points": points,
        "transactions": tx[-100:],
    }


def install():
    # Patch the already-importable module before FastAPI registers its endpoint.
    import extra_api
    extra_api._backtest = _corrected_backtest
