"""Market-wide capital-flow and ownership radar.

This layer is deliberately separate from NordicSignal's score. It records point-in-
time ownership/capital-flow evidence, distinguishes fresh/active/historical events,
and makes new material events available to Web Push. Official exchange disclosures
and primary-insider records are treated as verified; media reports are labelled as
reported context and never silently promoted to verified holdings data.
"""
from __future__ import annotations

from datetime import datetime, timezone, timedelta
import hashlib
import json
import re
import threading
import time

import extra_api
from database import connect, USING_POSTGRES
import general_news_runtime

NEW_HOURS = 48
ACTIVE_DAYS = 30
RETENTION_DAYS = 730
SCAN_INTERVAL_SECONDS = 300
MAX_ITEMS = 500
_SCAN_LOCK = threading.Lock()
_SCAN_STARTED = False

BUY_WORDS = re.compile(r"\b(buy|buys|bought|purchase|purchased|acquire|acquired|increase|increased|adds?|added|accumulat|kjøp|kjøper|kjøpte|øker|økt|erverv)\w*\b", re.I)
SELL_WORDS = re.compile(r"\b(sell|sells|sold|reduce|reduced|dispose|disposed|cuts?|cut|salg|selger|solgte|reduser|avhend)\w*\b", re.I)
INSTITUTION_WORDS = re.compile(r"\b(fund|fond|asset management|capital management|investment management|institutional|institution|investor|forvalter|forvaltning|pension|pensjon|mutual fund|etf)\b", re.I)
FOREIGN_WORDS = re.compile(r"\b(foreign|international investors?|utenlandsk|utenlandske|british|german|american|uk investors?|us investors?|engelske|tyske)\b", re.I)
FLAG_WORDS = re.compile(r"\b(flagging|flagged|major holdings?|large shareholdings?|disclosure of (?:large|major) shareholdings?|threshold crossing|notification of major holdings?|meldepliktig eierandel|stor aksjonær|større aksjonær)\b", re.I)
BLOCK_WORDS = re.compile(r"\b(block trade|block sale|accelerated bookbuild|bookbuilding|placement|private placement|blokksalg|blokkhandel|plassering)\b", re.I)
OWNERSHIP_WORDS = re.compile(r"\b(ownership|shareholder|shareholding|stake|eierandel|aksjonær|aksjonaer|beholdning)\b", re.I)


def _now_dt():
    return datetime.now(timezone.utc)


def _now():
    return _now_dt().isoformat()


def _parse_dt(value):
    if not value:
        return None
    try:
        dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)
    except (TypeError, ValueError):
        try:
            return datetime.fromisoformat(str(value)[:10]).replace(tzinfo=timezone.utc)
        except (TypeError, ValueError):
            return None


def _ensure_schema():
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn = connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS capital_flow_events (
          id {identity},
          fingerprint TEXT NOT NULL UNIQUE,
          ticker TEXT,
          instrument_name TEXT,
          asset_class TEXT NOT NULL DEFAULT 'stock',
          event_type TEXT NOT NULL,
          direction TEXT NOT NULL DEFAULT 'neutral',
          actor TEXT,
          actor_type TEXT,
          shares DOUBLE PRECISION,
          price DOUBLE PRECISION,
          value_nok DOUBLE PRECISION,
          event_at TEXT NOT NULL,
          first_seen_at TEXT NOT NULL,
          last_seen_at TEXT NOT NULL,
          title TEXT NOT NULL,
          summary TEXT,
          source TEXT NOT NULL,
          source_url TEXT,
          evidence_level TEXT NOT NULL,
          official INTEGER NOT NULL DEFAULT 0,
          alert_eligible INTEGER NOT NULL DEFAULT 0,
          payload_json TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_capital_flow_event_at ON capital_flow_events(event_at);
        CREATE INDEX IF NOT EXISTS idx_capital_flow_ticker ON capital_flow_events(ticker);
        CREATE INDEX IF NOT EXISTS idx_capital_flow_type ON capital_flow_events(event_type);
        CREATE INDEX IF NOT EXISTS idx_capital_flow_first_seen ON capital_flow_events(first_seen_at);
        """)
        conn.commit()
    finally:
        conn.close()


def _fingerprint(prefix, *parts):
    raw = "|".join(str(x or "").strip().lower() for x in parts)
    return prefix + ":" + hashlib.sha256(raw.encode("utf-8", "ignore")).hexdigest()[:32]


def _upsert(event):
    event = dict(event)
    now = _now()
    event.setdefault("first_seen_at", now)
    event["last_seen_at"] = now
    encoded = json.dumps(event, ensure_ascii=False, separators=(",", ":"), default=str)
    conn = connect()
    try:
        conn.execute(
            "INSERT INTO capital_flow_events(fingerprint,ticker,instrument_name,asset_class,event_type,direction,actor,actor_type,shares,price,value_nok,event_at,first_seen_at,last_seen_at,title,summary,source,source_url,evidence_level,official,alert_eligible,payload_json) "
            "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) "
            "ON CONFLICT(fingerprint) DO UPDATE SET last_seen_at=excluded.last_seen_at,title=excluded.title,summary=excluded.summary,source_url=COALESCE(excluded.source_url,capital_flow_events.source_url),payload_json=excluded.payload_json",
            (
                event["fingerprint"], event.get("ticker"), event.get("instrument_name"), event.get("asset_class", "stock"),
                event["event_type"], event.get("direction", "neutral"), event.get("actor"), event.get("actor_type"),
                event.get("shares"), event.get("price"), event.get("value_nok"), event["event_at"], event["first_seen_at"], now,
                event["title"], event.get("summary"), event["source"], event.get("source_url"), event["evidence_level"],
                1 if event.get("official") else 0, 1 if event.get("alert_eligible") else 0, encoded,
            ),
        )
        cutoff = (_now_dt() - timedelta(days=RETENTION_DAYS)).isoformat()
        conn.execute("DELETE FROM capital_flow_events WHERE event_at<?", (cutoff,))
        conn.commit()
    finally:
        conn.close()


def _ingest_insider_history():
    conn = connect()
    try:
        cutoff = (_now_dt() - timedelta(days=180)).isoformat()
        try:
            rows = conn.execute(
                "SELECT fingerprint,ticker,company,actor,role,direction,activity_type,shares,price,trade_date,published_at,transaction_value,title,summary,source,source_url,captured_at "
                "FROM insider_history WHERE COALESCE(published_at,captured_at,trade_date)>=? ORDER BY COALESCE(published_at,captured_at,trade_date) DESC LIMIT 1000",
                (cutoff,),
            ).fetchall()
        except Exception:
            rows = []
    finally:
        conn.close()

    count = 0
    for row in rows:
        d = dict(row)
        direction = str(d.get("direction") or "neutral").lower()
        if direction not in {"buy", "sell"}:
            continue
        event_at = d.get("published_at") or d.get("captured_at") or d.get("trade_date")
        if not _parse_dt(event_at):
            continue
        value = d.get("transaction_value")
        actor = d.get("actor")
        ticker = str(d.get("ticker") or "").upper().replace(".OL", "") or None
        title = d.get("title") or f"{ticker or d.get('company') or 'Oslo Børs'} · primærinnsider {direction}"
        _upsert({
            "fingerprint": "insider:" + str(d.get("fingerprint") or _fingerprint("trade", ticker, actor, d.get("trade_date"), d.get("shares"), direction)),
            "ticker": ticker,
            "instrument_name": d.get("company"),
            "asset_class": "stock",
            "event_type": "PRIMARY_INSIDER",
            "direction": direction,
            "actor": actor,
            "actor_type": "primary_insider",
            "shares": d.get("shares"),
            "price": d.get("price"),
            "value_nok": value,
            "event_at": str(event_at),
            "title": title,
            "summary": d.get("summary") or (f"{actor or 'Primærinnsider'} {direction} {d.get('shares') or ''} aksjer".strip()),
            "source": d.get("source") or "Euronext / Oslo Børs",
            "source_url": d.get("source_url"),
            "evidence_level": "verified",
            "official": True,
            "alert_eligible": direction in {"buy", "sell"},
        })
        count += 1
    return count


def _classify_news(item):
    text = " ".join(str(item.get(k) or "") for k in ("title", "summary", "category", "topic"))
    if not text.strip():
        return None
    direction = "buy" if BUY_WORDS.search(text) else "sell" if SELL_WORDS.search(text) else "neutral"
    if FLAG_WORDS.search(text):
        kind = "LARGE_HOLDING"
    elif BLOCK_WORDS.search(text):
        kind = "BLOCK_TRADE"
    elif FOREIGN_WORDS.search(text) and (OWNERSHIP_WORDS.search(text) or direction != "neutral"):
        kind = "FOREIGN_OWNERSHIP"
    elif INSTITUTION_WORDS.search(text) and (OWNERSHIP_WORDS.search(text) or direction != "neutral"):
        kind = "INSTITUTIONAL_FLOW"
    elif OWNERSHIP_WORDS.search(text) and direction != "neutral":
        kind = "OWNERSHIP_CHANGE"
    else:
        return None
    return kind, direction


def _ingest_market_news():
    try:
        feed = general_news_runtime.general_market_news(limit=50) or {}
    except Exception:
        return 0
    count = 0
    for item in feed.get("items") or []:
        classified = _classify_news(item)
        if not classified:
            continue
        kind, direction = classified
        event_at = item.get("published_at") or _now()
        official = bool(item.get("official"))
        evidence = "verified" if official else "reported"
        ticker = str(item.get("ticker") or "").upper().replace(".OL", "") or None
        source_url = item.get("url")
        title = str(item.get("title") or "Kapitalflyt").strip()
        fp = _fingerprint("news", item.get("node_id") or source_url, ticker, title, event_at)
        # Media context can be useful, but only direct ticker-linked items with an
        # explicit direction become push-eligible. It never changes the score.
        alert_eligible = official or bool(ticker and direction in {"buy", "sell"} and INSTITUTION_WORDS.search(title))
        _upsert({
            "fingerprint": fp,
            "ticker": ticker,
            "instrument_name": item.get("company"),
            "asset_class": "stock",
            "event_type": kind,
            "direction": direction,
            "actor": None,
            "actor_type": "institution_or_holder" if kind in {"INSTITUTIONAL_FLOW", "FOREIGN_OWNERSHIP", "LARGE_HOLDING"} else None,
            "event_at": str(event_at),
            "title": title,
            "summary": item.get("summary") or title,
            "source": item.get("publisher") or ("Euronext / Oslo Børs" if official else "Markedsnyheter"),
            "source_url": source_url,
            "evidence_level": evidence,
            "official": official,
            "alert_eligible": alert_eligible,
        })
        count += 1
    return count


def scan_once():
    if not _SCAN_LOCK.acquire(blocking=False):
        return {"status": "busy"}
    try:
        _ensure_schema()
        insiders = _ingest_insider_history()
        news = _ingest_market_news()
        return {"status": "ok", "insider_events_seen": insiders, "ownership_news_seen": news, "generated_at": _now()}
    finally:
        _SCAN_LOCK.release()


def _bucket(event_at):
    dt = _parse_dt(event_at)
    if not dt:
        return "HISTORICAL"
    age = _now_dt() - dt.astimezone(timezone.utc)
    if age <= timedelta(hours=NEW_HOURS):
        return "NEW"
    if age <= timedelta(days=ACTIVE_DAYS):
        return "ACTIVE"
    return "HISTORICAL"


def list_events(limit=100, state=None, event_type=None, ticker=None, evidence=None):
    limit = max(1, min(int(limit or 100), MAX_ITEMS))
    clauses, params = [], []
    if event_type:
        clauses.append("event_type=?"); params.append(str(event_type).upper())
    if ticker:
        clauses.append("ticker=?"); params.append(str(ticker).upper().replace(".OL", ""))
    if evidence:
        clauses.append("evidence_level=?"); params.append(str(evidence).lower())
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    conn = connect()
    try:
        rows = conn.execute(
            "SELECT id,fingerprint,ticker,instrument_name,asset_class,event_type,direction,actor,actor_type,shares,price,value_nok,event_at,first_seen_at,last_seen_at,title,summary,source,source_url,evidence_level,official,alert_eligible "
            f"FROM capital_flow_events{where} ORDER BY event_at DESC,id DESC LIMIT ?",
            tuple(params + [max(limit * 4, 200)]),
        ).fetchall()
    finally:
        conn.close()
    items = []
    wanted = str(state or "").upper()
    for row in rows:
        item = dict(row)
        item["state"] = _bucket(item.get("event_at"))
        item["official"] = bool(item.get("official"))
        item["alert_eligible"] = bool(item.get("alert_eligible"))
        if wanted and wanted not in {"ALL", item["state"]}:
            continue
        items.append(item)
        if len(items) >= limit:
            break
    counts = {"NEW": 0, "ACTIVE": 0, "HISTORICAL": 0}
    conn = connect()
    try:
        all_rows = conn.execute("SELECT event_at FROM capital_flow_events ORDER BY event_at DESC LIMIT 2000").fetchall()
    finally:
        conn.close()
    for row in all_rows:
        counts[_bucket(row["event_at"])] += 1
    return {
        "status": "ok",
        "items": items,
        "counts": counts,
        "policy": {
            "new_hours": NEW_HOURS,
            "active_days": ACTIVE_DAYS,
            "score_effect": "none",
            "verified_definition": "Official exchange/primary-insider evidence",
            "reported_definition": "Media/context evidence; not treated as verified holdings delta",
        },
        "generated_at": _now(),
    }


def status():
    _ensure_schema()
    conn = connect()
    try:
        row = conn.execute("SELECT COUNT(*) AS n,MAX(last_seen_at) AS last_seen FROM capital_flow_events").fetchone()
        verified = conn.execute("SELECT COUNT(*) AS n FROM capital_flow_events WHERE evidence_level='verified'").fetchone()
        reported = conn.execute("SELECT COUNT(*) AS n FROM capital_flow_events WHERE evidence_level='reported'").fetchone()
    finally:
        conn.close()
    return {
        "status": "ok",
        "events": int(row["n"] if row else 0),
        "verified": int(verified["n"] if verified else 0),
        "reported": int(reported["n"] if reported else 0),
        "last_seen_at": row["last_seen"] if row else None,
        "score_effect": "none",
        "coverage": ["primary_insiders", "major_holding_disclosures", "institutional/fund ownership news", "foreign ownership context", "block trades"],
        "generated_at": _now(),
    }


def _scanner_loop():
    while True:
        try:
            scan_once()
        except Exception:
            pass
        time.sleep(SCAN_INTERVAL_SECONDS)


def _start_scanner():
    global _SCAN_STARTED
    if _SCAN_STARTED:
        return
    _SCAN_STARTED = True
    threading.Thread(target=_scanner_loop, daemon=True, name="capital-flow-radar").start()


def install():
    if getattr(extra_api, "_capital_flow_runtime_v1", False):
        return
    _ensure_schema()
    original_install = extra_api.install

    def patched_install(app):
        original_install(app)

        @app.get("/api/capital-flow")
        def capital_flow(limit: int = 100, state: str | None = None, type: str | None = None, ticker: str | None = None, evidence: str | None = None, refresh: bool = False):
            if refresh:
                scan_once()
            return list_events(limit=limit, state=state, event_type=type, ticker=ticker, evidence=evidence)

        @app.get("/api/capital-flow/status")
        def capital_flow_status():
            return status()

    extra_api.install = patched_install
    extra_api._capital_flow_runtime_v1 = True
    _start_scanner()


install()
