# NordicSignal database layer
import os
import re
import sqlite3
from pathlib import Path

DEFAULT_DB_PATH = Path(__file__).resolve().parent / "nordicsignal.db"
DB_PATH = Path(os.getenv("NORDICSIGNAL_DB_PATH", str(DEFAULT_DB_PATH))).expanduser().resolve()
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
USING_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))

SCHEMA_SQLITE = """
CREATE TABLE IF NOT EXISTS stocks (
    ticker TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    sector TEXT,
    exchange TEXT DEFAULT 'Oslo Børs',
    active INTEGER DEFAULT 1
);
CREATE TABLE IF NOT EXISTS quotes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL,
    price REAL,
    change_pct REAL,
    volume INTEGER,
    captured_at TEXT NOT NULL,
    FOREIGN KEY(ticker) REFERENCES stocks(ticker)
);
CREATE TABLE IF NOT EXISTS fundamentals (
    ticker TEXT PRIMARY KEY,
    revenue REAL,
    ebitda REAL,
    ebit REAL,
    eps REAL,
    free_cash_flow REAL,
    net_debt REAL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(ticker) REFERENCES stocks(ticker)
);
CREATE TABLE IF NOT EXISTS insider_trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL,
    person TEXT,
    role TEXT,
    transaction_type TEXT,
    shares REAL,
    price REAL,
    trade_date TEXT,
    source TEXT,
    FOREIGN KEY(ticker) REFERENCES stocks(ticker)
);
CREATE TABLE IF NOT EXISTS short_positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL,
    holder TEXT,
    short_pct REAL,
    position_date TEXT,
    source TEXT,
    FOREIGN KEY(ticker) REFERENCES stocks(ticker)
);
CREATE TABLE IF NOT EXISTS scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL,
    fundamentals INTEGER NOT NULL,
    insider INTEGER NOT NULL,
    valuation INTEGER NOT NULL,
    sentiment INTEGER NOT NULL,
    total INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    source TEXT DEFAULT 'stored',
    FOREIGN KEY(ticker) REFERENCES stocks(ticker)
);
CREATE TABLE IF NOT EXISTS watchlist (
    ticker TEXT PRIMARY KEY,
    created_at TEXT NOT NULL,
    FOREIGN KEY(ticker) REFERENCES stocks(ticker)
);
"""

SCHEMA_POSTGRES = """
CREATE TABLE IF NOT EXISTS stocks (
    ticker TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    sector TEXT,
    exchange TEXT DEFAULT 'Oslo Børs',
    active INTEGER DEFAULT 1
);
CREATE TABLE IF NOT EXISTS quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL REFERENCES stocks(ticker),
    price DOUBLE PRECISION,
    change_pct DOUBLE PRECISION,
    volume BIGINT,
    captured_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS fundamentals (
    ticker TEXT PRIMARY KEY REFERENCES stocks(ticker),
    revenue DOUBLE PRECISION,
    ebitda DOUBLE PRECISION,
    ebit DOUBLE PRECISION,
    eps DOUBLE PRECISION,
    free_cash_flow DOUBLE PRECISION,
    net_debt DOUBLE PRECISION,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS insider_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL REFERENCES stocks(ticker),
    person TEXT,
    role TEXT,
    transaction_type TEXT,
    shares DOUBLE PRECISION,
    price DOUBLE PRECISION,
    trade_date TEXT,
    source TEXT
);
CREATE TABLE IF NOT EXISTS short_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL REFERENCES stocks(ticker),
    holder TEXT,
    short_pct DOUBLE PRECISION,
    position_date TEXT,
    source TEXT
);
CREATE TABLE IF NOT EXISTS scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL REFERENCES stocks(ticker),
    fundamentals INTEGER NOT NULL,
    insider INTEGER NOT NULL,
    valuation INTEGER NOT NULL,
    sentiment INTEGER NOT NULL,
    total INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    source TEXT DEFAULT 'stored'
);
CREATE TABLE IF NOT EXISTS watchlist (
    ticker TEXT PRIMARY KEY REFERENCES stocks(ticker),
    created_at TEXT NOT NULL
);
"""


def _translate_sql(sql):
    sql = sql.replace("INSERT OR IGNORE INTO", "INSERT INTO")
    sql = sql.replace("INSERT OR IGNORE", "INSERT")
    if "INSERT INTO" in sql and "ON CONFLICT" not in sql and sql.lstrip().upper().startswith("INSERT INTO"):
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return sql.replace("?", "%s")


class PostgresConnection:
    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql, params=()):
        return self._connection.execute(_translate_sql(sql), params)

    def executescript(self, script):
        for statement in re.split(r";\s*(?:\n|$)", script):
            statement = statement.strip()
            if statement:
                self.execute(statement)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def connect():
    if USING_POSTGRES:
        try:
            import psycopg
            from psycopg.rows import dict_row
            conn = psycopg.connect(DATABASE_URL, row_factory=dict_row, connect_timeout=10)
            return PostgresConnection(conn)
        except Exception:
            raise
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA busy_timeout=30000")
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def init_db():
    conn = connect()
    conn.executescript(SCHEMA_POSTGRES if USING_POSTGRES else SCHEMA_SQLITE)
    try:
        conn.execute("ALTER TABLE scores ADD COLUMN source TEXT DEFAULT 'stored'")
    except Exception:
        pass
    conn.commit()
    conn.close()
