"""Persistent point-in-time observations for Early Discovery research.

This module is intentionally research-only. It stores state changes so the model can
be replayed and validated without changing score, Opportunity, High Conviction,
alerts, thresholds, or position sizing.
"""
from __future__ import annotations
from datetime import datetime, timezone
import json

from fastapi import Query
import main
from database import connect, USING_POSTGRES
import early_discovery_research as research

app = main.app

def _now():
    return datetime.now(timezone.utc).isoformat()

def _ensure_schema():
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn=connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS early_discovery_observations (
          id {identity},
          ticker TEXT NOT NULL,
          market_date TEXT NOT NULL,
          label TEXT NOT NULL,
          research_score DOUBLE PRECISION,
          components TEXT NOT NULL,
          reasons TEXT NOT NULL,
          model_version TEXT NOT NULL,
          observed_at TEXT NOT NULL,
          UNIQUE(ticker,market_date,model_version)
        );
        """)
        conn.commit()
    finally: conn.close()

def record(ticker, result, observed_at=None):
    ticker=str(ticker or "").upper().replace(".OL","")
    if not ticker or result.get("status")!="ok": return {"stored":False,"reason":"invalid_or_insufficient"}
    market_date=str(result.get("as_of") or "")[:10]
    if len(market_date)!=10: return {"stored":False,"reason":"missing_market_date"}
    conn=connect()
    try:
        cur=conn.execute(
          "INSERT INTO early_discovery_observations(ticker,market_date,label,research_score,components,reasons,model_version,observed_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(ticker,market_date,model_version) DO NOTHING",
          (ticker,market_date,result.get("label"),result.get("score"),json.dumps(result.get("components") or {},separators=(",",":")),json.dumps(result.get("reasons") or [],ensure_ascii=False,separators=(",",":")),result.get("version") or research.VERSION,observed_at or _now()))
        conn.commit()
        return {"stored":bool(getattr(cur,"rowcount",0)),"ticker":ticker,"market_date":market_date,"label":result.get("label"),"score_effect":0}
    finally: conn.close()

def latest(limit=100, labels=None):
    limit=max(1,min(200,int(limit)))
    wanted={str(x).upper() for x in (labels or []) if x}
    conn=connect()
    try:
        rows=[dict(x) for x in conn.execute(
          "SELECT o.* FROM early_discovery_observations o JOIN (SELECT ticker,MAX(id) id FROM early_discovery_observations GROUP BY ticker) z ON z.id=o.id ORDER BY COALESCE(o.research_score,-1) DESC,o.ticker LIMIT ?",
          (limit,)).fetchall()]
    finally: conn.close()
    out=[]
    for row in rows:
        if wanted and row["label"] not in wanted: continue
        row["components"]=json.loads(row.get("components") or "{}")
        row["reasons"]=json.loads(row.get("reasons") or "[]")
        row["score_effect"]=0
        row["policy"]="research_watchlist_only_no_production_signal_effect"
        out.append(row)
    return out

@app.get("/api/early-discovery")
def early_discovery_latest(limit:int=Query(100,ge=1,le=200), state:str|None=None):
    labels=[x.strip().upper() for x in (state or "").split(",") if x.strip()]
    items=latest(limit,labels)
    return {"items":items,"count":len(items),"model_version":research.VERSION,"score_effect":0,"policy":"research_watchlist_only_no_production_signal_effect"}

def install():
    _ensure_schema()
