from datetime import datetime, timezone
from urllib.parse import quote_plus

from fastapi import HTTPException
from pydantic import BaseModel, Field

from database import connect, USING_POSTGRES
from providers import YahooProvider


def _now(): return datetime.now(timezone.utc).isoformat()

def _ensure_schema():
    conn=connect()
    schema = '''
    CREATE TABLE IF NOT EXISTS paper_accounts (
        id INTEGER PRIMARY KEY CHECK(id=1),
        starting_cash DOUBLE PRECISION NOT NULL DEFAULT 100000,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS paper_trades (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id INTEGER NOT NULL DEFAULT 1,
        ticker TEXT NOT NULL,
        side TEXT NOT NULL CHECK(side IN ('buy','sell')),
        shares DOUBLE PRECISION NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        fee DOUBLE PRECISION NOT NULL DEFAULT 0,
        executed_at TEXT NOT NULL,
        note TEXT,
        FOREIGN KEY(account_id) REFERENCES paper_accounts(id)
    );
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS paper_accounts (
        id INTEGER PRIMARY KEY CHECK(id=1),
        starting_cash REAL NOT NULL DEFAULT 100000,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS paper_trades (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        account_id INTEGER NOT NULL DEFAULT 1,
        ticker TEXT NOT NULL,
        side TEXT NOT NULL CHECK(side IN ('buy','sell')),
        shares REAL NOT NULL,
        price REAL NOT NULL,
        fee REAL NOT NULL DEFAULT 0,
        executed_at TEXT NOT NULL,
        note TEXT,
        FOREIGN KEY(account_id) REFERENCES paper_accounts(id)
    );
    '''
    conn.executescript(schema)
    if not conn.execute('SELECT 1 FROM paper_accounts WHERE id=1').fetchone():
        now=_now(); conn.execute('INSERT INTO paper_accounts(id,starting_cash,created_at,updated_at) VALUES(1,?,?,?)',(100000,now,now))
    conn.commit(); conn.close()

class TradeIn(BaseModel):
    ticker:str=Field(min_length=1,max_length=12); side:str; shares:float=Field(gt=0); price:float|None=Field(default=None,gt=0); fee:float=Field(default=0,ge=0); note:str|None=Field(default=None,max_length=240)
class AccountIn(BaseModel): starting_cash:float=Field(gt=0,le=1000000000)

def _quote(provider,ticker):
    q=provider.quote(ticker)
    if q.get('price') is None: raise HTTPException(502,detail='Live quote unavailable')
    return q

def _positions(provider):
    conn=connect(); account=conn.execute('SELECT starting_cash FROM paper_accounts WHERE id=1').fetchone(); trades=conn.execute('SELECT * FROM paper_trades WHERE account_id=1 ORDER BY id').fetchall(); conn.close()
    starting=float(account['starting_cash']) if account else 100000.; cash=starting; positions={}; layers={}; realized={}
    for t in trades:
        ticker=t['ticker']; shares=float(t['shares']); price=float(t['price']); gross=shares*price; fee=float(t['fee'] or 0)
        if t['side']=='buy':
            cash-=gross+fee; positions[ticker]=positions.get(ticker,0)+shares; layers.setdefault(ticker,[]).append([shares,gross+fee]); continue
        held=positions.get(ticker,0)
        if shares>held+1e-10: continue
        cash+=gross-fee; positions[ticker]=positions.get(ticker,0)-shares; remaining=shares; removed=0.; queue=layers.setdefault(ticker,[])
        while remaining>1e-10 and queue:
            ls,lc=queue[0]; take=min(remaining,ls); unit=lc/ls if ls else 0.; removed+=take*unit; ls-=take; lc-=take*unit; remaining-=take
            if ls<=1e-10: queue.pop(0)
            else: queue[0]=[ls,lc]
        realized[ticker]=realized.get(ticker,0.)+(gross-fee-removed)
    result=[]
    for ticker,shares in positions.items():
        if abs(shares)<1e-10: continue
        try: price=float(_quote(provider,ticker)['price'])
        except Exception: price=None
        value=shares*price if price is not None else None; cost=sum(x[1] for x in layers.get(ticker,[])); pnl=value-cost if value is not None else None
        result.append({'ticker':ticker,'shares':shares,'price':price,'value':value,'cost_basis':cost,'pnl':pnl,'realized_pnl':realized.get(ticker,0.),'change_pct':pnl/cost*100 if pnl is not None and cost else None})
    market=sum(x['value'] or 0 for x in result); equity=cash+market
    return {'starting_cash':starting,'cash':cash,'positions':result,'market_value':market,'equity':equity,'pnl':equity-starting,'pnl_pct':(equity-starting)/starting*100,'realized_pnl':sum(realized.values())}

def _xirr(cashflows):
    if len(cashflows)<2:return None
    first=cashflows[0][0]; flows=[((dt-first).total_seconds()/31557600.,float(amount)) for dt,amount in cashflows]
    if not any(a<0 for _,a in flows) or not any(a>0 for _,a in flows):return None
    def npv(rate):
        base=1+rate
        if base<=0:return float('inf')
        return sum(a/(base**years) for years,a in flows)
    lo,hi=-.9999,10.; nlo,nhi=npv(lo),npv(hi)
    for _ in range(40):
        if nlo*nhi<=0:break
        hi=hi*2+1; nhi=npv(hi)
    if nlo*nhi>0:return None
    for _ in range(100):
        mid=(lo+hi)/2; nm=npv(mid)
        if abs(nm)<1e-7:return mid
        if nlo*nm<=0:hi,nhi=mid,nm
        else:lo,nlo=mid,nm
    return (lo+hi)/2

def _parse_date(value, field):
    try: dt=datetime.fromisoformat(value.replace('Z','+00:00'))
    except ValueError: raise HTTPException(400,detail=f'Invalid {field} date; use YYYY-MM-DD')
    if dt.tzinfo is None: dt=dt.replace(tzinfo=timezone.utc)
    return dt

def _backtest(provider,ticker,start,end,initial_cash,monthly_investment,reinvest_dividends):
    from dividend_runtime import fetch_dividend_events
    start_dt=_parse_date(start,'start'); end_dt=_parse_date(end,'end')
    if end_dt<=start_dt: raise HTTPException(400,detail='End date must be after start date')
    start_ts=int(start_dt.timestamp()); end_ts=int(end_dt.timestamp())+86399
    symbol=provider.symbol(ticker)
    data=provider._get(f'{provider.BASE}/v8/finance/chart/{symbol}',{'period1':start_ts,'period2':end_ts,'interval':'1d','events':'div|split'})
    result=((data.get('chart') or {}).get('result') or [])
    if not result: raise HTTPException(404,detail=f'No historical data for {ticker}')
    result=result[0]; timestamps=result.get('timestamp') or []; quote=(result.get('indicators',{}).get('quote') or [{}])[0]; closes=quote.get('close') or []
    rows=[]
    for i,ts in enumerate(timestamps):
        if i<len(closes) and closes[i] is not None: rows.append({'timestamp':int(ts),'date':datetime.fromtimestamp(ts,timezone.utc).isoformat(),'close':closes[i]})
    if not rows: raise HTTPException(404,detail='No historical data for selected period')
    divs=fetch_dividend_events(provider,ticker,start_ts-86400,end_ts+86400)
    div_by_day={}
    for d in divs: div_by_day[d['date']]=div_by_day.get(d['date'],0.0)+float(d['amount'])
    cash=0.; shares=0.; invested=0.; dividend_total=0.; last_month=None; points=[]; tx=[]; flows=[]
    for row in rows:
        d=datetime.fromtimestamp(row['timestamp'],timezone.utc).date(); price=float(row['close'])
        if last_month!=(d.year,d.month):
            contribution=float(initial_cash) if last_month is None else float(monthly_investment)
            if contribution>0:
                cash+=contribution; bought=contribution/price; shares+=bought; cash-=bought*price; invested+=contribution
                tx.append({'date':d.isoformat(),'side':'buy','shares':bought,'price':price,'amount':contribution}); flows.append((datetime(d.year,d.month,d.day,tzinfo=timezone.utc),-contribution))
            last_month=(d.year,d.month)
        dividend_per=div_by_day.get(d.isoformat(),0.)
        if dividend_per and shares:
            dividend=shares*dividend_per; dividend_total+=dividend
            if reinvest_dividends:
                added=dividend/price; shares+=added; tx.append({'date':d.isoformat(),'side':'dividend_reinvest','shares':added,'price':price,'amount':dividend})
            else:
                cash+=dividend; tx.append({'date':d.isoformat(),'side':'dividend_cash','shares':shares,'price':price,'amount':dividend})
        value=shares*price; equity=cash+value; points.append({'date':d.isoformat(),'price':price,'shares':shares,'cash':cash,'value':value,'equity':equity,'invested':invested})
    end_equity=points[-1]['equity']; total=end_equity-invested; flows.append((datetime.fromtimestamp(rows[-1]['timestamp'],timezone.utc),end_equity))
    return {'ticker':ticker,'start':rows[0]['date'],'end':rows[-1]['date'],'initial_cash':initial_cash,'monthly_investment':monthly_investment,'reinvest_dividends':reinvest_dividends,'invested':invested,'final_equity':end_equity,'return':total,'return_pct':total/invested*100 if invested else 0,'xirr':_xirr(flows),'shares':shares,'cash':cash,'dividends':dividend_total,'points':points,'transactions':tx[-100:]}
