from datetime import datetime, timezone
from urllib.parse import quote_plus

from fastapi import HTTPException
from pydantic import BaseModel, Field

from database import connect, USING_POSTGRES
from providers import YahooProvider


def _now(): return datetime.now(timezone.utc).isoformat()


def _ensure_schema():
    conn=connect()
    schema = '''
    CREATE TABLE IF NOT EXISTS paper_accounts (id INTEGER PRIMARY KEY CHECK(id=1), starting_cash DOUBLE PRECISION NOT NULL DEFAULT 100000, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS paper_trades (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id INTEGER NOT NULL DEFAULT 1, ticker TEXT NOT NULL, side TEXT NOT NULL CHECK(side IN ('buy','sell')), shares DOUBLE PRECISION NOT NULL, price DOUBLE PRECISION NOT NULL, fee DOUBLE PRECISION NOT NULL DEFAULT 0, executed_at TEXT NOT NULL, note TEXT, FOREIGN KEY(account_id) REFERENCES paper_accounts(id));
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS paper_accounts (id INTEGER PRIMARY KEY CHECK(id=1), starting_cash REAL NOT NULL DEFAULT 100000, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS paper_trades (id INTEGER PRIMARY KEY AUTOINCREMENT, account_id INTEGER NOT NULL DEFAULT 1, ticker TEXT NOT NULL, side TEXT NOT NULL CHECK(side IN ('buy','sell')), shares REAL NOT NULL, price REAL NOT NULL, fee REAL NOT NULL DEFAULT 0, executed_at TEXT NOT NULL, note TEXT, FOREIGN KEY(account_id) REFERENCES paper_accounts(id));
    '''
    conn.executescript(schema)
    if not conn.execute('SELECT 1 FROM paper_accounts WHERE id=1').fetchone():
        now=_now(); conn.execute('INSERT INTO paper_accounts(id,starting_cash,created_at,updated_at) VALUES(1,?,?,?)',(100000,now,now))
    conn.commit(); conn.close()

class TradeIn(BaseModel):
    ticker:str=Field(min_length=1,max_length=12); side:str; shares:float=Field(gt=0); price:float|None=Field(default=None,gt=0); fee:float=Field(default=0,ge=0); note:str|None=Field(default=None,max_length=240)
class AccountIn(BaseModel): starting_cash:float=Field(gt=0,le=1000000000)

def _quote(provider,ticker):
    q=provider.quote(ticker)
    if q.get('price') is None: raise HTTPException(502,detail='Live quote unavailable')
    return q

def _positions(provider):
    conn=connect(); account=conn.execute('SELECT starting_cash FROM paper_accounts WHERE id=1').fetchone(); trades=conn.execute('SELECT * FROM paper_trades WHERE account_id=1 ORDER BY id').fetchall(); conn.close()
    starting=float(account['starting_cash']) if account else 100000.; cash=starting; positions={}; layers={}; realized={}
    for t in trades:
        ticker=t['ticker']; shares=float(t['shares']); price=float(t['price']); gross=shares*price; fee=float(t['fee'] or 0)
        if t['side']=='buy': cash-=gross+fee; positions[ticker]=positions.get(ticker,0)+shares; layers.setdefault(ticker,[]).append([shares,gross+fee]); continue
        held=positions.get(ticker,0)
        if shares>held+1e-10: continue
        cash+=gross-fee; positions[ticker]=positions.get(ticker,0)-shares; remaining=shares; removed=0.; queue=layers.setdefault(ticker,[])
        while remaining>1e-10 and queue:
            ls,lc=queue[0]; take=min(remaining,ls); unit=lc/ls if ls else 0.; removed+=take*unit; ls-=take; lc-=take*unit; remaining-=take
            if ls<=1e-10: queue.pop(0)
            else: queue[0]=[ls,lc]
        realized[ticker]=realized.get(ticker,0.)+(gross-fee-removed)
    result=[]
    for ticker,shares in positions.items():
        if abs(shares)<1e-10: continue
        try: price=float(_quote(provider,ticker)['price'])
        except Exception: price=None
        value=shares*price if price is not None else None; cost=sum(x[1] for x in layers.get(ticker,[])); pnl=value-cost if value is not None else None
        result.append({'ticker':ticker,'shares':shares,'price':price,'value':value,'cost_basis':cost,'pnl':pnl,'realized_pnl':realized.get(ticker,0.),'change_pct':pnl/cost*100 if pnl is not None and cost else None})
    market=sum(x['value'] or 0 for x in result); equity=cash+market
    return {'starting_cash':starting,'cash':cash,'positions':result,'market_value':market,'equity':equity,'pnl':equity-starting,'pnl_pct':(equity-starting)/starting*100,'realized_pnl':sum(realized.values())}

def _xirr(cashflows):
    if len(cashflows)<2:return None
    first=cashflows[0][0]; flows=[((dt-first).total_seconds()/31557600.,float(amount)) for dt,amount in cashflows]
    if not any(a<0 for _,a in flows) or not any(a>0 for _,a in flows):return None
    def npv(rate):
        base=1+rate
        if base<=0:return float('inf')
        return sum(a/(base**years) for years,a in flows)
    lo,hi=-.9999,10.; nlo,nhi=npv(lo),npv(hi)
    for _ in range(40):
        if nlo*nhi<=0:break
        hi=hi*2+1; nhi=npv(hi)
    if nlo*nhi>0:return None
    for _ in range(100):
        mid=(lo+hi)/2; nm=npv(mid)
        if abs(nm)<1e-7:return mid
        if nlo*nm<=0:hi,nhi=mid,nm
        else:lo,nlo=mid,nm
    return (lo+hi)/2

def _parse_date(value, field):
    try: dt=datetime.fromisoformat(value.replace('Z','+00:00'))
    except ValueError: raise HTTPException(400,detail=f'Invalid {field} date; use YYYY-MM-DD')
    if dt.tzinfo is None: dt=dt.replace(tzinfo=timezone.utc)
    return dt

def _historical_rows(provider, ticker, start_ts, end_ts):
    symbol=ticker if ticker.startswith('^') or '.' in ticker else provider.symbol(ticker)
    data=provider._get(f'{provider.BASE}/v8/finance/chart/{symbol}',{'period1':int(start_ts),'period2':int(end_ts),'interval':'1d','events':'div|split'})
    result=((data.get('chart') or {}).get('result') or [])
    if not result: raise HTTPException(404,detail=f'No historical data for {ticker}')
    result=result[0]; timestamps=result.get('timestamp') or []; quote=(result.get('indicators',{}).get('quote') or [{}])[0]; closes=quote.get('close') or []
    rows=[{'timestamp':int(ts),'date':datetime.fromtimestamp(ts,timezone.utc).isoformat(),'close':closes[i]} for i,ts in enumerate(timestamps) if i<len(closes) and closes[i] is not None]
    if not rows: raise HTTPException(404,detail=f'No historical data for {ticker}')
    return rows

def _fee_for_gross(gross, fee_pct, fixed_fee): return max(0.,gross)*max(0.,fee_pct)/100.+max(0.,fixed_fee)

def _buy_with_cash(cash, price, fee_pct, fixed_fee):
    if cash<=0 or price<=0:return 0.,0.,0.
    pct=max(0.,fee_pct)/100.; fixed=max(0.,fixed_fee)
    gross=max(0.,(cash-fixed)/(1.+pct))
    fee=_fee_for_gross(gross,fee_pct,fixed)
    return gross/price, gross, fee

def _backtest(provider,ticker,start,end,initial_cash,monthly_investment,reinvest_dividends,fee_pct=0.,fixed_fee=0.,strategy='dca',benchmark='^OSEBX'):
    from dividend_runtime import fetch_dividend_events
    strategy=(strategy or 'dca').lower()
    if strategy not in ('dca','lump_sum','sma_cross'): raise HTTPException(400,detail='strategy must be dca, lump_sum or sma_cross')
    start_dt=_parse_date(start,'start'); end_dt=_parse_date(end,'end')
    if end_dt<=start_dt: raise HTTPException(400,detail='End date must be after start date')
    start_ts=int(start_dt.timestamp()); end_ts=int(end_dt.timestamp())+86399
    rows=_historical_rows(provider,ticker.upper(),start_ts,end_ts)
    div_by_day={}
    if not ticker.startswith('^'):
        for d in fetch_dividend_events(provider,ticker,start_ts-86400,end_ts+86400): div_by_day[d['date']]=div_by_day.get(d['date'],0.)+float(d['amount'])
    cash=0.; shares=0.; invested=0.; fees_paid=0.; dividend_total=0.; last_month=None; points=[]; tx=[]; flows=[]; closes=[]
    for row in rows:
        d=datetime.fromtimestamp(row['timestamp'],timezone.utc).date(); price=float(row['close']); closes.append(price)
        if strategy in ('dca','sma_cross') and last_month!=(d.year,d.month):
            contribution=float(initial_cash) if last_month is None else float(monthly_investment)
            if contribution>0:
                cash+=contribution; invested+=contribution; flows.append((datetime(d.year,d.month,d.day,tzinfo=timezone.utc),-contribution)); tx.append({'date':d.isoformat(),'side':'contribution','amount':contribution})
            last_month=(d.year,d.month)
        elif strategy=='lump_sum' and last_month is None:
            contribution=float(initial_cash); cash+=contribution; invested+=contribution; flows.append((datetime(d.year,d.month,d.day,tzinfo=timezone.utc),-contribution)); tx.append({'date':d.isoformat(),'side':'contribution','amount':contribution}); last_month=(d.year,d.month)
        dividend_per=div_by_day.get(d.isoformat(),0.)
        if dividend_per and shares:
            dividend=shares*dividend_per; dividend_total+=dividend
            if reinvest_dividends and price>0:
                add,gross,fee=_buy_with_cash(dividend,price,fee_pct,fixed_fee); shares+=add; fees_paid+=fee; tx.append({'date':d.isoformat(),'side':'dividend_reinvest','shares':add,'price':price,'amount':dividend,'fee':fee})
            else: cash+=dividend; tx.append({'date':d.isoformat(),'side':'dividend_cash','shares':shares,'price':price,'amount':dividend,'fee':0.})
        signal=True
        if strategy=='sma_cross':
            fast=sum(closes[-50:])/min(50,len(closes)); slow=sum(closes[-200:])/min(200,len(closes)); signal=len(closes)>=200 and fast>slow
        if strategy in ('dca','lump_sum'):
            signal=True
        if signal and cash>0 and price>0:
            bought,gross,fee=_buy_with_cash(cash,price,fee_pct,fixed_fee)
            if bought>0: shares+=bought; cash-=gross+fee; fees_paid+=fee; tx.append({'date':d.isoformat(),'side':'buy','shares':bought,'price':price,'amount':gross,'fee':fee})
        elif strategy=='sma_cross' and not signal and shares>0:
            gross=shares*price; fee=_fee_for_gross(gross,fee_pct,fixed_fee); cash+=gross-fee; fees_paid+=fee; tx.append({'date':d.isoformat(),'side':'sell','shares':shares,'price':price,'amount':gross,'fee':fee}); shares=0.
        value=shares*price; equity=cash+value; points.append({'date':d.isoformat(),'price':price,'shares':shares,'cash':cash,'value':value,'equity':equity,'invested':invested})
    end_equity=points[-1]['equity']; total=end_equity-invested; flows.append((datetime.fromtimestamp(rows[-1]['timestamp'],timezone.utc),end_equity))
    benchmark_result=None
    if benchmark and benchmark.upper()!=ticker.upper():
        try:
            b_rows=_historical_rows(provider,benchmark,start_ts,end_ts); b_cash=0.; b_shares=0.; b_last=None
            for row in b_rows:
                d=datetime.fromtimestamp(row['timestamp'],timezone.utc).date(); price=float(row['close'])
                if b_last!=(d.year,d.month):
                    contribution=float(initial_cash) if b_last is None else (0. if strategy=='lump_sum' else float(monthly_investment)); b_cash+=contribution; b_last=(d.year,d.month)
                    if b_cash>0 and price>0:
                        bought,gross,fee=_buy_with_cash(b_cash,price,fee_pct,fixed_fee); b_shares+=bought; b_cash-=gross+fee
            benchmark_equity=b_cash+b_shares*float(b_rows[-1]['close']); benchmark_result={'ticker':benchmark,'final_equity':benchmark_equity,'return':benchmark_equity-invested,'return_pct':(benchmark_equity-invested)/invested*100 if invested else 0.}
        except Exception:
            benchmark_result=None
    return {'ticker':ticker,'strategy':strategy,'strategy_label':{'dca':'Månedlig investering','lump_sum':'Alt inn med en gang','sma_cross':'50/200 SMA trendstrategi'}[strategy],'start':rows[0]['date'],'end':rows[-1]['date'],'initial_cash':initial_cash,'monthly_investment':monthly_investment,'reinvest_dividends':reinvest_dividends,'fee_pct':fee_pct,'fixed_fee':fixed_fee,'invested':invested,'final_equity':end_equity,'return':total,'return_pct':total/invested*100 if invested else 0,'xirr':_xirr(flows),'shares':shares,'cash':cash,'dividends':dividend_total,'fees_paid':fees_paid,'benchmark':benchmark_result,'points':points,'transactions':tx[-300:]}

def install(app):
    _ensure_schema(); provider=YahooProvider()
    @app.get('/api/search')
    def case_insensitive_search(q:str=''):
        q=q.strip()
        if not q:return {'items':[]}
        conn=connect(); pattern=f'%{q}%'; rows=conn.execute("SELECT ticker,name,sector,exchange FROM stocks WHERE active=1 AND (LOWER(ticker) LIKE LOWER(?) OR LOWER(name) LIKE LOWER(?)) ORDER BY name LIMIT 30",(pattern,pattern)).fetchall(); conn.close(); return {'items':[dict(r) for r in rows]}
    @app.get('/api/paper/account')
    def paper_account():
        conn=connect(); row=conn.execute('SELECT * FROM paper_accounts WHERE id=1').fetchone(); conn.close(); return dict(row) if row else {'id':1,'starting_cash':100000}
    @app.post('/api/paper/account')
    def set_paper_account(payload:AccountIn):
        conn=connect()
        try:
            if conn.execute('SELECT 1 FROM paper_trades WHERE account_id=1 LIMIT 1').fetchone(): raise HTTPException(409,detail='Starting capital cannot be changed after a paper trade. Reset the paper account first.')
            conn.execute('UPDATE paper_accounts SET starting_cash=?,updated_at=? WHERE id=1',(payload.starting_cash,_now())); conn.commit()
        finally: conn.close()
        return paper_account()
    @app.get('/api/paper/portfolio')
    def paper_portfolio():return _positions(provider)
    @app.get('/api/paper/trades')
    def paper_trades(limit:int=100):
        conn=connect(); rows=conn.execute('SELECT * FROM paper_trades WHERE account_id=1 ORDER BY id DESC LIMIT ?',(min(max(limit,1),500),)).fetchall(); conn.close(); return {'items':[dict(r) for r in rows]}
    @app.post('/api/paper/trades')
    def paper_trade(payload:TradeIn):
        side=payload.side.lower(); ticker=payload.ticker.upper()
        if side not in ('buy','sell'):raise HTTPException(400,detail='side must be buy or sell')
        price=payload.price or float(_quote(provider,ticker)['price']); shares=float(payload.shares); fee=float(payload.fee); port=_positions(provider); position=next((p for p in port['positions'] if p['ticker']==ticker),None); held=position['shares'] if position else 0
        if side=='buy' and port['cash']<shares*price+fee:raise HTTPException(400,detail='Insufficient paper cash')
        if side=='sell' and held<shares-1e-10:raise HTTPException(400,detail=f'Insufficient paper shares; holding {held:g}')
        conn=connect(); conn.execute('INSERT INTO paper_trades(account_id,ticker,side,shares,price,fee,executed_at,note) VALUES(1,?,?,?,?,?,?,?)',(ticker,side,shares,price,fee,_now(),payload.note)); conn.commit(); conn.close(); return {'status':'ok','trade':{'ticker':ticker,'side':side,'shares':shares,'price':price,'fee':fee},'portfolio':_positions(provider)}
    @app.post('/api/paper/reset')
    def paper_reset():
        conn=connect(); conn.execute('DELETE FROM paper_trades WHERE account_id=1'); conn.commit(); conn.close(); return {'status':'ok','portfolio':_positions(provider)}
    @app.get('/api/paper/backtest')
    def paper_backtest(ticker:str,start:str,end:str,initial_cash:float=100000,monthly_investment:float=0,reinvest_dividends:bool=True,fee_pct:float=0.,fixed_fee:float=0.,strategy:str='dca',benchmark:str='^OSEBX'):
        if initial_cash<=0 or monthly_investment<0 or fee_pct<0 or fixed_fee<0:raise HTTPException(400,detail='Invalid investment amounts or fees')
        return _backtest(provider,ticker.upper(),start,end,initial_cash,monthly_investment,reinvest_dividends,fee_pct,fixed_fee,strategy,benchmark)
    @app.get('/api/news/{ticker}')
    def stock_news(ticker:str,limit:int=12):
        ticker=ticker.upper(); limit=max(1,min(limit,20)); items=[]
        try:
            data=provider._get(f'{provider.BASE}/v1/finance/search?q={quote_plus(ticker)}&quotesCount=1&newsCount={limit}')
            for n in data.get('news') or []:
                title=n.get('title') or ''; publisher=n.get('publisher') or 'Unknown'; link=n.get('link') or ''; ts=n.get('providerPublishTime'); dt=datetime.fromtimestamp(ts,timezone.utc).isoformat() if ts else None; low=title.lower(); category='Nyhet'
                if any(k in low for k in ('insider','primary insider','mandatory notification')):category='Insider'
                elif any(k in low for k in ('report','results','quarter','q1','q2','q3','q4','earnings')):category='Rapport'
                elif any(k in low for k in ('dividend','ex-dividend')):category='Utbytte'
                elif any(k in low for k in ('acqui','merger','contract','order','agreement')):category='Selskap'
                items.append({'ticker':ticker,'title':title,'publisher':publisher,'url':link,'published_at':dt,'category':category,'summary':title})
        except Exception as exc:return {'ticker':ticker,'items':[],'status':'unavailable','source':'Yahoo Finance search','error':str(exc)}
        return {'ticker':ticker,'items':items,'status':'live_news' if items else 'no_news','source':'Yahoo Finance search'}
    @app.get('/api/news/{ticker}/summary')
    def news_summary(ticker:str):
        d=stock_news(ticker,8); items=d.get('items') or []; counts={}
        for x in items:counts[x['category']]=counts.get(x['category'],0)+1
        return {'ticker':ticker.upper(),'headline_count':len(items),'categories':counts,'summary':(' · '.join(x['title'] for x in items[:3]) if items else 'Ingen nye offentlige nyheter funnet.'),'items':items}
