"""User-entered holdings portfolio with account-level ASK tax tracking."""
from datetime import datetime, timezone
from fastapi import HTTPException
from pydantic import BaseModel, Field
import extra_api
from database import connect, USING_POSTGRES
from providers import YahooProvider

ASK_TAX_RATE_2026 = 0.3784

def _now(): return datetime.now(timezone.utc).isoformat()
def _clean_text(value, fallback):
    text=' '.join(str(value or '').split()).strip(); return text or fallback

def _ensure_schema():
    conn=connect()
    holdings='''CREATE TABLE IF NOT EXISTS holdings (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ticker TEXT NOT NULL,shares DOUBLE PRECISION NOT NULL,average_cost DOUBLE PRECISION NOT NULL,broker TEXT NOT NULL DEFAULT 'Nordnet',account_type TEXT NOT NULL DEFAULT 'ASK',note TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(ticker,broker,account_type));''' if USING_POSTGRES else '''CREATE TABLE IF NOT EXISTS holdings (id INTEGER PRIMARY KEY AUTOINCREMENT,ticker TEXT NOT NULL,shares REAL NOT NULL,average_cost REAL NOT NULL,broker TEXT NOT NULL DEFAULT 'Nordnet',account_type TEXT NOT NULL DEFAULT 'ASK',note TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(ticker,broker,account_type));'''
    accounts='''CREATE TABLE IF NOT EXISTS holding_accounts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,broker TEXT NOT NULL,account_type TEXT NOT NULL,contributed_capital DOUBLE PRECISION NOT NULL DEFAULT 0,withdrawn DOUBLE PRECISION NOT NULL DEFAULT 0,unused_shielding DOUBLE PRECISION NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,UNIQUE(broker,account_type));''' if USING_POSTGRES else '''CREATE TABLE IF NOT EXISTS holding_accounts (id INTEGER PRIMARY KEY AUTOINCREMENT,broker TEXT NOT NULL,account_type TEXT NOT NULL,contributed_capital REAL NOT NULL DEFAULT 0,withdrawn REAL NOT NULL DEFAULT 0,unused_shielding REAL NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,UNIQUE(broker,account_type));'''
    try: conn.executescript(holdings+'\n'+accounts); conn.commit()
    finally: conn.close()

class HoldingIn(BaseModel):
    ticker:str=Field(min_length=1,max_length=20); shares:float=Field(gt=0,le=1_000_000_000); average_cost:float=Field(gt=0,le=1_000_000_000); broker:str=Field(default='Nordnet',min_length=1,max_length=60); account_type:str=Field(default='ASK',min_length=1,max_length=60); note:str|None=Field(default=None,max_length=240)
class AccountTaxIn(BaseModel):
    broker:str=Field(default='Nordnet',min_length=1,max_length=60); account_type:str=Field(default='ASK',min_length=1,max_length=60); contributed_capital:float=Field(ge=0,le=10_000_000_000); withdrawn:float=Field(ge=0,le=10_000_000_000); unused_shielding:float=Field(default=0,ge=0,le=10_000_000_000)

def _row_with_market(row,provider):
    item=dict(row); shares=float(item.get('shares') or 0); avg=float(item.get('average_cost') or 0); invested=shares*avg; price=None; source=None; err=None
    try:
        q=provider.quote(item['ticker']); price=float(q['price']) if q.get('price') is not None else None; source=q.get('source')
    except Exception as exc: err=str(exc)
    value=shares*price if price is not None else None; pnl=value-invested if value is not None else None
    item.update(invested=invested,current_price=price,market_value=value,unrealized_pnl=pnl,unrealized_pnl_pct=(pnl/invested*100 if pnl is not None and invested else None),quote_source=source,quote_error=err); return item

def _account_tax_rows():
    conn=connect()
    try: rows=conn.execute('SELECT * FROM holding_accounts ORDER BY broker,account_type').fetchall()
    finally: conn.close()
    out=[]
    for row in rows:
        x=dict(row); contributed=float(x.get('contributed_capital') or 0); withdrawn=float(x.get('withdrawn') or 0); shielding=float(x.get('unused_shielding') or 0); remaining=max(0,contributed-withdrawn); taxable=max(0,withdrawn-contributed-shielding) if str(x.get('account_type','')).upper()=='ASK' else None
        x.update(remaining_tax_free_capital=remaining,taxable_withdrawal=taxable,estimated_tax=(taxable*ASK_TAX_RATE_2026 if taxable is not None else None),tax_rate=(ASK_TAX_RATE_2026 if taxable is not None else None)); out.append(x)
    return out

def build_holdings_snapshot(provider=None):
    provider=provider or YahooProvider(); conn=connect()
    try: rows=conn.execute('SELECT * FROM holdings ORDER BY broker,account_type,ticker').fetchall()
    finally: conn.close()
    items=[_row_with_market(r,provider) for r in rows]; invested=sum(float(x.get('invested') or 0) for x in items); priced=[x for x in items if x.get('market_value') is not None]; value=sum(float(x['market_value']) for x in priced); priced_cost=sum(float(x.get('invested') or 0) for x in priced); pnl=value-priced_cost if priced else 0.0
    return {'items':items,'summary':{'position_count':len(items),'priced_count':len(priced),'invested':invested,'market_value':value,'unrealized_pnl':pnl,'unrealized_pnl_pct':pnl/priced_cost*100 if priced_cost else None},'accounts':_account_tax_rows(),'currency':'NOK','tax_status':'account_aware','tax_note':'ASK: innskutt kapital anses tatt ut først. Uttak over gjenværende innskudd og eventuell ubenyttet skjerming er skattepliktig. 2026-satsen for skattepliktig aksjeinntekt er 37,84 %. Tallene er estimater og bør kontrolleres mot megler/skattemelding.'}

def install():
    if getattr(extra_api,'_holdings_routes_v2',False): return
    original=extra_api.install
    def patched_install(app):
        original(app); _ensure_schema(); provider=YahooProvider()
        @app.get('/api/holdings')
        def holdings(): return build_holdings_snapshot(provider)
        @app.post('/api/holdings')
        def save_holding(payload:HoldingIn):
            ticker=payload.ticker.strip().upper(); broker=_clean_text(payload.broker,'Nordnet'); account=_clean_text(payload.account_type,'ASK'); note=_clean_text(payload.note,'') or None; now=_now(); conn=connect()
            try:
                existing=conn.execute('SELECT id FROM holdings WHERE ticker=? AND broker=? AND account_type=? LIMIT 1',(ticker,broker,account)).fetchone()
                if existing: conn.execute('UPDATE holdings SET shares=?,average_cost=?,note=?,updated_at=? WHERE id=?',(payload.shares,payload.average_cost,note,now,existing['id'])); hid=existing['id']
                else: hid=getattr(conn.execute('INSERT INTO holdings(ticker,shares,average_cost,broker,account_type,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',(ticker,payload.shares,payload.average_cost,broker,account,note,now,now)),'lastrowid',None)
                conn.commit()
            finally: conn.close()
            return {'status':'ok','id':hid,'portfolio':build_holdings_snapshot(provider)}
        @app.post('/api/holdings/account-tax')
        def save_account_tax(payload:AccountTaxIn):
            broker=_clean_text(payload.broker,'Nordnet'); account=_clean_text(payload.account_type,'ASK'); now=_now(); conn=connect()
            try:
                existing=conn.execute('SELECT id FROM holding_accounts WHERE broker=? AND account_type=? LIMIT 1',(broker,account)).fetchone()
                if existing: conn.execute('UPDATE holding_accounts SET contributed_capital=?,withdrawn=?,unused_shielding=?,updated_at=? WHERE id=?',(payload.contributed_capital,payload.withdrawn,payload.unused_shielding,now,existing['id']))
                else: conn.execute('INSERT INTO holding_accounts(broker,account_type,contributed_capital,withdrawn,unused_shielding,updated_at) VALUES(?,?,?,?,?,?)',(broker,account,payload.contributed_capital,payload.withdrawn,payload.unused_shielding,now))
                conn.commit()
            finally: conn.close()
            return {'status':'ok','portfolio':build_holdings_snapshot(provider)}
        @app.delete('/api/holdings/{holding_id}')
        def delete_holding(holding_id:int):
            conn=connect()
            try:
                row=conn.execute('SELECT id FROM holdings WHERE id=? LIMIT 1',(holding_id,)).fetchone()
                if not row: raise HTTPException(404,detail='Holding not found')
                conn.execute('DELETE FROM holdings WHERE id=?',(holding_id,)); conn.commit()
            finally: conn.close()
            return {'status':'ok','portfolio':build_holdings_snapshot(provider)}
    extra_api.install=patched_install; extra_api._holdings_routes_v2=True
install()
