"""Detailed purchase lots for positions in the Holdings view.

A holding remains one aggregate portfolio position, while this runtime stores any
number of dated purchase lots underneath it. Adding a new lot updates the holding's
total shares and weighted average cost atomically. Existing aggregate positions are
preserved by seeding a legacy lot the first time a new purchase is added.
"""

from datetime import date, datetime, timezone

from fastapi import HTTPException
from pydantic import BaseModel, Field

import extra_api
import holdings_routes
from database import connect, USING_POSTGRES


def _now():
    return datetime.now(timezone.utc).isoformat()


def _ensure_schema():
    conn = connect()
    schema = '''
    CREATE TABLE IF NOT EXISTS holding_purchase_lots (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      holding_id BIGINT NOT NULL,
      shares DOUBLE PRECISION NOT NULL,
      price_nok DOUBLE PRECISION NOT NULL,
      purchase_date TEXT,
      note TEXT,
      source TEXT NOT NULL DEFAULT 'manual',
      created_at TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_holding_purchase_lots_holding_date
      ON holding_purchase_lots(holding_id,purchase_date,id);
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS holding_purchase_lots (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      holding_id INTEGER NOT NULL,
      shares REAL NOT NULL,
      price_nok REAL NOT NULL,
      purchase_date TEXT,
      note TEXT,
      source TEXT NOT NULL DEFAULT 'manual',
      created_at TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_holding_purchase_lots_holding_date
      ON holding_purchase_lots(holding_id,purchase_date,id);
    '''
    try:
        conn.executescript(schema)
        conn.commit()
    finally:
        conn.close()


class PurchaseLotIn(BaseModel):
    purchase_date: date | None = None
    shares: float = Field(gt=0, le=1_000_000_000)
    price_nok: float = Field(gt=0, le=1_000_000_000)
    note: str | None = Field(default=None, max_length=240)


class InitializePurchaseIn(BaseModel):
    purchase_date: date | None = None
    note: str | None = Field(default=None, max_length=240)


def _clean_note(value):
    text = ' '.join(str(value or '').split()).strip()
    return text or None


def _date_text(value):
    return value.isoformat() if value is not None else None


def _holding_row(conn, holding_id):
    row = conn.execute('SELECT * FROM holdings WHERE id=? LIMIT 1', (int(holding_id),)).fetchone()
    if not row:
        raise HTTPException(404, detail='Holding not found')
    return dict(row)


def _lot_rows(conn, holding_id):
    rows = conn.execute(
        'SELECT * FROM holding_purchase_lots WHERE holding_id=? '
        'ORDER BY CASE WHEN purchase_date IS NULL THEN 0 ELSE 1 END, purchase_date ASC, id ASC',
        (int(holding_id),),
    ).fetchall()
    return [dict(row) for row in rows]


def _aggregate_lots(lots):
    shares = sum(float(x.get('shares') or 0) for x in lots or [])
    cost = sum(float(x.get('shares') or 0) * float(x.get('price_nok') or 0) for x in lots or [])
    return {
        'shares': shares,
        'cost_basis': cost,
        'average_cost': (cost / shares) if shares > 0 else None,
    }


def _sync_holding_from_lots(conn, holding_id):
    lots = _lot_rows(conn, holding_id)
    agg = _aggregate_lots(lots)
    if agg['shares'] > 0 and agg['average_cost'] is not None:
        conn.execute(
            'UPDATE holdings SET shares=?,average_cost=?,updated_at=? WHERE id=?',
            (agg['shares'], agg['average_cost'], _now(), int(holding_id)),
        )
    return agg


def _seed_legacy_lot(conn, holding):
    existing = conn.execute(
        'SELECT id FROM holding_purchase_lots WHERE holding_id=? LIMIT 1',
        (int(holding['id']),),
    ).fetchone()
    if existing:
        return False
    shares = float(holding.get('shares') or 0)
    price = float(holding.get('average_cost') or 0)
    if shares <= 0 or price <= 0:
        return False
    conn.execute(
        'INSERT INTO holding_purchase_lots(holding_id,shares,price_nok,purchase_date,note,source,created_at) '
        'VALUES(?,?,?,?,?,?,?)',
        (int(holding['id']), shares, price, None, 'Eksisterende beholdning før detaljert kjøpsoversikt', 'legacy_snapshot', _now()),
    )
    return True


def _lot_view(row, current_price):
    shares = float(row.get('shares') or 0)
    price = float(row.get('price_nok') or 0)
    cost = shares * price
    current_value = shares * float(current_price) if current_price is not None else None
    pnl = current_value - cost if current_value is not None else None
    pnl_pct = pnl / cost * 100 if pnl is not None and cost else None
    out = dict(row)
    out.update({
        'cost_basis': cost,
        'current_price': current_price,
        'current_value': current_value,
        'unrealized_pnl': pnl,
        'unrealized_pnl_pct': pnl_pct,
        'status': 'profit' if pnl is not None and pnl > 0 else 'loss' if pnl is not None and pnl < 0 else 'flat' if pnl is not None else 'unpriced',
        'is_legacy': row.get('source') == 'legacy_snapshot',
    })
    return out


def _lots_by_holding():
    conn = connect()
    try:
        rows = conn.execute(
            'SELECT * FROM holding_purchase_lots '
            'ORDER BY holding_id, CASE WHEN purchase_date IS NULL THEN 0 ELSE 1 END, purchase_date ASC, id ASC'
        ).fetchall()
    finally:
        conn.close()
    grouped = {}
    for row in rows:
        item = dict(row)
        grouped.setdefault(int(item['holding_id']), []).append(item)
    return grouped


_original_snapshot = holdings_routes.build_holdings_snapshot


def build_holdings_snapshot_with_purchase_lots(provider=None):
    snapshot = _original_snapshot(provider)
    grouped = _lots_by_holding()
    for item in snapshot.get('items') or []:
        holding_id = int(item.get('id') or 0)
        raw = grouped.get(holding_id, [])
        current_price = item.get('current_price')
        views = [_lot_view(row, current_price) for row in raw]
        agg = _aggregate_lots(raw)
        item['purchase_lots'] = views
        item['purchase_lot_count'] = len(views)
        item['purchase_summary'] = {
            **agg,
            'current_value': sum(float(x['current_value']) for x in views if x.get('current_value') is not None) if views and current_price is not None else None,
            'unrealized_pnl': sum(float(x['unrealized_pnl']) for x in views if x.get('unrealized_pnl') is not None) if views and current_price is not None else None,
            'has_detailed_lots': bool(views),
            'has_legacy_lot': any(x.get('is_legacy') for x in views),
        }
    return snapshot


def _replace_snapshot_route(app):
    return True


def install():
    if getattr(holdings_routes, '_purchase_lots_runtime_v1', False):
        return
    _ensure_schema()
    holdings_routes.build_holdings_snapshot = build_holdings_snapshot_with_purchase_lots
    holdings_routes._purchase_lots_runtime_v1 = True

    original_install = extra_api.install

    def patched_install(app):
        original_install(app)
        _replace_snapshot_route(app)

        @app.post('/api/holdings/{holding_id}/purchases')
        def add_purchase(holding_id: int, payload: PurchaseLotIn):
            conn = connect()
            try:
                holding = _holding_row(conn, holding_id)
                _seed_legacy_lot(conn, holding)
                cursor = conn.execute(
                    'INSERT INTO holding_purchase_lots(holding_id,shares,price_nok,purchase_date,note,source,created_at) '
                    'VALUES(?,?,?,?,?,?,?)',
                    (holding_id, float(payload.shares), float(payload.price_nok), _date_text(payload.purchase_date), _clean_note(payload.note), 'manual', _now()),
                )
                _sync_holding_from_lots(conn, holding_id)
                conn.commit()
                purchase_id = getattr(cursor, 'lastrowid', None)
            finally:
                conn.close()
            return {'status': 'ok', 'id': purchase_id}

        @app.post('/api/holdings/{holding_id}/purchases/initialize')
        def initialize_existing_purchase(holding_id: int, payload: InitializePurchaseIn):
            conn = connect()
            try:
                holding = _holding_row(conn, holding_id)
                existing = _lot_rows(conn, holding_id)
                if existing:
                    raise HTTPException(409, detail='Detailed purchase lots already exist for this holding')
                shares = float(holding.get('shares') or 0)
                price = float(holding.get('average_cost') or 0)
                if shares <= 0 or price <= 0:
                    raise HTTPException(400, detail='Holding does not have a valid aggregate position')
                cursor = conn.execute(
                    'INSERT INTO holding_purchase_lots(holding_id,shares,price_nok,purchase_date,note,source,created_at) '
                    'VALUES(?,?,?,?,?,?,?)',
                    (holding_id, shares, price, _date_text(payload.purchase_date), _clean_note(payload.note), 'manual_initial', _now()),
                )
                conn.commit()
                purchase_id = getattr(cursor, 'lastrowid', None)
            finally:
                conn.close()
            return {'status': 'ok', 'id': purchase_id}

        @app.delete('/api/holding-purchases/{purchase_id}')
        def delete_purchase(purchase_id: int):
            conn = connect()
            try:
                row = conn.execute('SELECT * FROM holding_purchase_lots WHERE id=? LIMIT 1', (purchase_id,)).fetchone()
                if not row:
                    raise HTTPException(404, detail='Purchase not found')
                holding_id = int(row['holding_id'])
                conn.execute('DELETE FROM holding_purchase_lots WHERE id=?', (purchase_id,))
                remaining = _lot_rows(conn, holding_id)
                if remaining:
                    _sync_holding_from_lots(conn, holding_id)
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok'}

    extra_api.install = patched_install


install()