"""Canonical user-entered holdings portfolio for NordicSignal.

This is deliberately separate from paper trading. Users can mirror positions they
hold at Nordnet or another broker without creating simulated trades. Tax logic is
not applied here; this first layer establishes a clean holdings ledger and live
mark-to-market values that later tax/account rules can build on.
"""

from datetime import datetime, timezone

from fastapi import HTTPException
from pydantic import BaseModel, Field

import extra_api
from database import connect, USING_POSTGRES
from providers import YahooProvider


def _now():
    return datetime.now(timezone.utc).isoformat()


def _ensure_schema():
    conn = connect()
    schema = '''
    CREATE TABLE IF NOT EXISTS holdings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ticker TEXT NOT NULL,
      shares DOUBLE PRECISION NOT NULL,
      average_cost DOUBLE PRECISION NOT NULL,
      broker TEXT NOT NULL DEFAULT 'Nordnet',
      account_type TEXT NOT NULL DEFAULT 'ASK',
      note TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(ticker, broker, account_type)
    );
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS holdings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ticker TEXT NOT NULL,
      shares REAL NOT NULL,
      average_cost REAL NOT NULL,
      broker TEXT NOT NULL DEFAULT 'Nordnet',
      account_type TEXT NOT NULL DEFAULT 'ASK',
      note TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(ticker, broker, account_type)
    );
    '''
    try:
        conn.executescript(schema)
        conn.commit()
    finally:
        conn.close()


class HoldingIn(BaseModel):
    ticker: str = Field(min_length=1, max_length=20)
    shares: float = Field(gt=0, le=1_000_000_000)
    average_cost: float = Field(gt=0, le=1_000_000_000)
    broker: str = Field(default='Nordnet', min_length=1, max_length=60)
    account_type: str = Field(default='ASK', min_length=1, max_length=60)
    note: str | None = Field(default=None, max_length=240)


def _clean_text(value, fallback):
    text = ' '.join(str(value or '').split()).strip()
    return text or fallback


def _row_with_market(row, provider):
    item = dict(row)
    shares = float(item.get('shares') or 0)
    average_cost = float(item.get('average_cost') or 0)
    invested = shares * average_cost
    price = None
    quote_source = None
    quote_error = None
    try:
        quote = provider.quote(item['ticker'])
        if quote.get('price') is not None:
            price = float(quote['price'])
        quote_source = quote.get('source')
    except Exception as exc:
        quote_error = str(exc)
    market_value = shares * price if price is not None else None
    pnl = market_value - invested if market_value is not None else None
    pnl_pct = pnl / invested * 100 if pnl is not None and invested else None
    item.update({
        'invested': invested,
        'current_price': price,
        'market_value': market_value,
        'unrealized_pnl': pnl,
        'unrealized_pnl_pct': pnl_pct,
        'quote_source': quote_source,
        'quote_error': quote_error,
    })
    return item


def build_holdings_snapshot(provider=None):
    provider = provider or YahooProvider()
    conn = connect()
    try:
        rows = conn.execute('SELECT * FROM holdings ORDER BY broker, account_type, ticker').fetchall()
    finally:
        conn.close()
    items = [_row_with_market(row, provider) for row in rows]
    invested = sum(float(x.get('invested') or 0) for x in items)
    priced = [x for x in items if x.get('market_value') is not None]
    market_value = sum(float(x['market_value']) for x in priced)
    priced_invested = sum(float(x.get('invested') or 0) for x in priced)
    pnl = market_value - priced_invested if priced else 0.0
    return {
        'items': items,
        'summary': {
            'position_count': len(items),
            'priced_count': len(priced),
            'invested': invested,
            'market_value': market_value,
            'unrealized_pnl': pnl,
            'unrealized_pnl_pct': (pnl / priced_invested * 100) if priced_invested else None,
        },
        'currency': 'NOK',
        'tax_status': 'not_calculated',
        'tax_note': 'Skatt beregnes ikke i beholdningslisten ennå. Skattemodulen bygges separat med kontotype og gjeldende norske skatteregler.',
    }


def install():
    if getattr(extra_api, '_holdings_routes_v1', False):
        return
    original = extra_api.install

    def patched_install(app):
        original(app)
        _ensure_schema()
        provider = YahooProvider()

        @app.get('/api/holdings')
        def holdings():
            return build_holdings_snapshot(provider)

        @app.post('/api/holdings')
        def save_holding(payload: HoldingIn):
            ticker = payload.ticker.strip().upper()
            broker = _clean_text(payload.broker, 'Nordnet')
            account_type = _clean_text(payload.account_type, 'ASK')
            note = _clean_text(payload.note, '') or None
            now = _now()
            conn = connect()
            try:
                existing = conn.execute(
                    'SELECT id FROM holdings WHERE ticker=? AND broker=? AND account_type=? LIMIT 1',
                    (ticker, broker, account_type),
                ).fetchone()
                if existing:
                    conn.execute(
                        'UPDATE holdings SET shares=?,average_cost=?,note=?,updated_at=? WHERE id=?',
                        (payload.shares, payload.average_cost, note, now, existing['id']),
                    )
                    holding_id = existing['id']
                else:
                    cursor = conn.execute(
                        'INSERT INTO holdings(ticker,shares,average_cost,broker,account_type,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',
                        (ticker, payload.shares, payload.average_cost, broker, account_type, note, now, now),
                    )
                    holding_id = getattr(cursor, 'lastrowid', None)
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'id': holding_id, 'portfolio': build_holdings_snapshot(provider)}

        @app.delete('/api/holdings/{holding_id}')
        def delete_holding(holding_id: int):
            conn = connect()
            try:
                row = conn.execute('SELECT id FROM holdings WHERE id=? LIMIT 1', (holding_id,)).fetchone()
                if not row:
                    raise HTTPException(404, detail='Holding not found')
                conn.execute('DELETE FROM holdings WHERE id=?', (holding_id,))
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'portfolio': build_holdings_snapshot(provider)}

    extra_api.install = patched_install
    extra_api._holdings_routes_v1 = True


install()
