"""User-entered holdings portfolio, transaction ledger and account-aware tax tracking.

Holdings mirror real broker positions and stay separate from paper trading. ASK tax
tracking is account-level: deposits are treated as withdrawn first, while internal
buys/sells/dividends on ASK do not themselves create a taxable event. The ledger
therefore records cash flows separately from the current position snapshot.
"""
from datetime import date, datetime, timezone
from typing import Literal

from fastapi import HTTPException
from pydantic import BaseModel, Field, model_validator

import extra_api
from database import connect, USING_POSTGRES
from providers import YahooProvider

ASK_TAX_RATE_2026 = 0.3784
TX_TYPES = {'deposit', 'withdrawal', 'buy', 'sell', 'dividend'}


def _now():
    return datetime.now(timezone.utc).isoformat()


def _clean_text(value, fallback):
    text = ' '.join(str(value or '').split()).strip()
    return text or fallback


def _ensure_schema():
    conn = connect()
    holdings = '''
    CREATE TABLE IF NOT EXISTS holdings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ticker TEXT NOT NULL,
      shares DOUBLE PRECISION NOT NULL,
      average_cost DOUBLE PRECISION NOT NULL,
      broker TEXT NOT NULL DEFAULT 'Nordnet',
      account_type TEXT NOT NULL DEFAULT 'ASK',
      note TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(ticker, broker, account_type)
    );
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS holdings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ticker TEXT NOT NULL,
      shares REAL NOT NULL,
      average_cost REAL NOT NULL,
      broker TEXT NOT NULL DEFAULT 'Nordnet',
      account_type TEXT NOT NULL DEFAULT 'ASK',
      note TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(ticker, broker, account_type)
    );
    '''
    accounts = '''
    CREATE TABLE IF NOT EXISTS holding_accounts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      broker TEXT NOT NULL,
      account_type TEXT NOT NULL,
      contributed_capital DOUBLE PRECISION NOT NULL DEFAULT 0,
      withdrawn DOUBLE PRECISION NOT NULL DEFAULT 0,
      unused_shielding DOUBLE PRECISION NOT NULL DEFAULT 0,
      updated_at TEXT NOT NULL,
      UNIQUE(broker, account_type)
    );
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS holding_accounts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      broker TEXT NOT NULL,
      account_type TEXT NOT NULL,
      contributed_capital REAL NOT NULL DEFAULT 0,
      withdrawn REAL NOT NULL DEFAULT 0,
      unused_shielding REAL NOT NULL DEFAULT 0,
      updated_at TEXT NOT NULL,
      UNIQUE(broker, account_type)
    );
    '''
    transactions = '''
    CREATE TABLE IF NOT EXISTS holding_transactions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      broker TEXT NOT NULL,
      account_type TEXT NOT NULL,
      transaction_type TEXT NOT NULL,
      ticker TEXT,
      shares DOUBLE PRECISION,
      price DOUBLE PRECISION,
      amount DOUBLE PRECISION NOT NULL,
      transaction_date TEXT NOT NULL,
      note TEXT,
      created_at TEXT NOT NULL
    );
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS holding_transactions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      broker TEXT NOT NULL,
      account_type TEXT NOT NULL,
      transaction_type TEXT NOT NULL,
      ticker TEXT,
      shares REAL,
      price REAL,
      amount REAL NOT NULL,
      transaction_date TEXT NOT NULL,
      note TEXT,
      created_at TEXT NOT NULL
    );
    '''
    try:
        conn.executescript(holdings + '\n' + accounts + '\n' + transactions)
        conn.commit()
    finally:
        conn.close()


class HoldingIn(BaseModel):
    ticker: str = Field(min_length=1, max_length=20)
    shares: float = Field(gt=0, le=1_000_000_000)
    average_cost: float = Field(gt=0, le=1_000_000_000)
    broker: str = Field(default='Nordnet', min_length=1, max_length=60)
    account_type: str = Field(default='ASK', min_length=1, max_length=60)
    note: str | None = Field(default=None, max_length=240)


class AccountTaxIn(BaseModel):
    broker: str = Field(default='Nordnet', min_length=1, max_length=60)
    account_type: str = Field(default='ASK', min_length=1, max_length=60)
    contributed_capital: float = Field(ge=0, le=10_000_000_000)
    withdrawn: float = Field(ge=0, le=10_000_000_000)
    unused_shielding: float = Field(default=0, ge=0, le=10_000_000_000)


class HoldingTransactionIn(BaseModel):
    broker: str = Field(default='Nordnet', min_length=1, max_length=60)
    account_type: str = Field(default='ASK', min_length=1, max_length=60)
    transaction_type: Literal['deposit', 'withdrawal', 'buy', 'sell', 'dividend']
    ticker: str | None = Field(default=None, max_length=20)
    shares: float | None = Field(default=None, gt=0, le=1_000_000_000)
    price: float | None = Field(default=None, gt=0, le=1_000_000_000)
    amount: float | None = Field(default=None, gt=0, le=10_000_000_000)
    transaction_date: date = Field(default_factory=date.today)
    note: str | None = Field(default=None, max_length=240)

    @model_validator(mode='after')
    def validate_transaction(self):
        if self.transaction_type in {'buy', 'sell'}:
            if not self.ticker:
                raise ValueError('Ticker is required for buy/sell transactions')
            if self.amount is None and (self.shares is None or self.price is None):
                raise ValueError('Buy/sell requires amount, or both shares and price')
        elif self.transaction_type == 'dividend':
            if not self.ticker:
                raise ValueError('Ticker is required for dividend transactions')
            if self.amount is None:
                raise ValueError('Dividend amount is required')
        elif self.amount is None:
            raise ValueError('Amount is required for deposit/withdrawal')
        return self


def _row_with_market(row, provider):
    item = dict(row)
    shares = float(item.get('shares') or 0)
    average_cost = float(item.get('average_cost') or 0)
    invested = shares * average_cost
    price = None
    quote_source = None
    quote_error = None
    try:
        quote = provider.quote(item['ticker'])
        if quote.get('price') is not None:
            price = float(quote['price'])
        quote_source = quote.get('source')
    except Exception as exc:
        quote_error = str(exc)
    market_value = shares * price if price is not None else None
    pnl = market_value - invested if market_value is not None else None
    pnl_pct = pnl / invested * 100 if pnl is not None and invested else None
    item.update({
        'invested': invested,
        'current_price': price,
        'market_value': market_value,
        'unrealized_pnl': pnl,
        'unrealized_pnl_pct': pnl_pct,
        'quote_source': quote_source,
        'quote_error': quote_error,
    })
    return item


def _transaction_rows(limit=250):
    conn = connect()
    try:
        rows = conn.execute(
            'SELECT * FROM holding_transactions ORDER BY transaction_date DESC, id DESC LIMIT ?',
            (max(1, min(int(limit), 1000)),),
        ).fetchall()
    finally:
        conn.close()
    return [dict(row) for row in rows]


def _transaction_totals():
    conn = connect()
    try:
        rows = conn.execute(
            "SELECT broker,account_type,transaction_type,SUM(amount) AS total FROM holding_transactions GROUP BY broker,account_type,transaction_type"
        ).fetchall()
    finally:
        conn.close()
    totals = {}
    for row in rows:
        key = (row['broker'], row['account_type'])
        totals.setdefault(key, {})[row['transaction_type']] = float(row['total'] or 0)
    return totals


def _ask_tax_summary(contributed, withdrawn, shielding):
    contributed = max(0.0, float(contributed or 0))
    withdrawn = max(0.0, float(withdrawn or 0))
    shielding = max(0.0, float(shielding or 0))
    excess = max(0.0, withdrawn - contributed)
    shielding_used = min(shielding, excess)
    taxable = max(0.0, excess - shielding_used)
    return {
        'remaining_tax_free_capital': max(0.0, contributed - withdrawn),
        'withdrawal_above_contributions': excess,
        'shielding_used': shielding_used,
        'remaining_shielding': max(0.0, shielding - shielding_used),
        'taxable_withdrawal': taxable,
        'estimated_tax': taxable * ASK_TAX_RATE_2026,
        'tax_rate': ASK_TAX_RATE_2026,
    }


def _account_tax_rows():
    tx_totals = _transaction_totals()
    conn = connect()
    try:
        rows = conn.execute('SELECT * FROM holding_accounts ORDER BY broker,account_type').fetchall()
    finally:
        conn.close()
    accounts = {(row['broker'], row['account_type']): dict(row) for row in rows}
    for key in tx_totals:
        accounts.setdefault(key, {
            'broker': key[0], 'account_type': key[1], 'contributed_capital': 0,
            'withdrawn': 0, 'unused_shielding': 0, 'updated_at': None,
        })
    out = []
    for key in sorted(accounts):
        x = accounts[key]
        tx = tx_totals.get(key, {})
        opening_contributed = float(x.get('contributed_capital') or 0)
        opening_withdrawn = float(x.get('withdrawn') or 0)
        deposits = float(tx.get('deposit') or 0)
        withdrawals = float(tx.get('withdrawal') or 0)
        shielding = float(x.get('unused_shielding') or 0)
        total_contributed = opening_contributed + deposits
        total_withdrawn = opening_withdrawn + withdrawals
        is_ask = str(x.get('account_type', '')).strip().upper() == 'ASK'
        x.update({
            'opening_contributed_capital': opening_contributed,
            'opening_withdrawn': opening_withdrawn,
            'ledger_deposits': deposits,
            'ledger_withdrawals': withdrawals,
            'ledger_buys': float(tx.get('buy') or 0),
            'ledger_sells': float(tx.get('sell') or 0),
            'ledger_dividends': float(tx.get('dividend') or 0),
            'total_contributed_capital': total_contributed,
            'total_withdrawn': total_withdrawn,
            'tax_model': 'ASK' if is_ask else 'not_calculated',
        })
        if is_ask:
            x.update(_ask_tax_summary(total_contributed, total_withdrawn, shielding))
        else:
            x.update({
                'remaining_tax_free_capital': None,
                'withdrawal_above_contributions': None,
                'shielding_used': None,
                'remaining_shielding': None,
                'taxable_withdrawal': None,
                'estimated_tax': None,
                'tax_rate': None,
            })
        out.append(x)
    return out


def build_holdings_snapshot(provider=None):
    provider = provider or YahooProvider()
    conn = connect()
    try:
        rows = conn.execute(
            'SELECT h.*,s.name AS company_name,s.sector AS sector FROM holdings h LEFT JOIN stocks s ON s.ticker=h.ticker ORDER BY h.broker,h.account_type,h.ticker'
        ).fetchall()
    finally:
        conn.close()
    items = [_row_with_market(row, provider) for row in rows]
    invested = sum(float(x.get('invested') or 0) for x in items)
    priced = [x for x in items if x.get('market_value') is not None]
    market_value = sum(float(x['market_value']) for x in priced)
    priced_invested = sum(float(x.get('invested') or 0) for x in priced)
    pnl = market_value - priced_invested if priced else 0.0
    for item in items:
        item['portfolio_weight_pct'] = (
            float(item['market_value']) / market_value * 100
            if item.get('market_value') is not None and market_value > 0 else None
        )
    sector_map = {}
    for item in priced:
        sector = item.get('sector') or 'Ukjent'
        bucket = sector_map.setdefault(sector, {'sector': sector, 'market_value': 0.0, 'positions': 0})
        bucket['market_value'] += float(item['market_value'])
        bucket['positions'] += 1
    sectors = sorted(sector_map.values(), key=lambda x: x['market_value'], reverse=True)
    for sector in sectors:
        sector['weight_pct'] = sector['market_value'] / market_value * 100 if market_value else None
    transactions = _transaction_rows(250)
    tx_summary = {
        'transaction_count': len(transactions),
        'deposits': sum(float(x['amount']) for x in transactions if x['transaction_type'] == 'deposit'),
        'withdrawals': sum(float(x['amount']) for x in transactions if x['transaction_type'] == 'withdrawal'),
        'dividends': sum(float(x['amount']) for x in transactions if x['transaction_type'] == 'dividend'),
        'buys': sum(float(x['amount']) for x in transactions if x['transaction_type'] == 'buy'),
        'sells': sum(float(x['amount']) for x in transactions if x['transaction_type'] == 'sell'),
    }
    return {
        'items': items,
        'summary': {
            'position_count': len(items),
            'priced_count': len(priced),
            'invested': invested,
            'market_value': market_value,
            'unrealized_pnl': pnl,
            'unrealized_pnl_pct': (pnl / priced_invested * 100) if priced_invested else None,
        },
        'sectors': sectors,
        'transactions': transactions,
        'transaction_summary': tx_summary,
        'accounts': _account_tax_rows(),
        'currency': 'NOK',
        'tax_status': 'account_aware',
        'tax_note': (
            'ASK: innskudd anses tatt ut først. Kjøp, salg og utbytte inne på ASK utløser ikke skatt i seg selv; '
            'uttak utover samlet innskudd og tilgjengelig skjerming kan bli skattepliktig. '
            'Skattepliktige ASK-uttak i 2026 er estimert med 37,84 %. For andre kontotyper vises ingen automatisk skatt ennå.'
        ),
    }


def install():
    if getattr(extra_api, '_holdings_routes_v3', False):
        return
    original = extra_api.install

    def patched_install(app):
        original(app)
        _ensure_schema()
        provider = YahooProvider()

        @app.get('/api/holdings')
        def holdings():
            return build_holdings_snapshot(provider)

        @app.post('/api/holdings')
        def save_holding(payload: HoldingIn):
            ticker = payload.ticker.strip().upper()
            broker = _clean_text(payload.broker, 'Nordnet')
            account = _clean_text(payload.account_type, 'ASK')
            note = _clean_text(payload.note, '') or None
            now = _now()
            conn = connect()
            try:
                existing = conn.execute(
                    'SELECT id FROM holdings WHERE ticker=? AND broker=? AND account_type=? LIMIT 1',
                    (ticker, broker, account),
                ).fetchone()
                if existing:
                    conn.execute(
                        'UPDATE holdings SET shares=?,average_cost=?,note=?,updated_at=? WHERE id=?',
                        (payload.shares, payload.average_cost, note, now, existing['id']),
                    )
                    holding_id = existing['id']
                else:
                    cursor = conn.execute(
                        'INSERT INTO holdings(ticker,shares,average_cost,broker,account_type,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',
                        (ticker, payload.shares, payload.average_cost, broker, account, note, now, now),
                    )
                    holding_id = getattr(cursor, 'lastrowid', None)
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'id': holding_id, 'portfolio': build_holdings_snapshot(provider)}

        @app.post('/api/holdings/account-tax')
        def save_account_tax(payload: AccountTaxIn):
            broker = _clean_text(payload.broker, 'Nordnet')
            account = _clean_text(payload.account_type, 'ASK')
            now = _now()
            conn = connect()
            try:
                existing = conn.execute(
                    'SELECT id FROM holding_accounts WHERE broker=? AND account_type=? LIMIT 1',
                    (broker, account),
                ).fetchone()
                if existing:
                    conn.execute(
                        'UPDATE holding_accounts SET contributed_capital=?,withdrawn=?,unused_shielding=?,updated_at=? WHERE id=?',
                        (payload.contributed_capital, payload.withdrawn, payload.unused_shielding, now, existing['id']),
                    )
                else:
                    conn.execute(
                        'INSERT INTO holding_accounts(broker,account_type,contributed_capital,withdrawn,unused_shielding,updated_at) VALUES(?,?,?,?,?,?)',
                        (broker, account, payload.contributed_capital, payload.withdrawn, payload.unused_shielding, now),
                    )
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'portfolio': build_holdings_snapshot(provider)}

        @app.post('/api/holdings/transactions')
        def add_transaction(payload: HoldingTransactionIn):
            broker = _clean_text(payload.broker, 'Nordnet')
            account = _clean_text(payload.account_type, 'ASK')
            ticker = payload.ticker.strip().upper() if payload.ticker else None
            shares = float(payload.shares) if payload.shares is not None else None
            price = float(payload.price) if payload.price is not None else None
            amount = float(payload.amount) if payload.amount is not None else float(shares * price)
            note = _clean_text(payload.note, '') or None
            conn = connect()
            try:
                cursor = conn.execute(
                    'INSERT INTO holding_transactions(broker,account_type,transaction_type,ticker,shares,price,amount,transaction_date,note,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',
                    (broker, account, payload.transaction_type, ticker, shares, price, amount, payload.transaction_date.isoformat(), note, _now()),
                )
                transaction_id = getattr(cursor, 'lastrowid', None)
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'id': transaction_id, 'portfolio': build_holdings_snapshot(provider)}

        @app.delete('/api/holdings/transactions/{transaction_id}')
        def delete_transaction(transaction_id: int):
            conn = connect()
            try:
                row = conn.execute('SELECT id FROM holding_transactions WHERE id=? LIMIT 1', (transaction_id,)).fetchone()
                if not row:
                    raise HTTPException(404, detail='Transaction not found')
                conn.execute('DELETE FROM holding_transactions WHERE id=?', (transaction_id,))
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'portfolio': build_holdings_snapshot(provider)}

        @app.delete('/api/holdings/{holding_id}')
        def delete_holding(holding_id: int):
            conn = connect()
            try:
                row = conn.execute('SELECT id FROM holdings WHERE id=? LIMIT 1', (holding_id,)).fetchone()
                if not row:
                    raise HTTPException(404, detail='Holding not found')
                conn.execute('DELETE FROM holdings WHERE id=?', (holding_id,))
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'portfolio': build_holdings_snapshot(provider)}

    extra_api.install = patched_install
    extra_api._holdings_routes_v3 = True


install()
