"""Persistence, Latest Signals integration and forward tracking for Early Opportunity.

This runtime keeps the opportunity model isolated from the aggregate stock score.
It records material opportunity-state transitions, exposes them in Latest Signals,
and settles 5/10/20/60 trading-day forward returns as observations mature.
"""
from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
import json
import threading
import time

import extra_api
from database import connect, USING_POSTGRES
import opportunity_confluence_runtime as opportunity
from providers import YahooProvider
import signal_events_runtime

HORIZONS = (5, 10, 20, 60)
SCAN_INTERVAL_SECONDS = 30 * 60
SCAN_WORKERS = 2
TRACKED_LABELS = {"WATCH_CONFLUENCE", "EARLY_OPPORTUNITY", "EARLY_OPPORTUNITY_HIGH"}

_SCAN_LOCK = threading.Lock()
_SCAN_RUNNING = False
_LAST_SCAN_AT = 0.0


def _now():
    return datetime.now(timezone.utc).isoformat()


def _ensure_schema():
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn = connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS opportunity_state (
          ticker TEXT PRIMARY KEY,
          label TEXT NOT NULL,
          score DOUBLE PRECISION,
          payload TEXT NOT NULL,
          observed_at TEXT NOT NULL,
          updated_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS opportunity_events (
          id {identity},
          ticker TEXT NOT NULL,
          name TEXT NOT NULL,
          previous_label TEXT,
          label TEXT NOT NULL,
          score DOUBLE PRECISION,
          entry_price DOUBLE PRECISION,
          reversal_score DOUBLE PRECISION,
          volume_ratio DOUBLE PRECISION,
          insider_label TEXT,
          independent_buyers INTEGER,
          buy_value_nok DOUBLE PRECISION,
          payload TEXT NOT NULL,
          observed_at TEXT NOT NULL,
          created_at TEXT NOT NULL,
          event_key TEXT NOT NULL,
          UNIQUE(ticker,event_key)
        );
        CREATE TABLE IF NOT EXISTS opportunity_forward_returns (
          event_id BIGINT NOT NULL,
          horizon_days INTEGER NOT NULL,
          target_date TEXT,
          target_price DOUBLE PRECISION,
          return_pct DOUBLE PRECISION,
          settled_at TEXT NOT NULL,
          PRIMARY KEY(event_id,horizon_days)
        );
        """)
        conn.commit()
    finally:
        conn.close()


def _state(ticker):
    conn = connect()
    try:
        row = conn.execute("SELECT * FROM opportunity_state WHERE ticker=?", (ticker,)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def _set_state(ticker, result):
    opp = result.get("opportunity") or {}
    label = str(opp.get("label") or "NO_OPPORTUNITY")
    payload = json.dumps(result, ensure_ascii=False, separators=(",", ":"), default=str)
    observed_at = str(result.get("generated_at") or _now())
    conn = connect()
    try:
        existing = conn.execute("SELECT ticker FROM opportunity_state WHERE ticker=?", (ticker,)).fetchone()
        values = (label, opp.get("score"), payload, observed_at, _now(), ticker)
        if existing:
            conn.execute("UPDATE opportunity_state SET label=?,score=?,payload=?,observed_at=?,updated_at=? WHERE ticker=?", values)
        else:
            conn.execute("INSERT INTO opportunity_state(label,score,payload,observed_at,updated_at,ticker) VALUES(?,?,?,?,?,?)", values)
        conn.commit()
    finally:
        conn.close()


def _entry_price(result):
    reversal = result.get("reversal") or {}
    metrics = reversal.get("metrics") or {}
    for key in ("close", "current", "price"):
        try:
            value = float(metrics.get(key))
            if value > 0:
                return value
        except (TypeError, ValueError):
            pass
    return None


def record_opportunity(result, name=None):
    ticker = str(result.get("ticker") or "").upper().replace(".OL", "")
    if not ticker or result.get("status") != "ok":
        return {"emitted": False, "reason": "invalid_result"}
    opp = result.get("opportunity") or {}
    label = str(opp.get("label") or "NO_OPPORTUNITY")
    previous = _state(ticker)
    previous_label = str(previous.get("label") or "NO_OPPORTUNITY") if previous else None
    emitted = False

    if previous is not None and label != previous_label and label in TRACKED_LABELS:
        components = opp.get("components") or {}
        observed_at = str(result.get("generated_at") or _now())
        event_key = f"{observed_at[:10]}:{previous_label}->{label}"
        payload = json.dumps(result, ensure_ascii=False, separators=(",", ":"), default=str)
        conn = connect()
        try:
            cur = conn.execute(
                "INSERT INTO opportunity_events(ticker,name,previous_label,label,score,entry_price,reversal_score,volume_ratio,insider_label,independent_buyers,buy_value_nok,payload,observed_at,created_at,event_key) "
                "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(ticker,event_key) DO NOTHING",
                (
                    ticker, name or ticker, previous_label, label, opp.get("score"), _entry_price(result),
                    components.get("reversal_score"), components.get("volume_ratio"), components.get("insider_label"),
                    components.get("independent_buyers"), components.get("buy_value_nok"), payload, observed_at, _now(), event_key,
                ),
            )
            conn.commit()
            emitted = bool(getattr(cur, "rowcount", 0))
        finally:
            conn.close()
    _set_state(ticker, result)
    return {"emitted": emitted, "previous_label": previous_label, "label": label}


def _history(provider, ticker):
    rows = provider.historical(ticker, "1y") or []
    valid = []
    for row in rows:
        try:
            close = float(row.get("close"))
        except (TypeError, ValueError, AttributeError):
            continue
        date = str(row.get("date") or "")[:10]
        if close > 0 and date:
            valid.append({"date": date, "close": close})
    valid.sort(key=lambda x: x["date"])
    return valid


def settle_forward_returns(ticker, rows=None):
    ticker = str(ticker or "").upper().replace(".OL", "")
    if not ticker:
        return 0
    rows = rows if rows is not None else _history(YahooProvider(), ticker)
    if not rows:
        return 0
    conn = connect()
    try:
        events = [dict(x) for x in conn.execute(
            "SELECT * FROM opportunity_events WHERE ticker=? ORDER BY id", (ticker,)
        ).fetchall()]
        settled = 0
        for event in events:
            day = str(event.get("observed_at") or "")[:10]
            start_idx = next((i for i, row in enumerate(rows) if row["date"] >= day), None)
            if start_idx is None:
                continue
            entry = event.get("entry_price")
            if entry is None:
                entry = rows[start_idx]["close"]
            try:
                entry = float(entry)
            except (TypeError, ValueError):
                continue
            for horizon in HORIZONS:
                exists = conn.execute(
                    "SELECT event_id FROM opportunity_forward_returns WHERE event_id=? AND horizon_days=?",
                    (event["id"], horizon),
                ).fetchone()
                if exists or start_idx + horizon >= len(rows):
                    continue
                target = rows[start_idx + horizon]
                ret = ((float(target["close"]) / entry) - 1.0) * 100.0 if entry else None
                conn.execute(
                    "INSERT INTO opportunity_forward_returns(event_id,horizon_days,target_date,target_price,return_pct,settled_at) VALUES(?,?,?,?,?,?)",
                    (event["id"], horizon, target["date"], target["close"], ret, _now()),
                )
                settled += 1
        conn.commit()
        return settled
    finally:
        conn.close()


def _event_items(limit=30):
    conn = connect()
    try:
        rows = conn.execute(
            "SELECT oe.*,s.sector FROM opportunity_events oe LEFT JOIN stocks s ON s.ticker=oe.ticker "
            "ORDER BY oe.created_at DESC,oe.id DESC LIMIT ?", (max(1, min(int(limit or 30), 50)),)
        ).fetchall()
    finally:
        conn.close()
    items = []
    for raw in rows:
        x = dict(raw)
        strength = "strong" if x.get("label") == "EARLY_OPPORTUNITY_HIGH" else "watch"
        detail = f"Reversal {x.get('reversal_score') or 0:.0f} · volum {x.get('volume_ratio') or 0:.1f}× · insider {x.get('insider_label') or 'NONE'}"
        items.append({
            "ticker": x.get("ticker"), "symbol": x.get("ticker"), "name": x.get("name") or x.get("ticker"),
            "sector": x.get("sector"), "asset_class": "Aksjer", "event_type": "early_opportunity",
            "signal": "Strong" if strength == "strong" else "Watch", "strength": strength,
            "event": str(x.get("label") or "").replace("_", " ").title(), "detail": detail,
            "opportunity_score": x.get("score"), "reversal_score": x.get("reversal_score"),
            "volume_ratio": x.get("volume_ratio"), "insider_label": x.get("insider_label"),
            "independent_buyers": x.get("independent_buyers"), "buy_value_nok": x.get("buy_value_nok"),
            "updated_at": x.get("created_at"), "observed_at": x.get("observed_at"),
            "score_source": "opportunity_v1", "score": x.get("score"), "score_delta": 0.0,
        })
    return items


def _scan_one(row):
    result = opportunity.live_opportunity(row["ticker"])
    record = record_opportunity(result, row.get("name") or row["ticker"])
    try:
        settle_forward_returns(row["ticker"])
    except Exception:
        pass
    return record


def _run_scan():
    global _SCAN_RUNNING
    conn = None
    try:
        conn = connect()
        rows = [dict(x) for x in conn.execute("SELECT ticker,name FROM stocks WHERE active=1 ORDER BY ticker").fetchall()]
    except Exception:
        rows = []
    finally:
        if conn is not None:
            conn.close()
    try:
        with ThreadPoolExecutor(max_workers=SCAN_WORKERS) as pool:
            futures = [pool.submit(_scan_one, row) for row in rows]
            for future in as_completed(futures):
                try:
                    future.result()
                except Exception:
                    pass
    finally:
        with _SCAN_LOCK:
            _SCAN_RUNNING = False


def _maybe_schedule_scan():
    global _SCAN_RUNNING, _LAST_SCAN_AT
    now = time.monotonic()
    with _SCAN_LOCK:
        if _SCAN_RUNNING or now - _LAST_SCAN_AT < SCAN_INTERVAL_SECONDS:
            return "running" if _SCAN_RUNNING else "fresh"
        _SCAN_RUNNING = True
        _LAST_SCAN_AT = now
    threading.Thread(target=_run_scan, daemon=True, name="nordicsignal-opportunity-scan").start()
    return "scheduled"


def opportunity_performance(limit=100):
    conn = connect()
    try:
        events = [dict(x) for x in conn.execute(
            "SELECT * FROM opportunity_events ORDER BY created_at DESC,id DESC LIMIT ?", (max(1, min(int(limit or 100), 500)),)
        ).fetchall()]
        returns = [dict(x) for x in conn.execute(
            "SELECT r.* FROM opportunity_forward_returns r JOIN opportunity_events e ON e.id=r.event_id "
            "ORDER BY e.created_at DESC,r.horizon_days"
        ).fetchall()]
    finally:
        conn.close()
    grouped = {h: [] for h in HORIZONS}
    for row in returns:
        h = int(row.get("horizon_days") or 0)
        if h in grouped and row.get("return_pct") is not None:
            grouped[h].append(float(row["return_pct"]))
    summary = {}
    for h, values in grouped.items():
        summary[str(h)] = {
            "n": len(values),
            "mean_return_pct": round(sum(values) / len(values), 3) if values else None,
            "positive_rate_pct": round(sum(v > 0 for v in values) / len(values) * 100.0, 2) if values else None,
        }
    return {"events": len(events), "horizons": summary, "recent_events": events[:20], "updated_at": _now()}


def install():
    if getattr(extra_api, "_opportunity_tracking_runtime", False):
        return
    _ensure_schema()

    original_live = opportunity.live_opportunity
    def tracked_live(ticker):
        result = original_live(ticker)
        try:
            record_opportunity(result)
            settle_forward_returns(result.get("ticker"))
        except Exception:
            pass
        return result
    opportunity.live_opportunity = tracked_live

    original_signal_events = signal_events_runtime.signal_events
    def signal_events_with_opportunity(asset_class="Aksjer", limit=12):
        result = original_signal_events(asset_class, limit)
        requested = str(asset_class or "Aksjer")
        if requested in ("Aksjer", "Alle"):
            scan_state = _maybe_schedule_scan()
            items = list(result.get("items") or []) + _event_items(limit)
            items.sort(key=lambda x: str(x.get("updated_at") or ""), reverse=True)
            result["items"] = items[: max(1, min(int(limit or 12), 30))]
            result["opportunity_tracking"] = {"enabled": True, "background_scan": scan_state, "horizons": list(HORIZONS)}
            result["meaning"] = "material score, trend/activity and Early Opportunity changes"
        return result
    signal_events_runtime.signal_events = signal_events_with_opportunity

    original_install = extra_api.install
    def patched_install(app):
        original_install(app)
        @app.get("/api/opportunity-performance")
        def opportunity_performance_route(limit: int = 100):
            return opportunity_performance(limit)
    extra_api.install = patched_install
    extra_api._opportunity_tracking_runtime = True


install()
