"""Point-in-time ownership snapshot engine for NordicSignal.

This module stores authoritative shareholder snapshots from external providers and
computes deltas without inferring ownership from news. It is intentionally model-
neutral: ownership observations never modify NordicSignal score, Opportunity,
High Conviction, thresholds or position sizing.

Adapters can call ``ingest_snapshot`` when a licensed daily Euronext Securities
feed or a dated public register extract is available. Read endpoints remain useful
before a provider is connected by reporting source/status truthfully.
"""
from __future__ import annotations

from datetime import datetime, timezone
import hashlib
import json

import extra_api
from database import connect, USING_POSTGRES

MODEL_POLICY = {
    "score_effect": "none",
    "opportunity_effect": "none",
    "high_conviction_effect": "none",
    "position_sizing_effect": "none",
    "rule": "point_in_time_evidence_only",
}

SOURCE_POLICY = {
    "euronext_securities_top_shareholders": {
        "authority": "official_register",
        "frequency": "daily_when_licensed",
        "status": "adapter_ready_not_configured",
    },
    "euronext_securities_top_changes": {
        "authority": "official_register",
        "frequency": "daily_when_licensed",
        "status": "adapter_ready_not_configured",
    },
    "skatteetaten_aksjonaerregisteret": {
        "authority": "official_annual_register",
        "frequency": "annual",
        "status": "adapter_ready_manual_extract",
    },
}


def _now():
    return datetime.now(timezone.utc).isoformat()


def _ensure_schema():
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn = connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS ownership_snapshots (
          id {identity},
          provider TEXT NOT NULL,
          ticker TEXT NOT NULL,
          as_of_date TEXT NOT NULL,
          captured_at TEXT NOT NULL,
          source_ref TEXT,
          holder_count INTEGER NOT NULL DEFAULT 0,
          payload_hash TEXT NOT NULL,
          UNIQUE(provider,ticker,as_of_date)
        );
        CREATE INDEX IF NOT EXISTS idx_ownership_snapshot_ticker_date
          ON ownership_snapshots(ticker,as_of_date);

        CREATE TABLE IF NOT EXISTS ownership_positions (
          snapshot_id BIGINT NOT NULL,
          holder_key TEXT NOT NULL,
          holder_name TEXT NOT NULL,
          holder_type TEXT,
          country TEXT,
          shares REAL,
          ownership_pct REAL,
          rank_no INTEGER,
          PRIMARY KEY(snapshot_id,holder_key)
        );
        CREATE INDEX IF NOT EXISTS idx_ownership_positions_holder
          ON ownership_positions(holder_key);

        CREATE TABLE IF NOT EXISTS ownership_changes (
          id {identity},
          provider TEXT NOT NULL,
          ticker TEXT NOT NULL,
          from_date TEXT,
          to_date TEXT NOT NULL,
          holder_key TEXT NOT NULL,
          holder_name TEXT NOT NULL,
          holder_type TEXT,
          country TEXT,
          shares_before REAL,
          shares_after REAL,
          shares_delta REAL,
          pct_before REAL,
          pct_after REAL,
          pct_delta REAL,
          change_kind TEXT NOT NULL,
          created_at TEXT NOT NULL,
          UNIQUE(provider,ticker,to_date,holder_key)
        );
        CREATE INDEX IF NOT EXISTS idx_ownership_changes_ticker_date
          ON ownership_changes(ticker,to_date);
        """)
        conn.commit()
    finally:
        conn.close()


def _holder_key(row):
    raw = "|".join([
        str(row.get("holder_id") or "").strip().lower(),
        str(row.get("name") or row.get("holder_name") or "").strip().lower(),
        str(row.get("country") or "").strip().lower(),
    ])
    return hashlib.sha256(raw.encode("utf-8", "ignore")).hexdigest()[:32]


def _num(value):
    try:
        return float(value) if value is not None and value != "" else None
    except (TypeError, ValueError):
        return None


def _normalize_holders(holders):
    out = []
    for raw in holders or []:
        if not isinstance(raw, dict):
            continue
        name = str(raw.get("name") or raw.get("holder_name") or "").strip()
        if not name:
            continue
        out.append({
            "holder_key": _holder_key(raw),
            "holder_name": name[:300],
            "holder_type": str(raw.get("holder_type") or "").strip()[:80] or None,
            "country": str(raw.get("country") or "").strip()[:80] or None,
            "shares": _num(raw.get("shares")),
            "ownership_pct": _num(raw.get("ownership_pct")),
            "rank_no": int(raw["rank"]) if str(raw.get("rank") or "").isdigit() else None,
        })
    return out


def ingest_snapshot(provider, ticker, as_of_date, holders, source_ref=None):
    """Store one immutable dated ownership snapshot and derive holder deltas.

    Re-ingesting the same provider/ticker/date with an identical payload is idempotent.
    A changed payload replaces positions for that exact dated snapshot and recomputes
    changes against the previous snapshot from the same provider.
    """
    provider = str(provider or "").strip()
    ticker = str(ticker or "").strip().upper().replace(".OL", "")
    as_of_date = str(as_of_date or "").strip()[:10]
    if not provider or not ticker or len(as_of_date) != 10:
        raise ValueError("provider, ticker and YYYY-MM-DD as_of_date are required")
    normalized = _normalize_holders(holders)
    payload_hash = hashlib.sha256(json.dumps(normalized, sort_keys=True, ensure_ascii=False).encode("utf-8")).hexdigest()
    captured_at = _now()
    conn = connect()
    try:
        existing = conn.execute(
            "SELECT id,payload_hash FROM ownership_snapshots WHERE provider=? AND ticker=? AND as_of_date=?",
            (provider, ticker, as_of_date),
        ).fetchone()
        if existing and existing["payload_hash"] == payload_hash:
            return {"status": "unchanged", "snapshot_id": int(existing["id"]), "holders": len(normalized)}
        if existing:
            snapshot_id = int(existing["id"])
            conn.execute("DELETE FROM ownership_positions WHERE snapshot_id=?", (snapshot_id,))
            conn.execute(
                "UPDATE ownership_snapshots SET captured_at=?,source_ref=?,holder_count=?,payload_hash=? WHERE id=?",
                (captured_at, source_ref, len(normalized), payload_hash, snapshot_id),
            )
        else:
            cur = conn.execute(
                "INSERT INTO ownership_snapshots(provider,ticker,as_of_date,captured_at,source_ref,holder_count,payload_hash) VALUES(?,?,?,?,?,?,?)",
                (provider, ticker, as_of_date, captured_at, source_ref, len(normalized), payload_hash),
            )
            snapshot_id = int(cur.lastrowid)
        for row in normalized:
            conn.execute(
                "INSERT INTO ownership_positions(snapshot_id,holder_key,holder_name,holder_type,country,shares,ownership_pct,rank_no) VALUES(?,?,?,?,?,?,?,?)",
                (snapshot_id,row["holder_key"],row["holder_name"],row["holder_type"],row["country"],row["shares"],row["ownership_pct"],row["rank_no"]),
            )

        prev = conn.execute(
            "SELECT id,as_of_date FROM ownership_snapshots WHERE provider=? AND ticker=? AND as_of_date<? ORDER BY as_of_date DESC LIMIT 1",
            (provider, ticker, as_of_date),
        ).fetchone()
        conn.execute("DELETE FROM ownership_changes WHERE provider=? AND ticker=? AND to_date=?", (provider,ticker,as_of_date))
        previous = {}
        if prev:
            rows = conn.execute("SELECT * FROM ownership_positions WHERE snapshot_id=?", (prev["id"],)).fetchall()
            previous = {r["holder_key"]: dict(r) for r in rows}
        current = {r["holder_key"]: r for r in normalized}
        for key in sorted(set(previous) | set(current)):
            before = previous.get(key)
            after = current.get(key)
            name = (after or before)["holder_name"]
            shares_before = _num(before.get("shares")) if before else None
            shares_after = _num(after.get("shares")) if after else None
            pct_before = _num(before.get("ownership_pct")) if before else None
            pct_after = _num(after.get("ownership_pct")) if after else None
            shares_delta = (shares_after - shares_before) if shares_before is not None and shares_after is not None else None
            pct_delta = (pct_after - pct_before) if pct_before is not None and pct_after is not None else None
            if before is None:
                kind = "ENTERED"
            elif after is None:
                kind = "EXITED"
            elif (shares_delta or 0) > 0 or (pct_delta or 0) > 0:
                kind = "INCREASED"
            elif (shares_delta or 0) < 0 or (pct_delta or 0) < 0:
                kind = "DECREASED"
            else:
                kind = "UNCHANGED"
            conn.execute(
                "INSERT INTO ownership_changes(provider,ticker,from_date,to_date,holder_key,holder_name,holder_type,country,shares_before,shares_after,shares_delta,pct_before,pct_after,pct_delta,change_kind,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (provider,ticker,prev["as_of_date"] if prev else None,as_of_date,key,name,(after or before).get("holder_type"),(after or before).get("country"),shares_before,shares_after,shares_delta,pct_before,pct_after,pct_delta,kind,captured_at),
            )
        conn.commit()
        return {"status": "stored", "snapshot_id": snapshot_id, "holders": len(normalized), "previous_date": prev["as_of_date"] if prev else None}
    finally:
        conn.close()


def status():
    conn = connect()
    try:
        snapshots = conn.execute("SELECT COUNT(*) AS n FROM ownership_snapshots").fetchone()
        tickers = conn.execute("SELECT COUNT(DISTINCT ticker) AS n FROM ownership_snapshots").fetchone()
        latest = conn.execute("SELECT MAX(as_of_date) AS d FROM ownership_snapshots").fetchone()
        return {
            "status": "ok",
            "snapshots": int(snapshots["n"] if snapshots else 0),
            "tickers": int(tickers["n"] if tickers else 0),
            "latest_as_of_date": latest["d"] if latest else None,
            "sources": SOURCE_POLICY,
            "policy": MODEL_POLICY,
            "generated_at": _now(),
        }
    finally:
        conn.close()


def ownership(ticker, limit=50):
    ticker = str(ticker or "").strip().upper().replace(".OL", "")
    limit = max(1, min(int(limit or 50), 200))
    conn = connect()
    try:
        snap = conn.execute("SELECT * FROM ownership_snapshots WHERE ticker=? ORDER BY as_of_date DESC, id DESC LIMIT 1", (ticker,)).fetchone()
        if not snap:
            return {"status":"no_snapshot","ticker":ticker,"positions":[],"changes":[],"policy":MODEL_POLICY,"sources":SOURCE_POLICY}
        positions = conn.execute(
            "SELECT holder_name,holder_type,country,shares,ownership_pct,rank_no FROM ownership_positions WHERE snapshot_id=? ORDER BY COALESCE(rank_no,999999),COALESCE(shares,0) DESC LIMIT ?",
            (snap["id"],limit),
        ).fetchall()
        changes = conn.execute(
            "SELECT holder_name,holder_type,country,shares_before,shares_after,shares_delta,pct_before,pct_after,pct_delta,change_kind,from_date,to_date FROM ownership_changes WHERE provider=? AND ticker=? AND to_date=? AND change_kind<>'UNCHANGED' ORDER BY ABS(COALESCE(shares_delta,0)) DESC LIMIT ?",
            (snap["provider"],ticker,snap["as_of_date"],limit),
        ).fetchall()
        return {
            "status":"ok","ticker":ticker,"provider":snap["provider"],"as_of_date":snap["as_of_date"],"source_ref":snap["source_ref"],
            "positions":[dict(r) for r in positions],"changes":[dict(r) for r in changes],"policy":MODEL_POLICY,
        }
    finally:
        conn.close()


def install():
    if getattr(extra_api, "_ownership_snapshot_runtime_v1", False):
        return
    _ensure_schema()
    original_install = extra_api.install
    def patched_install(app):
        original_install(app)
        @app.get("/api/ownership/status")
        def ownership_status():
            return status()
        @app.get("/api/ownership/{ticker}")
        def ownership_ticker(ticker: str, limit: int = 50):
            return ownership(ticker, limit)
    extra_api.install = patched_install
    extra_api._ownership_snapshot_runtime_v1 = True


install()
