"""Verified instrument identity registry for ownership ingestion.

NordicSignal's canonical ``stocks`` table does not currently carry ISIN. Ownership
providers may identify issuers by ISIN, so this registry provides an explicit,
auditable bridge without guessing from issuer names or symbols.

Only rows marked ``verified=1`` may resolve an external identifier to a ticker.
Nothing in this module changes score, Opportunity, High Conviction, thresholds,
or position sizing.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Mapping, Any

from database import connect, USING_POSTGRES


MODEL_POLICY = {
    "score_effect": "none",
    "opportunity_effect": "none",
    "high_conviction_effect": "none",
    "position_sizing_effect": "none",
    "rule": "identity_resolution_only",
}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _ensure_schema() -> None:
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn = connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS ownership_instrument_identifiers (
          id {identity},
          scheme TEXT NOT NULL,
          identifier TEXT NOT NULL,
          ticker TEXT NOT NULL,
          verified INTEGER NOT NULL DEFAULT 0,
          source_ref TEXT,
          verified_at TEXT,
          created_at TEXT NOT NULL,
          UNIQUE(scheme, identifier)
        );
        CREATE INDEX IF NOT EXISTS idx_ownership_identifier_ticker
          ON ownership_instrument_identifiers(ticker);
        """)
        conn.commit()
    finally:
        conn.close()


def _normalize_scheme(value: Any) -> str:
    scheme = str(value or "").strip().upper()
    if not scheme:
        raise ValueError("identifier scheme is required")
    return scheme


def _normalize_identifier(value: Any) -> str:
    identifier = "".join(str(value or "").strip().upper().split())
    if not identifier:
        raise ValueError("instrument identifier is required")
    return identifier


def _normalize_ticker(value: Any) -> str:
    ticker = str(value or "").strip().upper().replace(".OL", "")
    if not ticker:
        raise ValueError("ticker is required")
    return ticker


def register_verified_identifier(scheme: str, identifier: str, ticker: str, *, source_ref: str) -> dict:
    """Register a manually/provider-verified identifier mapping.

    A source reference is mandatory. Existing identifiers cannot silently move to
    another ticker: a conflicting mapping must be investigated explicitly.
    """
    scheme = _normalize_scheme(scheme)
    identifier = _normalize_identifier(identifier)
    ticker = _normalize_ticker(ticker)
    source_ref = str(source_ref or "").strip()
    if not source_ref:
        raise ValueError("verified identifier mapping requires source_ref")
    _ensure_schema()
    conn = connect()
    try:
        stock = conn.execute("SELECT ticker FROM stocks WHERE ticker=? AND active=1 LIMIT 1", (ticker,)).fetchone()
        if not stock:
            raise ValueError(f"cannot map identifier to unknown/inactive ticker: {ticker}")
        existing = conn.execute(
            "SELECT ticker,verified,source_ref FROM ownership_instrument_identifiers WHERE scheme=? AND identifier=?",
            (scheme, identifier),
        ).fetchone()
        if existing and str(existing["ticker"]).upper() != ticker:
            raise ValueError(
                f"conflicting verified identifier mapping for {scheme}:{identifier}: "
                f"{existing['ticker']} != {ticker}"
            )
        now = _now()
        if existing:
            conn.execute(
                "UPDATE ownership_instrument_identifiers SET verified=1,source_ref=?,verified_at=? WHERE scheme=? AND identifier=?",
                (source_ref, now, scheme, identifier),
            )
        else:
            conn.execute(
                "INSERT INTO ownership_instrument_identifiers(scheme,identifier,ticker,verified,source_ref,verified_at,created_at) VALUES(?,?,?,?,?,?,?)",
                (scheme, identifier, ticker, 1, source_ref, now, now),
            )
        conn.commit()
        return {"scheme": scheme, "identifier": identifier, "ticker": ticker, "verified": True, "source_ref": source_ref}
    finally:
        conn.close()


def resolve_identifier(scheme: str, identifier: str) -> str | None:
    """Resolve only explicitly verified identity mappings; never infer."""
    scheme = _normalize_scheme(scheme)
    identifier = _normalize_identifier(identifier)
    _ensure_schema()
    conn = connect()
    try:
        row = conn.execute(
            "SELECT ticker FROM ownership_instrument_identifiers WHERE scheme=? AND identifier=? AND verified=1 LIMIT 1",
            (scheme, identifier),
        ).fetchone()
        return _normalize_ticker(row["ticker"]) if row else None
    finally:
        conn.close()


def make_row_resolver(provider_field: str, *, scheme: str = "ISIN"):
    """Build an adapter resolver for an explicitly mapped provider identifier field."""
    field = str(provider_field or "").strip()
    if not field:
        raise ValueError("provider identifier field is required")

    def resolver(row: Mapping[str, Any]) -> str:
        ticker = resolve_identifier(scheme, row.get(field))
        if not ticker:
            raw = str(row.get(field) or "").strip()
            raise ValueError(f"no verified ticker mapping for {scheme.upper()}:{raw}")
        return ticker

    return resolver


def identity_status() -> dict:
    """Return truthful resolver coverage without implying ownership-feed coverage."""
    _ensure_schema()
    conn = connect()
    try:
        total = conn.execute("SELECT COUNT(*) AS n FROM ownership_instrument_identifiers").fetchone()["n"]
        verified = conn.execute("SELECT COUNT(*) AS n FROM ownership_instrument_identifiers WHERE verified=1").fetchone()["n"]
        isin = conn.execute("SELECT COUNT(*) AS n FROM ownership_instrument_identifiers WHERE verified=1 AND scheme='ISIN'").fetchone()["n"]
        return {
            "registry_rows": int(total or 0),
            "verified_rows": int(verified or 0),
            "verified_isin_rows": int(isin or 0),
            "inference_enabled": False,
            "model_policy": MODEL_POLICY,
        }
    finally:
        conn.close()
