"""Global instrument discovery and asset-class allocation for Holdings.

This runtime keeps the stable holdings ledger intact and adds a sidecar metadata
layer for instruments discovered through Yahoo Finance. It also adds explicit cash
balances and computes an allocation summary in NOK. Existing Oslo holdings without
metadata continue to work unchanged.
"""
from datetime import datetime, timezone
import time

from fastapi import HTTPException
from pydantic import BaseModel, Field

import extra_api
import holdings_routes
from database import connect, USING_POSTGRES
from providers import YahooProvider

_ALLOWED_QUOTE_TYPES = {
    'EQUITY', 'ETF', 'MUTUALFUND', 'MONEYMARKET', 'CLOSEDEND_FUND',
}
_ASSET_CLASS = {
    'EQUITY': 'Aksjer',
    'ETF': 'ETF',
    'MUTUALFUND': 'Fond',
    'MONEYMARKET': 'Fond',
    'CLOSEDEND_FUND': 'Fond',
}
_FX_CACHE = {}


def _now():
    return datetime.now(timezone.utc).isoformat()


def _clean(value, fallback=''):
    text = ' '.join(str(value or '').split()).strip()
    return text or fallback


def asset_class_for(quote_type):
    return _ASSET_CLASS.get(str(quote_type or '').strip().upper(), 'Øvrig')


def _ensure_schema():
    meta = '''
    CREATE TABLE IF NOT EXISTS holding_instrument_meta (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ticker TEXT NOT NULL,
      broker TEXT NOT NULL,
      account_type TEXT NOT NULL,
      market_symbol TEXT NOT NULL,
      instrument_name TEXT,
      quote_type TEXT,
      asset_class TEXT NOT NULL DEFAULT 'Øvrig',
      exchange TEXT,
      currency TEXT,
      updated_at TEXT NOT NULL,
      UNIQUE(ticker, broker, account_type)
    );
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS holding_instrument_meta (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ticker TEXT NOT NULL,
      broker TEXT NOT NULL,
      account_type TEXT NOT NULL,
      market_symbol TEXT NOT NULL,
      instrument_name TEXT,
      quote_type TEXT,
      asset_class TEXT NOT NULL DEFAULT 'Øvrig',
      exchange TEXT,
      currency TEXT,
      updated_at TEXT NOT NULL,
      UNIQUE(ticker, broker, account_type)
    );
    '''
    cash = '''
    CREATE TABLE IF NOT EXISTS holding_cash (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      broker TEXT NOT NULL,
      account_type TEXT NOT NULL,
      currency TEXT NOT NULL DEFAULT 'NOK',
      balance DOUBLE PRECISION NOT NULL DEFAULT 0,
      updated_at TEXT NOT NULL,
      UNIQUE(broker, account_type, currency)
    );
    ''' if USING_POSTGRES else '''
    CREATE TABLE IF NOT EXISTS holding_cash (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      broker TEXT NOT NULL,
      account_type TEXT NOT NULL,
      currency TEXT NOT NULL DEFAULT 'NOK',
      balance REAL NOT NULL DEFAULT 0,
      updated_at TEXT NOT NULL,
      UNIQUE(broker, account_type, currency)
    );
    '''
    conn = connect()
    try:
        conn.executescript(meta + '\n' + cash)
        conn.commit()
    finally:
        conn.close()


class InstrumentMetaIn(BaseModel):
    ticker: str = Field(min_length=1, max_length=40)
    broker: str = Field(default='Nordnet', min_length=1, max_length=60)
    account_type: str = Field(default='ASK', min_length=1, max_length=60)
    market_symbol: str = Field(min_length=1, max_length=60)
    instrument_name: str | None = Field(default=None, max_length=180)
    quote_type: str | None = Field(default=None, max_length=40)
    exchange: str | None = Field(default=None, max_length=100)
    currency: str | None = Field(default=None, max_length=12)


class CashIn(BaseModel):
    broker: str = Field(default='Nordnet', min_length=1, max_length=60)
    account_type: str = Field(default='ASK', min_length=1, max_length=60)
    currency: str = Field(default='NOK', min_length=3, max_length=12)
    balance: float = Field(ge=0, le=100_000_000_000)


def _metadata_rows():
    conn = connect()
    try:
        rows = conn.execute('SELECT * FROM holding_instrument_meta').fetchall()
    finally:
        conn.close()
    return [dict(row) for row in rows]


def _cash_rows():
    conn = connect()
    try:
        rows = conn.execute('SELECT * FROM holding_cash ORDER BY broker,account_type,currency').fetchall()
    finally:
        conn.close()
    return [dict(row) for row in rows]


def _exact_quote(provider, symbol):
    symbol = str(symbol or '').strip()
    if not symbol:
        raise RuntimeError('Missing market symbol')
    data = provider._get(
        f'{provider.BASE}/v8/finance/chart/{symbol}',
        {'range': '5d', 'interval': '1d'},
    )
    result = (data.get('chart', {}).get('result') or [None])[0]
    if not result:
        raise RuntimeError(f'No quote for {symbol}')
    meta = result.get('meta') or {}
    price = meta.get('regularMarketPrice')
    if price is None:
        price = meta.get('previousClose')
    if price is None:
        raise RuntimeError(f'No market price for {symbol}')
    return {
        'price': float(price),
        'currency': str(meta.get('currency') or '').upper() or None,
        'exchange': meta.get('exchangeName') or meta.get('fullExchangeName'),
    }


def _fx_to_nok(provider, currency):
    currency = str(currency or 'NOK').upper().strip()
    if currency in {'NOK', ''}:
        return 1.0
    cached = _FX_CACHE.get(currency)
    if cached and time.time() - cached[0] < 900:
        return cached[1]
    quote = _exact_quote(provider, f'{currency}NOK=X')
    rate = float(quote['price'])
    if rate <= 0:
        raise RuntimeError(f'Invalid FX rate {currency}/NOK')
    _FX_CACHE[currency] = (time.time(), rate)
    return rate


def search_instruments(provider, query, limit=12):
    query = _clean(query)
    if not query:
        return []
    limit = max(1, min(int(limit or 12), 25))
    response = provider.session.get(
        f'{provider.BASE}/v1/finance/search',
        params={
            'q': query,
            'quotesCount': max(limit * 3, 20),
            'newsCount': 0,
            'enableFuzzyQuery': 'true',
            'quotesQueryId': 'tss_match_phrase_query',
        },
        timeout=15,
        allow_redirects=True,
    )
    if response.status_code >= 400:
        raise RuntimeError(f'Instrument search HTTP {response.status_code}')
    data = response.json()
    out, seen = [], set()
    for row in data.get('quotes') or []:
        quote_type = str(row.get('quoteType') or '').upper()
        symbol = str(row.get('symbol') or '').strip()
        if quote_type not in _ALLOWED_QUOTE_TYPES or not symbol or symbol in seen:
            continue
        seen.add(symbol)
        out.append({
            'symbol': symbol,
            'ticker': symbol,
            'name': row.get('longname') or row.get('shortname') or symbol,
            'quote_type': quote_type,
            'asset_class': asset_class_for(quote_type),
            'exchange': row.get('exchDisp') or row.get('exchange'),
            'currency': row.get('currency'),
            'market': row.get('market'),
            'score': row.get('score'),
            'source': 'Yahoo Finance Search',
        })
        if len(out) >= limit:
            break
    return out


def _allocation(items, cash_rows):
    buckets = {}
    for item in items or []:
        value = item.get('market_value')
        if value is None:
            continue
        label = item.get('asset_class') or 'Aksjer'
        bucket = buckets.setdefault(label, {'asset_class': label, 'market_value': 0.0, 'positions': 0})
        bucket['market_value'] += float(value)
        bucket['positions'] += 1
    for cash in cash_rows or []:
        value = cash.get('market_value_nok')
        if value is None:
            continue
        bucket = buckets.setdefault('Kontanter', {'asset_class': 'Kontanter', 'market_value': 0.0, 'positions': 0})
        bucket['market_value'] += float(value)
        bucket['positions'] += 1
    total = sum(x['market_value'] for x in buckets.values())
    order = {'Aksjer': 0, 'Fond': 1, 'ETF': 2, 'Kontanter': 3, 'Øvrig': 4}
    rows = sorted(buckets.values(), key=lambda x: (order.get(x['asset_class'], 99), -x['market_value']))
    for row in rows:
        row['weight_pct'] = row['market_value'] / total * 100 if total > 0 else 0.0
    return rows, total


_original_snapshot = holdings_routes.build_holdings_snapshot


def build_holdings_snapshot_with_instruments(provider=None):
    provider = provider or YahooProvider()
    snapshot = _original_snapshot(provider)
    metadata = {
        (str(x['ticker']).upper(), x['broker'], x['account_type']): x
        for x in _metadata_rows()
    }
    quote_failures = []
    for item in snapshot.get('items') or []:
        key = (str(item.get('ticker') or '').upper(), item.get('broker'), item.get('account_type'))
        meta = metadata.get(key)
        if meta:
            item.update({
                'instrument_name': meta.get('instrument_name') or item.get('company_name') or item.get('ticker'),
                'market_symbol': meta.get('market_symbol'),
                'quote_type': meta.get('quote_type'),
                'asset_class': meta.get('asset_class') or asset_class_for(meta.get('quote_type')),
                'instrument_exchange': meta.get('exchange'),
                'instrument_currency': meta.get('currency'),
            })
            try:
                q = _exact_quote(provider, meta.get('market_symbol'))
                native_currency = str(q.get('currency') or meta.get('currency') or 'NOK').upper()
                fx = _fx_to_nok(provider, native_currency)
                native_price = float(q['price'])
                nok_price = native_price * fx
                shares = float(item.get('shares') or 0)
                invested_nok = shares * float(item.get('average_cost') or 0)
                market_nok = shares * nok_price
                pnl = market_nok - invested_nok
                item.update({
                    'current_price_native': native_price,
                    'native_currency': native_currency,
                    'fx_to_nok': fx,
                    'current_price': nok_price,
                    'market_value': market_nok,
                    'invested': invested_nok,
                    'unrealized_pnl': pnl,
                    'unrealized_pnl_pct': pnl / invested_nok * 100 if invested_nok else None,
                    'quote_source': 'Yahoo Finance exact symbol',
                    'quote_error': None,
                })
            except Exception as exc:
                item['quote_error'] = str(exc)
                quote_failures.append({'ticker': item.get('ticker'), 'symbol': meta.get('market_symbol'), 'error': str(exc)})
        else:
            item.update({
                'instrument_name': item.get('company_name') or item.get('ticker'),
                'market_symbol': item.get('ticker'),
                'quote_type': 'EQUITY',
                'asset_class': 'Aksjer',
                'instrument_exchange': item.get('exchange') or 'Oslo Børs',
                'instrument_currency': 'NOK',
            })

    items = snapshot.get('items') or []
    invested = sum(float(x.get('invested') or 0) for x in items)
    priced = [x for x in items if x.get('market_value') is not None]
    market_value = sum(float(x.get('market_value') or 0) for x in priced)
    priced_invested = sum(float(x.get('invested') or 0) for x in priced)
    pnl = market_value - priced_invested if priced else 0.0
    for item in items:
        item['portfolio_weight_pct'] = (
            float(item['market_value']) / market_value * 100
            if item.get('market_value') is not None and market_value > 0 else None
        )
    snapshot['summary'].update({
        'position_count': len(items),
        'priced_count': len(priced),
        'invested': invested,
        'market_value': market_value,
        'unrealized_pnl': pnl,
        'unrealized_pnl_pct': pnl / priced_invested * 100 if priced_invested else None,
    })

    sector_map = {}
    for item in priced:
        sector = item.get('sector') or 'Ukjent'
        bucket = sector_map.setdefault(sector, {'sector': sector, 'market_value': 0.0, 'positions': 0})
        bucket['market_value'] += float(item['market_value'])
        bucket['positions'] += 1
    snapshot['sectors'] = sorted(sector_map.values(), key=lambda x: x['market_value'], reverse=True)
    for sector in snapshot['sectors']:
        sector['weight_pct'] = sector['market_value'] / market_value * 100 if market_value else 0.0

    cash = []
    for row in _cash_rows():
        x = dict(row)
        try:
            fx = _fx_to_nok(provider, x.get('currency'))
            x['fx_to_nok'] = fx
            x['market_value_nok'] = float(x.get('balance') or 0) * fx
            x['quote_error'] = None
        except Exception as exc:
            x['fx_to_nok'] = None
            x['market_value_nok'] = None
            x['quote_error'] = str(exc)
        cash.append(x)
    allocation, total_with_cash = _allocation(items, cash)
    snapshot['cash'] = cash
    snapshot['asset_allocation'] = allocation
    snapshot['portfolio_value_with_cash'] = total_with_cash
    snapshot['allocation_priced_positions'] = len(priced)
    snapshot['allocation_unpriced_positions'] = len(items) - len(priced)
    snapshot['instrument_quote_failures'] = quote_failures
    snapshot['instrument_search_source'] = 'Yahoo Finance Search'
    return snapshot


def install():
    if getattr(holdings_routes, '_portfolio_instruments_installed', False):
        return
    holdings_routes.build_holdings_snapshot = build_holdings_snapshot_with_instruments
    holdings_routes._portfolio_instruments_installed = True

    original_install = extra_api.install

    def patched_install(app):
        original_install(app)
        _ensure_schema()
        provider = YahooProvider()

        @app.get('/api/instruments/search')
        def instrument_search(q: str = '', limit: int = 12):
            try:
                items = search_instruments(provider, q, limit)
                return {'query': q, 'items': items, 'source': 'Yahoo Finance Search'}
            except Exception as exc:
                raise HTTPException(502, detail=f'Instrument search unavailable: {exc}')

        @app.post('/api/holdings/instrument-meta')
        def save_instrument_meta(payload: InstrumentMetaIn):
            ticker = payload.ticker.strip().upper()
            broker = _clean(payload.broker, 'Nordnet')
            account = _clean(payload.account_type, 'ASK')
            symbol = payload.market_symbol.strip()
            quote_type = _clean(payload.quote_type).upper() or None
            asset_class = asset_class_for(quote_type)
            conn = connect()
            try:
                existing = conn.execute(
                    'SELECT id FROM holding_instrument_meta WHERE ticker=? AND broker=? AND account_type=? LIMIT 1',
                    (ticker, broker, account),
                ).fetchone()
                values = (
                    symbol, _clean(payload.instrument_name) or None, quote_type, asset_class,
                    _clean(payload.exchange) or None, _clean(payload.currency).upper() or None, _now(),
                )
                if existing:
                    conn.execute(
                        'UPDATE holding_instrument_meta SET market_symbol=?,instrument_name=?,quote_type=?,asset_class=?,exchange=?,currency=?,updated_at=? WHERE id=?',
                        values + (existing['id'],),
                    )
                else:
                    conn.execute(
                        'INSERT INTO holding_instrument_meta(ticker,broker,account_type,market_symbol,instrument_name,quote_type,asset_class,exchange,currency,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',
                        (ticker, broker, account) + values,
                    )
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'portfolio': holdings_routes.build_holdings_snapshot(provider)}

        @app.delete('/api/holdings/instrument-meta')
        def delete_instrument_meta(ticker: str, broker: str = 'Nordnet', account_type: str = 'ASK'):
            conn = connect()
            try:
                conn.execute(
                    'DELETE FROM holding_instrument_meta WHERE ticker=? AND broker=? AND account_type=?',
                    (ticker.strip().upper(), _clean(broker, 'Nordnet'), _clean(account_type, 'ASK')),
                )
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok'}

        @app.post('/api/holdings/cash')
        def save_cash(payload: CashIn):
            broker = _clean(payload.broker, 'Nordnet')
            account = _clean(payload.account_type, 'ASK')
            currency = payload.currency.strip().upper()
            conn = connect()
            try:
                existing = conn.execute(
                    'SELECT id FROM holding_cash WHERE broker=? AND account_type=? AND currency=? LIMIT 1',
                    (broker, account, currency),
                ).fetchone()
                if existing:
                    conn.execute(
                        'UPDATE holding_cash SET balance=?,updated_at=? WHERE id=?',
                        (payload.balance, _now(), existing['id']),
                    )
                else:
                    conn.execute(
                        'INSERT INTO holding_cash(broker,account_type,currency,balance,updated_at) VALUES(?,?,?,?,?)',
                        (broker, account, currency, payload.balance, _now()),
                    )
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'portfolio': holdings_routes.build_holdings_snapshot(provider)}

        @app.delete('/api/holdings/cash/{cash_id}')
        def delete_cash(cash_id: int):
            conn = connect()
            try:
                row = conn.execute('SELECT id FROM holding_cash WHERE id=? LIMIT 1', (cash_id,)).fetchone()
                if not row:
                    raise HTTPException(404, detail='Cash balance not found')
                conn.execute('DELETE FROM holding_cash WHERE id=?', (cash_id,))
                conn.commit()
            finally:
                conn.close()
            return {'status': 'ok', 'portfolio': holdings_routes.build_holdings_snapshot(provider)}

    extra_api.install = patched_install


install()
