"""Web Push infrastructure for installed NordicSignal PWAs.

Delivery is enabled only when VAPID keys are configured as server secrets. The
browser subscription is persisted in Postgres and new signal/trend events can be
sent even when the PWA is closed, provided the backend process is awake.
"""
from datetime import datetime, timezone, timedelta
import hashlib
import json
import os
import threading
import time

from fastapi import HTTPException
from pydantic import BaseModel, Field

import extra_api
from database import connect, USING_POSTGRES

try:
    from pywebpush import webpush, WebPushException
except Exception:  # pragma: no cover - readiness endpoint reports missing sender
    webpush = None
    WebPushException = Exception

VAPID_PUBLIC_KEY = os.getenv("NORDICSIGNAL_VAPID_PUBLIC_KEY", "").strip()
VAPID_PRIVATE_KEY = os.getenv("NORDICSIGNAL_VAPID_PRIVATE_KEY", "").strip()
VAPID_SUBJECT = os.getenv("NORDICSIGNAL_VAPID_SUBJECT", "mailto:nordicsignal@example.invalid").strip()
DISPATCH_INTERVAL_SECONDS = 60
_MAX_EVENTS_PER_CYCLE = 12
_DISPATCH_STARTED = False
_DISPATCH_LOCK = threading.Lock()


def _now():
    return datetime.now(timezone.utc).isoformat()


def _ready():
    return bool(VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY and VAPID_SUBJECT and webpush)


def _hash(endpoint):
    return hashlib.sha256(str(endpoint).encode("utf-8", "ignore")).hexdigest()


def _ensure_schema():
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn = connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS push_subscriptions (
          id {identity},
          endpoint_hash TEXT NOT NULL UNIQUE,
          endpoint TEXT NOT NULL,
          p256dh TEXT NOT NULL,
          auth TEXT NOT NULL,
          user_agent TEXT,
          enabled INTEGER NOT NULL DEFAULT 1,
          failure_count INTEGER NOT NULL DEFAULT 0,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL,
          last_success_at TEXT
        );
        CREATE TABLE IF NOT EXISTS push_deliveries (
          event_key TEXT NOT NULL,
          endpoint_hash TEXT NOT NULL,
          status TEXT NOT NULL,
          created_at TEXT NOT NULL,
          PRIMARY KEY(event_key,endpoint_hash)
        );
        """)
        conn.commit()
    finally:
        conn.close()


class PushKeys(BaseModel):
    p256dh: str = Field(min_length=16, max_length=512)
    auth: str = Field(min_length=8, max_length=256)


class PushSubscriptionIn(BaseModel):
    endpoint: str = Field(min_length=16, max_length=4096)
    keys: PushKeys
    user_agent: str | None = Field(default=None, max_length=400)


class PushEndpointIn(BaseModel):
    endpoint: str = Field(min_length=16, max_length=4096)


def subscribe(payload):
    endpoint = payload.endpoint.strip()
    if not endpoint.startswith("https://"):
        raise HTTPException(400, detail="Push endpoint must use HTTPS")
    key = _hash(endpoint)
    now = _now()
    conn = connect()
    try:
        row = conn.execute("SELECT endpoint_hash FROM push_subscriptions WHERE endpoint_hash=?", (key,)).fetchone()
        values = (endpoint, payload.keys.p256dh, payload.keys.auth, payload.user_agent, 1, 0, now, key)
        if row:
            conn.execute("UPDATE push_subscriptions SET endpoint=?,p256dh=?,auth=?,user_agent=?,enabled=?,failure_count=?,updated_at=? WHERE endpoint_hash=?", values)
        else:
            conn.execute("INSERT INTO push_subscriptions(endpoint,p256dh,auth,user_agent,enabled,failure_count,created_at,updated_at,endpoint_hash) VALUES(?,?,?,?,?,?,?, ?,?)", (endpoint, payload.keys.p256dh, payload.keys.auth, payload.user_agent, 1, 0, now, now, key))
        conn.commit()
    finally:
        conn.close()
    return {"status":"ok","endpoint_hash":key[:12],"delivery_ready":_ready(),"created_at":now}


def unsubscribe(endpoint):
    key = _hash(endpoint)
    conn = connect()
    try:
        conn.execute("UPDATE push_subscriptions SET enabled=0,updated_at=? WHERE endpoint_hash=?", (_now(), key))
        conn.commit()
    finally:
        conn.close()
    return {"status":"ok","enabled":False}


def _subscriptions():
    conn = connect()
    try:
        rows = conn.execute("SELECT * FROM push_subscriptions WHERE enabled=1 ORDER BY id").fetchall()
        return [dict(x) for x in rows]
    finally:
        conn.close()


def _delivered(event_key, endpoint_hash):
    conn = connect()
    try:
        row = conn.execute("SELECT 1 FROM push_deliveries WHERE event_key=? AND endpoint_hash=?", (event_key, endpoint_hash)).fetchone()
        return bool(row)
    finally:
        conn.close()


def _record_delivery(event_key, endpoint_hash, status):
    conn = connect()
    try:
        if not conn.execute("SELECT 1 FROM push_deliveries WHERE event_key=? AND endpoint_hash=?", (event_key, endpoint_hash)).fetchone():
            conn.execute("INSERT INTO push_deliveries(event_key,endpoint_hash,status,created_at) VALUES(?,?,?,?)", (event_key, endpoint_hash, status, _now()))
        conn.commit()
    finally:
        conn.close()


def _mark_subscription(endpoint_hash, success=True, disable=False):
    conn = connect()
    try:
        if success:
            conn.execute("UPDATE push_subscriptions SET failure_count=0,last_success_at=?,updated_at=? WHERE endpoint_hash=?", (_now(), _now(), endpoint_hash))
        elif disable:
            conn.execute("UPDATE push_subscriptions SET enabled=0,failure_count=failure_count+1,updated_at=? WHERE endpoint_hash=?", (_now(), endpoint_hash))
        else:
            conn.execute("UPDATE push_subscriptions SET failure_count=failure_count+1,updated_at=? WHERE endpoint_hash=?", (_now(), endpoint_hash))
        conn.commit()
    finally:
        conn.close()


def _send(subscription, payload):
    if not _ready():
        return False, "not_configured"
    info = {"endpoint":subscription["endpoint"], "keys":{"p256dh":subscription["p256dh"], "auth":subscription["auth"]}}
    try:
        webpush(
            subscription_info=info,
            data=json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
            vapid_private_key=VAPID_PRIVATE_KEY,
            vapid_claims={"sub":VAPID_SUBJECT},
            ttl=3600,
        )
        _mark_subscription(subscription["endpoint_hash"], success=True)
        return True, "sent"
    except WebPushException as exc:
        status = getattr(getattr(exc, "response", None), "status_code", None)
        _mark_subscription(subscription["endpoint_hash"], success=False, disable=status in (404, 410))
        return False, f"http_{status}" if status else "delivery_error"
    except Exception:
        _mark_subscription(subscription["endpoint_hash"], success=False)
        return False, "delivery_error"


def _event_rows(since):
    items = []
    conn = connect()
    try:
        try:
            rows = conn.execute("SELECT id,symbol,name,kind,direction,signal,event,detail,created_at FROM trend_activity_events WHERE created_at>? ORDER BY id DESC LIMIT ?", (since, _MAX_EVENTS_PER_CYCLE)).fetchall()
            for x in rows:
                d = dict(x)
                items.append({"event_key":f"trend:{d['id']}","ticker":d["symbol"],"title":f"{d['symbol']} · {d['event']}","body":d.get("detail") or d.get("event"),"url":f"/stock?ticker={d['symbol']}","created_at":d["created_at"]})
        except Exception:
            pass
        try:
            rows = conn.execute("SELECT id,symbol,name,signal,event,created_at FROM signal_events WHERE created_at>? ORDER BY id DESC LIMIT ?", (since, _MAX_EVENTS_PER_CYCLE)).fetchall()
            for x in rows:
                d = dict(x)
                items.append({"event_key":f"score:{d['id']}","ticker":d["symbol"],"title":f"{d['symbol']} · Signalendring","body":d.get("event") or d.get("signal"),"url":f"/stock?ticker={d['symbol']}","created_at":d["created_at"]})
        except Exception:
            pass
    finally:
        conn.close()
    items.sort(key=lambda x: str(x.get("created_at") or ""))
    return items[-_MAX_EVENTS_PER_CYCLE:]


def dispatch_once():
    if not _ready():
        return {"status":"not_configured","sent":0}
    subs = _subscriptions()
    if not subs:
        return {"status":"no_subscriptions","sent":0}
    earliest = min(str(x.get("created_at") or _now()) for x in subs)
    events = _event_rows(earliest)
    sent = 0
    attempted = 0
    for event in events:
        payload = {"title":event["title"],"body":event["body"],"url":event["url"],"tag":event["event_key"],"timestamp":event["created_at"]}
        for sub in subs:
            if str(event["created_at"]) <= str(sub.get("created_at") or ""):
                continue
            if _delivered(event["event_key"], sub["endpoint_hash"]):
                continue
            attempted += 1
            ok, status = _send(sub, payload)
            _record_delivery(event["event_key"], sub["endpoint_hash"], status)
            if ok:
                sent += 1
    return {"status":"ok","subscriptions":len(subs),"events":len(events),"attempted":attempted,"sent":sent}


def _dispatch_loop():
    time.sleep(20)
    while True:
        try:
            dispatch_once()
        except Exception:
            pass
        time.sleep(DISPATCH_INTERVAL_SECONDS)


def _start_dispatcher():
    global _DISPATCH_STARTED
    with _DISPATCH_LOCK:
        if _DISPATCH_STARTED:
            return
        _DISPATCH_STARTED = True
        threading.Thread(target=_dispatch_loop, daemon=True, name="nordicsignal-webpush").start()


def push_status():
    count = 0
    try:
        count = len(_subscriptions())
    except Exception:
        pass
    return {
        "status":"ok",
        "supported":True,
        "delivery_ready":_ready(),
        "public_key_configured":bool(VAPID_PUBLIC_KEY),
        "private_key_configured":bool(VAPID_PRIVATE_KEY),
        "active_subscriptions":count,
        "dispatcher_interval_seconds":DISPATCH_INTERVAL_SECONDS,
        "backend_awake_required":True,
        "note":"Real Web Push works for installed iPhone PWAs when VAPID secrets are configured. A sleeping backend cannot dispatch until it wakes.",
        "generated_at":_now(),
    }


def install():
    if getattr(extra_api, "_push_runtime_installed", False):
        return
    original_install = extra_api.install

    def patched_install(app):
        original_install(app)
        _ensure_schema()
        _start_dispatcher()

        @app.get("/api/push/public-key")
        def push_public_key():
            return {"configured":bool(VAPID_PUBLIC_KEY),"public_key":VAPID_PUBLIC_KEY or None}

        @app.get("/api/push/status")
        def push_status_route():
            return push_status()

        @app.post("/api/push/subscribe")
        def push_subscribe(payload: PushSubscriptionIn):
            return subscribe(payload)

        @app.post("/api/push/unsubscribe")
        def push_unsubscribe(payload: PushEndpointIn):
            return unsubscribe(payload.endpoint)

        @app.post("/api/push/test")
        def push_test(payload: PushEndpointIn):
            if not _ready():
                raise HTTPException(503, detail="VAPID push delivery is not configured")
            key = _hash(payload.endpoint)
            conn = connect()
            try:
                row = conn.execute("SELECT * FROM push_subscriptions WHERE endpoint_hash=? AND enabled=1", (key,)).fetchone()
            finally:
                conn.close()
            if not row:
                raise HTTPException(404, detail="Push subscription not found")
            ok, status = _send(dict(row), {"title":"NordicSignal","body":"Push-varsler fungerer.","url":"/mobile","tag":"push-test","timestamp":_now()})
            if not ok:
                raise HTTPException(502, detail=f"Push delivery failed: {status}")
            return {"status":"ok","delivered":True}

    extra_api.install = patched_install
    extra_api._push_runtime_installed = True


install()
