"""Security hardening for NordicSignal API.

The current product is a single-user application and does not pretend that a client-
side password is authentication. This layer adds useful controls today and supports a
real Worker-to-backend shared secret when the same NORDICSIGNAL_WRITE_TOKEN is
configured in Render and Cloudflare.
"""
from collections import OrderedDict, deque
from datetime import datetime, timezone
import hashlib
import hmac
import os
import threading
import time
import uuid

from fastapi import Request
from starlette.responses import JSONResponse

import extra_api
from database import connect, USING_POSTGRES

WRITE_TOKEN = os.getenv("NORDICSIGNAL_WRITE_TOKEN", "").strip()
DEFAULT_ORIGINS = (
    "https://nordicsignal.8pnwk5r8f4.workers.dev",
    "http://localhost",
    "http://127.0.0.1",
)
ALLOWED_ORIGINS = tuple(
    x.strip().rstrip("/") for x in os.getenv("NORDICSIGNAL_ALLOWED_ORIGINS", ",".join(DEFAULT_ORIGINS)).split(",") if x.strip()
)
WRITE_LIMIT_PER_MINUTE = 30
REFRESH_LIMIT_PER_MINUTE = 4
_MAX_CLIENTS = 512
_RATE_LOCK = threading.RLock()
_RATE = OrderedDict()


def _now():
    return datetime.now(timezone.utc).isoformat()


def _ensure_schema():
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn = connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS security_audit (
          id {identity},
          request_id TEXT NOT NULL,
          method TEXT NOT NULL,
          path TEXT NOT NULL,
          status_code INTEGER NOT NULL,
          origin TEXT,
          auth_mode TEXT NOT NULL,
          created_at TEXT NOT NULL
        );
        """)
        conn.commit()
    finally:
        conn.close()


def _client_key(request):
    forwarded = request.headers.get("cf-connecting-ip") or request.headers.get("x-forwarded-for") or "unknown"
    first = forwarded.split(",", 1)[0].strip()
    # Keep raw client addresses out of process state and audit storage.
    return hashlib.sha256(first.encode("utf-8", "ignore")).hexdigest()[:20]


def _rate_allowed(key, limit):
    now = time.monotonic()
    with _RATE_LOCK:
        q = _RATE.get(key)
        if q is None:
            q = deque()
            _RATE[key] = q
        while q and now - q[0] > 60.0:
            q.popleft()
        if len(q) >= limit:
            return False, max(1, int(60 - (now - q[0])))
        q.append(now)
        _RATE.move_to_end(key)
        while len(_RATE) > _MAX_CLIENTS:
            _RATE.popitem(last=False)
        return True, 0


def _origin_allowed(value):
    value = str(value or "").strip().rstrip("/")
    if not value:
        return True
    return any(value == allowed or value.startswith(allowed + "/") for allowed in ALLOWED_ORIGINS)


def _auth_ok(request):
    if not WRITE_TOKEN:
        return True, "same_origin_guard"
    supplied = request.headers.get("x-nordicsignal-internal-token", "")
    if not supplied:
        auth = request.headers.get("authorization", "")
        supplied = auth[7:].strip() if auth.lower().startswith("bearer ") else ""
    return hmac.compare_digest(str(supplied), WRITE_TOKEN), "shared_secret"


def _audit(request_id, method, path, status_code, origin, auth_mode):
    conn = None
    try:
        conn = connect()
        conn.execute(
            "INSERT INTO security_audit(request_id,method,path,status_code,origin,auth_mode,created_at) VALUES(?,?,?,?,?,?,?)",
            (request_id, method, path, int(status_code), str(origin or "")[:180] or None, auth_mode, _now()),
        )
        conn.commit()
    except Exception:
        try:
            if conn is not None:
                conn.rollback()
        except Exception:
            pass
    finally:
        try:
            if conn is not None:
                conn.close()
        except Exception:
            pass


def security_status():
    count = 0
    latest = None
    try:
        conn = connect()
        row = conn.execute("SELECT COUNT(*) n,MAX(created_at) latest FROM security_audit").fetchone()
        conn.close()
        count = int(row["n"] or 0) if row else 0
        latest = row["latest"] if row else None
    except Exception:
        pass
    return {
        "status": "ok",
        "authentication": "external_access_not_configured",
        "write_protection": "shared_secret" if WRITE_TOKEN else "same_origin_guard",
        "shared_secret_configured": bool(WRITE_TOKEN),
        "audit_events": count,
        "latest_audit_at": latest,
        "rate_limits": {"writes_per_minute": WRITE_LIMIT_PER_MINUTE, "refresh_per_minute": REFRESH_LIMIT_PER_MINUTE},
        "allowed_origins": list(ALLOWED_ORIGINS),
        "note": "For private/commercial use, put Cloudflare Access or equivalent real authentication in front of the app. Client-side password gates are intentionally not treated as security.",
        "generated_at": _now(),
    }


def install():
    if getattr(extra_api, "_security_runtime_installed", False):
        return
    original_install = extra_api.install

    def patched_install(app):
        original_install(app)
        _ensure_schema()

        @app.get("/api/security-status")
        def security_status_route():
            return security_status()

        if not getattr(app.state, "nordicsignal_security_runtime", False):
            app.state.nordicsignal_security_runtime = True

            @app.middleware("http")
            async def nordicsignal_security(request: Request, call_next):
                path = request.url.path
                method = request.method.upper()
                is_api = path.startswith("/api/")
                is_write = is_api and method in {"POST", "PUT", "PATCH", "DELETE"}
                is_refresh = is_api and (path == "/api/refresh" or path.endswith("/refresh"))
                origin = request.headers.get("origin") or ""
                request_id = request.headers.get("x-request-id") or str(uuid.uuid4())
                auth_mode = "read_only"

                if is_write or is_refresh:
                    auth_ok, auth_mode = _auth_ok(request)
                    if not auth_ok:
                        return JSONResponse({"status":"error","code":"WRITE_AUTH_REQUIRED","message":"Write operation is not authorized","request_id":request_id}, status_code=401)
                    if origin and not _origin_allowed(origin):
                        return JSONResponse({"status":"error","code":"ORIGIN_NOT_ALLOWED","message":"Cross-origin write blocked","request_id":request_id}, status_code=403)
                    key = _client_key(request) + (":refresh" if is_refresh else ":write")
                    allowed, retry = _rate_allowed(key, REFRESH_LIMIT_PER_MINUTE if is_refresh else WRITE_LIMIT_PER_MINUTE)
                    if not allowed:
                        return JSONResponse({"status":"busy","code":"RATE_LIMITED","retry_after_seconds":retry,"request_id":request_id}, status_code=429, headers={"Retry-After":str(retry)})

                response = await call_next(request)
                if is_api:
                    response.headers["x-content-type-options"] = "nosniff"
                    response.headers["referrer-policy"] = "no-referrer"
                    response.headers["permissions-policy"] = "camera=(), microphone=(), geolocation=()"
                    response.headers["x-request-id"] = request_id
                if is_write or is_refresh:
                    _audit(request_id, method, path, response.status_code, origin, auth_mode)
                return response

    extra_api.install = patched_install
    extra_api._security_runtime_installed = True


install()
