"""Latest signal-change feed for stocks, funds and ETFs.

Top Signals is a current ranking. Latest Signals should instead answer a different
question: what changed recently? This runtime emits only material score moves or
signal-band changes, so the dashboard does not repeat the same ranked instruments
in both panels.
"""
from datetime import datetime, timezone
import json

from fastapi import HTTPException

import extra_api
from database import connect, USING_POSTGRES
from providers import YahooProvider
from scoring import signal_label
import instrument_signal_runtime

SUPPORTED = {"Aksjer", "Fond", "ETF", "Alle"}
MIN_SCORE_MOVE = 2.0


def _now():
    return datetime.now(timezone.utc).isoformat()


def _strength(signal):
    value = str(signal or "").lower()
    return "strong" if value == "strong" else "risk" if value == "risk" else "watch" if value == "watch" else "neutral"


def _ensure_schema():
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USING_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"
    conn = connect()
    try:
        conn.executescript(f"""
        CREATE TABLE IF NOT EXISTS signal_event_state (
          symbol TEXT PRIMARY KEY,
          asset_class TEXT NOT NULL,
          score DOUBLE PRECISION NOT NULL,
          signal TEXT NOT NULL,
          updated_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS signal_events (
          id {identity},
          symbol TEXT NOT NULL,
          name TEXT NOT NULL,
          asset_class TEXT NOT NULL,
          previous_score DOUBLE PRECISION,
          score DOUBLE PRECISION NOT NULL,
          previous_signal TEXT,
          signal TEXT NOT NULL,
          event TEXT NOT NULL,
          exchange TEXT,
          currency TEXT,
          quote_type TEXT,
          created_at TEXT NOT NULL
        );
        """)
        conn.commit()
    finally:
        conn.close()


def _event_text(previous_score, score, previous_signal, signal):
    delta = float(score) - float(previous_score)
    if previous_signal != signal:
        arrow = "↑" if delta > 0 else "↓" if delta < 0 else "→"
        return f"{previous_signal} {arrow} {signal}"
    arrow = "↑" if delta > 0 else "↓"
    return f"Score {arrow} {abs(delta):.0f} poeng"


def build_stock_events(rows, limit=20):
    """Build one latest material change per ticker from score-history rows.

    Rows must be newest first and include ticker, total and created_at. This helper is
    pure enough for unit tests and deliberately ignores unchanged refreshes.
    """
    grouped = {}
    for raw in rows or []:
        row = dict(raw)
        grouped.setdefault(str(row.get("ticker") or ""), []).append(row)

    events = []
    for ticker, history in grouped.items():
        if not ticker or len(history) < 2:
            continue
        latest = history[0]
        previous = history[1]
        current_score = float(latest.get("total") or 0)
        previous_score = float(previous.get("total") or 0)
        current_signal = signal_label(current_score)
        previous_signal = signal_label(previous_score)
        delta = current_score - previous_score
        if current_signal == previous_signal and abs(delta) < MIN_SCORE_MOVE:
            continue
        events.append({
            "ticker": ticker,
            "symbol": ticker,
            "name": latest.get("name") or ticker,
            "sector": latest.get("sector"),
            "asset_class": "Aksjer",
            "previous_score": previous_score,
            "score": current_score,
            "score_delta": delta,
            "previous_signal": previous_signal,
            "signal": current_signal,
            "strength": _strength(current_signal),
            "event": _event_text(previous_score, current_score, previous_signal, current_signal),
            "updated_at": latest.get("created_at"),
            "score_source": latest.get("source") or "stored",
        })
    events.sort(key=lambda x: str(x.get("updated_at") or ""), reverse=True)
    return events[: max(1, min(int(limit or 20), 50))]


def _stock_events(limit):
    conn = connect()
    try:
        rows = conn.execute(
            "SELECT sc.ticker,sc.total,sc.created_at,COALESCE(sc.source,'stored') source,s.name,s.sector "
            "FROM scores sc JOIN stocks s ON s.ticker=sc.ticker WHERE s.active=1 "
            "ORDER BY sc.ticker,sc.id DESC"
        ).fetchall()
    finally:
        conn.close()
    # Only the newest two score snapshots per ticker are needed.
    trimmed, counts = [], {}
    for row in rows:
        ticker = row["ticker"]
        if counts.get(ticker, 0) >= 2:
            continue
        trimmed.append(dict(row))
        counts[ticker] = counts.get(ticker, 0) + 1
    return build_stock_events(trimmed, limit)


def _state_row(symbol):
    conn = connect()
    try:
        row = conn.execute("SELECT * FROM signal_event_state WHERE symbol=?", (symbol,)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def _set_state(item):
    symbol = str(item.get("symbol") or item.get("ticker") or "").upper()
    conn = connect()
    try:
        row = conn.execute("SELECT symbol FROM signal_event_state WHERE symbol=?", (symbol,)).fetchone()
        values = (item.get("asset_class") or "Øvrig", float(item.get("score") or 0), item.get("signal") or "Watch", _now(), symbol)
        if row:
            conn.execute("UPDATE signal_event_state SET asset_class=?,score=?,signal=?,updated_at=? WHERE symbol=?", values)
        else:
            conn.execute("INSERT INTO signal_event_state(asset_class,score,signal,updated_at,symbol) VALUES(?,?,?,?,?)", values)
        conn.commit()
    finally:
        conn.close()


def _record_external_event(item, previous):
    current_score = float(item.get("score") or 0)
    previous_score = float(previous.get("score") or 0)
    current_signal = str(item.get("signal") or "Watch")
    previous_signal = str(previous.get("signal") or "Watch")
    delta = current_score - previous_score
    if current_signal == previous_signal and abs(delta) < MIN_SCORE_MOVE:
        return False
    created = item.get("updated_at") or _now()
    conn = connect()
    try:
        conn.execute(
            "INSERT INTO signal_events(symbol,name,asset_class,previous_score,score,previous_signal,signal,event,exchange,currency,quote_type,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",
            (
                str(item.get("symbol") or item.get("ticker") or "").upper(),
                item.get("name") or item.get("symbol") or item.get("ticker") or "Instrument",
                item.get("asset_class") or "Øvrig",
                previous_score,
                current_score,
                previous_signal,
                current_signal,
                _event_text(previous_score, current_score, previous_signal, current_signal),
                item.get("exchange"),
                item.get("currency"),
                item.get("quote_type"),
                created,
            ),
        )
        conn.commit()
    finally:
        conn.close()
    return True


def _refresh_external_state(provider, asset_class):
    rows = instrument_signal_runtime._catalog_rows(asset_class, 30)
    for meta in rows:
        try:
            item = instrument_signal_runtime._build_signal(provider, meta, refresh=False)
        except Exception:
            continue
        symbol = str(item.get("symbol") or item.get("ticker") or "").upper()
        previous = _state_row(symbol)
        if previous is None:
            # First observation is a baseline, not a fake "latest change".
            _set_state(item)
            continue
        changed = _record_external_event(item, previous)
        if changed:
            _set_state(item)


def _external_events(asset_class, limit):
    provider = YahooProvider()
    _refresh_external_state(provider, asset_class)
    conn = connect()
    try:
        rows = conn.execute(
            "SELECT * FROM signal_events WHERE asset_class=? ORDER BY created_at DESC,id DESC LIMIT ?",
            (asset_class, max(1, min(int(limit or 20), 50))),
        ).fetchall()
    finally:
        conn.close()
    items = []
    for raw in rows:
        x = dict(raw)
        delta = float(x.get("score") or 0) - float(x.get("previous_score") or 0)
        x.update({
            "ticker": x.get("symbol"),
            "score_delta": delta,
            "strength": _strength(x.get("signal")),
            "updated_at": x.get("created_at"),
            "score_source": "history_model",
        })
        items.append(x)
    return items


def signal_events(asset_class="Aksjer", limit=12):
    requested = str(asset_class or "Aksjer").strip()
    if requested not in SUPPORTED:
        raise HTTPException(400, detail="asset_class must be Aksjer, Fond, ETF or Alle")
    limit = max(1, min(int(limit or 12), 30))
    if requested == "Aksjer":
        items = _stock_events(limit)
    elif requested in ("Fond", "ETF"):
        items = _external_events(requested, limit)
    else:
        items = _stock_events(limit)
        items += _external_events("Fond", limit)
        items += _external_events("ETF", limit)
        items.sort(key=lambda x: str(x.get("updated_at") or ""), reverse=True)
        items = items[:limit]
    return {
        "asset_class": requested,
        "items": items,
        "meaning": "material signal changes only",
        "minimum_score_move": MIN_SCORE_MOVE,
        "updated_at": _now(),
    }


def install():
    if getattr(extra_api, "_signal_events_runtime_installed", False):
        return
    original_install = extra_api.install

    def patched_install(app):
        original_install(app)
        _ensure_schema()

        @app.get("/api/signal-events")
        def signal_events_route(asset_class: str = "Aksjer", limit: int = 12):
            return signal_events(asset_class, limit)

    extra_api.install = patched_install
    extra_api._signal_events_runtime_installed = True
